SonarSource/sonar-scanner-msbuild

SonarQube.Common/FilePropertiesProvider.cs, SonarQube.Common/ProjectInfo/ProjectInfo.cs, SonarQube.Common/ProjectInfo/ProjectInfoExtensions.cs, SonarQube.MSBuild.Tasks/BuildTaskConstants.cs, SonarQube.MSBuild.Tasks/Resources.Designer.cs, SonarQube.MSBuild.Tasks/Resources.resx, SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, SonarQube.MSBuild.Tasks/WriteProjectInfoFile.cs, SonarRunner.Shim/PropertiesWriter.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/Infrastructure/DummyBuildEngine.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/IsTestFileByNameTests.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/WriteProjectInfoFileTests.cs, Tests/SonarRunner.Shim.Tests/PropertiesWriterTest.cs
* updated the targets file to pass a list of SonarQubeSetting items to the WriteProjectItemTask
* updated the WriteProjectItemTask to handle accept a list of TaskItems that it writes into the ProjectInfo.xml file.
* updated the PropertiesWriter to emit the settings from the ProjectInfo.xml file into the sonar-project.properties file
* added units tests for the task and properties writer
* added an integration test for the targets
=> SONARMSBRU-28: allow analysis settings to be supplied in MSBuild projects

SonarQube.Bootstrapper/BootstrapperSettings.cs, SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.ImportBefore.targets, SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, SonarQube.TeamBuild.Integration/TeamBuildSettings.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperSettingsTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/ImportBeforeTargetsTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarIntegrationTargetsTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, Tests/SonarQube.TeamBuild.Integration.Tests/TeamBuildSettingsTests.cs, VsoBuildStepSources/SonarQubePostBuild/SonarQubePostBuild.ps1
This quite large PR includes the following:
1) Support of the current working directory as a temporary analysis folder - it does not clean the folder automatically during the preprocessing step (that will come with http://jira.sonarsource.com/browse/SONARMSBRU-50)
2) Logic simplification within targets files: The presence of `SonarQubeTempPath` is now driving whether or not to perform the analysis, whereas it previously was a combination of that plus `RunSonarQubeAnalysis`. The implementation targets file also no longer knows anything about TFS 2013 or 2015
3) A few hacks are introduced to keep the integration tests running. I'll submit a separate PR to factorize the logic to run an end-to-end test, so that we won't have to update many places in case of future changes in the targets …
=> SONARMSBRU-43 Set the temporary folder to '.sonarqube' within the CWD

.gitattributes, SonarQube.Bootstrapper/App.config, SonarQube.Bootstrapper/BootstrapperSettings.cs, SonarQube.Bootstrapper/IBootstrapperSettings.cs, SonarQube.Bootstrapper/Program.cs, SonarQube.Bootstrapper/Properties/Settings.Designer.cs, SonarQube.Bootstrapper/Properties/Settings.settings, SonarQube.TeamBuild.Integration/TeamBuildSettings.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperSettingsTests.cs, Tests/SonarQube.Bootstrapper.Tests/Infrastructure/AppConfigWrapper.cs, Tests/SonarQube.TeamBuild.Integration.Tests/TeamBuildSettingsTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/PreprocessTestUtils.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorExeTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs
The previous PR regarding SONARMSBRU-43 actually only changed the .targets files and the Build vNext powershell script to look for a `.sonarqube` folder in the current working directory, if executed outside of TFS.
This one applies the same strategy, but to the Bootstrapper and the TFS Integration.
Note that, the TFS Integration now no longer duplicated the logic to find the location of the `.sonarqube` folder: It expects it its own current working directory.
The bootstrapper, which knows how to compute the `.sonarqube` path, launches both the pre&post processors with their current working directory set to it appropriately.
=> SONARMSBRU-43 Use the .sonarqube folder in CWD in the bootstrapper

SonarQube.Bootstrapper/ArgumentProcessor.cs, SonarQube.Bootstrapper/BootstrapperSettings.cs, SonarQube.Bootstrapper/Interfaces/IBootstrapperSettings.cs, SonarQube.Bootstrapper/Program.cs, SonarQube.Bootstrapper/Resources.Designer.cs, SonarQube.Bootstrapper/Resources.resx, SonarQube.Common/AnalysisProperties/FilePropertyProvider.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperExeTests.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperSettingsTests.cs, Tests/SonarQube.Common.UnitTests/FilePropertyProviderTests.cs, Tests/TestUtilities/SQPropertiesFileReader.cs
If the bootstrapper is using its default settings file, it will need to explicitly pass the location of that file to the pre-processor using the /s: switch.
Added unit tests.
=> SONARMSBRU-79: pass the default settings file location to the pre-processor

SonarQube.Bootstrapper/ArgumentProcessor.cs, SonarQube.Common/CommandLine/ArgumentDescriptor.cs, SonarQube.Common/CommandLine/CommandLineParser.cs, Tests/SonarQube.Bootstrapper.Tests/ArgumentProcessorTests.cs, Tests/SonarQube.Common.UnitTests/CommandLineParserTests.cs
e.g."beginX" should not be recognised a the verb "begin"
Added unit tests
=> SONARMSBRU-101: verbs should match whole argument

SonarQube.MSBuild.Tasks/Docs/IntegrationTargetDependencies.dgml, SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj, SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs
Simplified the main targets file and removed dependencies on the managed-only "CoreCompile" target.
Fixed up existing unit test.
Add new end-to-end tests for unrecognised project types (i.e. ones that do not import the standard managed targets or set the normal properties).
=> SONARMSBRU-96: simplify targets file

SonarQube.Bootstrapper/SonarQube.Analysis.xml, Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs
Simplifies the user experience for users who have authentication enabled.
I don't think we want to provide suggested values in the placeholders. By default, authentication is turned off so only users who have enabled authentication will need them, and it's up to them which account they want to use.
=> SONARMSBRU-79: added placeholders to default config file for server credentials

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/WellKnownProjectProperties.cs
One-character change in the targets file: correct property name is "PropertyTypeGuids", not "PropertyTypeGuid".
There are existing unit and integration tests but they all used the wrong name too...
=> [SONARSMSBRU-107] Fix detection of MSTest projects

SonarQube.Common/Serializer.cs
If you want to share the build server across multiple agents with the same config file you need this change. Without it the following code throws an in use exception even though it's only trying to read.
using (File.Open(fileName, FileMode.Open, FileAccess.Read))
using (File.Open(fileName, FileMode.Open, FileAccess.Read)  ;
the following allows multiple readers:
using (File.Open(fileName, FileMode.Open, FileAccess.Read, FileShare.Read))
using (File.Open(fileName, FileMode.Open, FileAccess.Read, FileShare.Read)  ;
=> [SONARMSBRU-120] Add the FileShare.Read to the .Load command to allow multiple readers.

PackagingProjects/CSharpPluginPayload/CSharpPluginPayload.csproj, PackagingProjects/CSharpPluginPayload/RepackageCSharpPlugin.ps1, SonarQube.TeamBuild.Integration/SonarQube.TeamBuild.Integration.csproj, SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/SonarQube.MSBuild.Tasks.IntegrationTests.csproj
Also fixed miscellaneous build warnings
Building in VS2015 created a .jar file twice the size of the one created when building in VS2013 due to the inclusion of various TFS dlls. The packaging project was explicitly copying the files to be include into the zip to a specific folder. However, it was also specifying this folder as the output folder for the project. This meant that all of the project dependencies were being copied into the "zip" folder.
In VS2015, the TFS2013 assemblies are considered to be dependencies that need to be copied locally since they aren't part of the VS2015 distribution.
=> [SONARMSBRU-113] Fixed issue creating .jar file in VS2015

SonarQube.Bootstrapper/Program.cs, SonarQube.Common/ProcessRunner.cs, SonarQube.Common/ProcessRunnerArgs.cs, SonarQube.Common/SonarQube.Common.csproj, SonarQube.TeamBuild.Integration/CoverageReportConverter.cs, SonarRunner.Shim/SonarRunner.Wrapper.cs, Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/V0_9UpgradeMessageTests.cs
No changes in behaviour. All existing tests pass.
The ProcessRunner already has six arguments and three "Execute" overloads. Not logging all arguments to the command line (SONARMSBRU-126) will add a seventh parameter.
This code review of mainly for information and to clean up the code before fixing SONARMSBRU-126.
=> [Technical] Refactored to use a parameter object for the ProcessRunner

SonarQube.Bootstrapper/ArgumentProcessor.cs, SonarQube.Bootstrapper/BootstrapperSettings.cs, SonarQube.Bootstrapper/Interfaces/IBootstrapperSettings.cs, SonarQube.Common/ProcessRunner.cs, SonarQube.Common/ProcessRunnerArgs.cs, SonarQube.TeamBuild.Integration/CoverageReportConverter.cs, SonarRunner.Shim/SonarRunner.Wrapper.cs, Tests/SonarQube.Bootstrapper.Tests/ArgumentProcessorTests.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperExeTests.cs, Tests/SonarQube.Bootstrapper.Tests/BootstrapperSettingsTests.cs, Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs, Tests/TestUtilities/DummyExeHelper.cs
Previously the process runner expected a single string containing all of the child args, correctly quoted. 
The commit changes the process runner to accept a list of individual strings that it will quote as necessary. This makes it easier to centralise processing of command line arguments e.g. it will be much simpler to make the ProcessRunner filter out arguments that should not be logged such as passwords.
=> [Technical] Changed the process runner to expect child args as a list

SonarQube.Common/AnalysisConfig/AnalysisConfig.cs, SonarQube.Common/AnalysisConfig/AnalysisConfigExtensions.cs, SonarQube.Common/AnalysisConfig/ConfigSetting.cs, SonarQube.Common/AnalysisProperties/Property.cs, SonarQube.Common/ProjectInfo/ProjectInfo.cs, SonarQube.Common/ProjectInfo/ProjectInfoExtensions.cs, SonarQube.Common/SonarQube.Common.csproj, SonarQube.Common/VerbosityCalculator.cs, SonarQube.MSBuild.Tasks/IsTestFileByName.cs, SonarQube.MSBuild.Tasks/WriteProjectInfoFile.cs, SonarQube.TeamBuild.Integration/TeamBuildAnalysisSettings.cs, SonarQube.TeamBuild.PostProcessor/Program.cs, SonarQube.TeamBuild.PreProcessor/AnalysisConfigGenerator.cs, SonarRunner.Shim/PropertiesFileGenerator.cs, SonarRunner.Shim/PropertiesWriter.cs, Tests/SonarQube.Common.UnitTests/AnalysisConfigExtensionsTests.cs, Tests/SonarQube.Common.UnitTests/AnalysisConfigTests.cs, Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs, Tests/SonarQube.Common.UnitTests/SonarQube.Common.UnitTests.csproj, Tests/SonarQube.Common.UnitTests/VerbosityCalculatorTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/IsTestFileByNameTests.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/WriteProjectInfoFileTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/AnalysisConfigGeneratorTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs, Tests/SonarRunner.Shim.Tests/PropertiesFileGeneratorTests.cs, Tests/SonarRunner.Shim.Tests/PropertiesWriterTest.cs, Tests/TestUtilities/SQPropertiesFileReader.cs
This change separates out the properties which should be passed to the sonar-runner from other configuration settings.
sonar-runner settings are now only stored in AnalysisProperties. Other configuration settings (such as TFS Uri / Build Uri) are stored in ConfigSetting
=> [Technical] Changed settings storage

SonarQube.Common/Resources.Designer.cs, SonarQube.Common/Resources.resx, SonarQube.Common/Utilities.cs
I've tested this commit by locally reverting the fix for SONARMSBRU-125: https://github.com/SonarSource/sonar-msbuild-runner/commit/6bdad3317ef6fdf7aa30d9f8fcf21047e6f3a2e7
I now get the following messages in the logs - which seems definitely better:
```
11:41:30  Generating the FxCop ruleset: C:\Users\dinesh\Desktop\tmp\ConsoleApplication1\.sonarqube\conf\SonarQubeFxCop-cs.ruleset
11:41:30  Could not find a file on the SonarQube server. Url: http://localhost:9000/api/profiles/index?language=cs&name=Sonar#way
Process returned exit code 1
Pre-processing failed. Exit code: 1
```
This relates to:
* http://jira.sonarsource.com/browse/SONARMSBRU-91
* https://github.com/SonarSource/sonar-msbuild-runner/commit/10963e597189c98f921d6b6ebc329edb18586f3f
I think the log message was missing from the …
=> Do not silently ignore 404 errors

SonarQube.Common/ProcessRunnerArguments.cs, SonarQube.TeamBuild.PostProcessor/MSBuildPostProcessor.cs, SonarQube.TeamBuild.PostProcessor/Program.cs, SonarQube.TeamBuild.PostProcessor/Resources.Designer.cs, SonarQube.TeamBuild.PostProcessor/Resources.resx, Tests/SonarQube.TeamBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs
The post-processor wasn't reformatting the args from e.g "/d:x=y" to "-Dx=y"
=> [SONARMSBRU-127] Fixed error in passing args to sonar-runner

Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildAssertions.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, Tests/TestUtilities/ProjectDescriptor.cs
No product changes
This PR is mainly for info. The helper methods that create MSBuild projects on the fly for testing are numerous, untidy, and reasonably complicated. This commit is a minor cleanup that attempts to organise the methods better and remove some of the clutter.
I've deleted some redundant methods, made a couple of methods private that were public, and grouped methods by purpose.
=> [Technical] Tidied up test build utilities

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildAssertions.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/SonarQube.MSBuild.Tasks.IntegrationTests.csproj, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarQube.TeamBuild.Integration.Tests/TrxFileReaderTests.cs, Tests/TestUtilities/TestUtils.cs
The targets now look for a well-known ruleset name on disc and configures the Roslyn analysis based on whether the file exists or not.
Currently the Roslyn ruleset is separate from the FxCop ruleset. The build properties are set appropriately so the correct ruleset is used. However, it might be simpler to generate a single combined ruleset file and use that - I'll see how it works out in practice.
=> Update targets files to override Roslyn code analysis properties

SonarQube.MSBuild.Tasks/IsTestFileByName.cs, SonarQube.MSBuild.Tasks/MSBuildLoggerAdapter.cs, SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj
The IsTestFileByName MSBuild task directly implemented ILogger and mapped the logging methods to the equivalent MSBuild logging methods. I moved this code into a separate logging adapter class so it can be used by other MSBuild tasks.
I haven't added any direct tests for the new adapter class; it's tested indirectly by the task tests.
=> [Technical] Factor out logging adapter class

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildAssertions.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
This PR is based on the one of SONARMSBRU-178: https://github.com/SonarSource/sonar-msbuild-runner/pull/156
It adds one commit on top of it - you can visualize only the relevant diff by first going to "Commits" and then click on the 2nd commit.
=> SONARMSBRU-184 Pass the downloaded additional XML file to MSBuild for the Roslyn analyzers

SonarQube.MSBuild.Tasks/MergeRulesets.cs, SonarQube.MSBuild.Tasks/Resources.Designer.cs, SonarQube.MSBuild.Tasks/Resources.resx, SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/MergeRuleSetsTests.cs
Added unit tests
Changed MergeRulesets and the targets so that the merged ruleset is created as a new file, rather than updating the shared, generated ruleset.
The merged ruleset will be created in the existing "conf" directory with the name *SonarQubeRoslyn-cs.ruleset.[ProjectName].[fffff]*, where *[fffff]* is a partial timestamp to help guarantee uniqueness.
=> [SONARMSBRU-200] Merged ruleset is save to a new file

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildAssertions.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/WellKnownProjectProperties.cs, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
... for FxCop and Roslyn analysis
Updated tests
There is also a related StyleCop property *$(StyleCopTreatErrorsAsWarnings)*. However, we don't run StyleCop as part of the build (it's run by the StyleCop plugin in the sonar-runner) so there's no point in us setting that property in the targets file.
=> [SONARMSBRU-198] Amended targets so warnings are not treated as errors

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets, Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
Removed ruleset merging from the targets file. Fixed up tests.
Now, the SonarLint analyser will be the only one that is executed: any analysers that are configured in the project will be overwritten, and the generated ruleset will be the only rules that are executed.
I've left the MergeRulesets task and tests in place, but the task is not currently called from the targets file.
=> [SONARMSBRU-183] Remove ruleset merging from the targets file

SonarQube.TeamBuild.PreProcessor/Resources.Designer.cs, SonarQube.TeamBuild.PreProcessor/Resources.resx, SonarQube.TeamBuild.PreProcessor/Roslyn/CompilerAnalyzerConfig.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/AdditionalFile.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/Configuration.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/Deployment.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/NuGetPackageInfo.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/RoslynExportProfile.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs, SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj, Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynExportProfileTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
Added serialization model and tests to load the new XML profile format
Created a RoslynAnalyzerProvider (similar to the existing SonarLintAnalyzerProvider, which will be redundant once the RoslynAnalyzerProvider is finished). Currently the new provider fetches the profile and extracts the ruleset.
TODO: extract the analyser rule config files
TODO: amend the target files
Fetching the NuGet packages is part of [SONARMSBRU-205]
=> [SONARMSBRU-204] Added support for extracting ruleset from new Roslyn export XML

SonarQube.TeamBuild.PreProcessor/Roslyn/Model/Deployment.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/Model/Plugin.cs, SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj, Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynExportProfileTests.cs
The Roslyn profile exporter format has changed to include data about plugins.
This change updates the XML classes to load the new format.
=> [SONARMSBRU-212] Updated profile exporter XML to include plugin data

SonarQube.MSBuild.Tasks/GetAnalyzerSettings.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
Modified the build task to filter out non-assemblies.
[SFSRAP-31] is tracking deciding what files should be embedded in the jar.
=> [SONARMSBRU-216] Do not pass non-assemblies to Roslyn

SonarQube.MSBuild.Tasks/AttachBuildWrapper.cs, Tests/SonarQube.MSBuild.Tasks.UnitTests/AttachBuildWrapperTests.cs
There are 32- and 640bit versions of MSBuild, so the task needs to launch the appropriate monitor exe.
I haven't added any new tests but I've added run the tests under both 32- and 64-bit (as described in https://msdn.microsoft.com/en-us/library/ee782531.aspx) to check that the correct exe is being launched.
=> [SONARMSBRU-237] Changed task to launch 32/64bit monitor as appropriate

SonarQube.MSBuild.Tasks/AttachBuildWrapper.cs, SonarQube.MSBuild.Tasks/Resources.Designer.cs, SonarQube.MSBuild.Tasks/Resources.resx
Note: With the current timeout of 5 seconds, the `AttachBW_NotAttached_ExeThrows_TaskFails` test is flaky.
It fails both on my machine and on AppVeyor from time to time: It's expected 0 warnigns to be logged, but in case of a timeout there will be 1.
The warning is logged by `ProcessRunner`:
```
this.outputLogger.LogWarning(Resources.WARN_ExecutionTimedOut, runnerArgs.TimeoutInMilliseconds, runnerArgs.ExeName)
```
=> SONARMSBRU-239 Increase build-wrapper attach timeout to 60s

SonarQube.Bootstrapper/Program.cs, SonarQube.Common/ProcessRunnerArguments.cs, SonarQube.MSBuild.Tasks/AttachBuildWrapper.cs, SonarQube.TeamBuild.Integration/CoverageReportConverter.cs, SonarRunner.Shim/SonarRunner.Wrapper.cs, Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs, Tests/SonarQube.TeamBuild.PreProcessor.Tests/V0_9UpgradeMessageTests.cs
@bgavrilMS You'll probably enjoy this PR as well.
The parameters we pass to the sonar-scanner.bat are forwarded to Java using `%*`.
The problem is that batch is a kind of preprocessor, so it starts by rewritten the code to expand all `%variables`, and only then executes what has been rewritten, 1 instruction at a time.
This makes it easy to inject code in the batch script, and it's up to the caller to make sure nothing bad gets injected.
The only impact I could imagine is if a SonarQube's user or password contains special characters such as ` & echo hehe` or perhaps `" & echo hehe`. I didn't test if there was a real end-user problem here, this issue just happened to be spotted while learning about argument passing.
=> ProcRunner: Properly escape sonar-runner arguments

SonarQube.Common/Resources.Designer.cs, SonarQube.Common/Resources.resx, SonarQube.Common/Utilities.cs
Previously the scanner threw an unhandled exception when connecting to the server with incorrect credentials and crashed the application. This fix handles the exception with http unauthorized response and adds it to the logging instead.
=> Handle WebException on incorrect authentication.

SonarQube.Bootstrapper/BootstrapperClass.cs, SonarQube.Common/AnalysisException.cs, SonarQube.Common/SonarQube.Common.csproj, SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs, SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynRuleSetGenerator.cs
Currently, throwing exceptions will cause the process to fail with an "unhandled exception" which is very ugly. This is what is happening if a old VB plugin is installed in SonarQube (see SONARMSBRU-284).
The way to stop the scanner due to a well understood problem is to propagate a boolean flag all the way to the bootstrapper, which will log that the program failed and set a return code 1.
With this P/R I introduce a new, easier way to fail programs when the error is correctly handled: to throw a custom exceptions anywhere. The bootstrapper will catch this specific exception, log it, and return error code 1.
=> Improve error handling with exceptions

SonarQube.Bootstrapper/Program.cs
/h argument doesn't display the content of help information
=> call the ResumeOutput on ILogger to display the help information

SonarQube.TeamBuild.Integration/CoverageReportConverter.cs, SonarQube.TeamBuild.Integration/Interfaces/IVisualStudioSetupConfigurationFactory.cs, SonarQube.TeamBuild.Integration/Resources.Designer.cs, SonarQube.TeamBuild.Integration/Resources.resx, SonarQube.TeamBuild.Integration/SonarQube.TeamBuild.Integration.csproj, SonarQube.TeamBuild.Integration/VisualStudioSetupConfigurationFactory.cs, SonarQube.TeamBuild.Integration/packages.config
Leverages the VS setup configuration library for determining VS installation directory.
The existing registry method is still used to support installations prior to 15.
=> Added support for visual studio 15 code coverage tool

SonarQube.TeamBuild.Integration/CoverageReportConverter.cs, Tests/SonarQube.TeamBuild.Integration.Tests/CoverageReportConverterTests.cs, Tests/SonarQube.TeamBuild.Integration.Tests/SonarQube.TeamBuild.Integration.Tests.csproj, Tests/SonarQube.TeamBuild.Integration.Tests/packages.config, Tests/TestUtilities/TestLogger.cs
This PR fixes `CoverageReportConverter` not being able to locate `CodeCoverage.exe` when
only the Agents for Visual Studio 2017 are installed on the build agent. This patch also
searches for a package with the id `Microsoft.VisualStudio.TestTools.CodeCoverage.Msi`.
I noticed that this was also available on my Visual Studio Enterprise installation but I am
not sure if this is always available. That is why I am searching for both `Microsoft.VisualStudio.TestTools.CodeCoverage`
and `Microsoft.VisualStudio.TestTools.CodeCoverage.Msi`. This patch also removes a Debug.Assert
that checks if the executable exists because I added some unit tests for the 
`IVisualStudioSetupConfigurationFactory` implementation. The file that the factory returns does
not exist on disk and would raise an assert …
=> Fix locating CodeCoverage.exe for Agents for Visual Studio 2017 

SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Fixes SONARMSBRU-359: _Multi-platform builds only analyse one platform unless /t:rebuild is specified_
https://jira.sonarsource.com/browse/SONARMSBRU-359
=> Fix #359: don't clean project before every build

build/build.ps1, build/ci-runTests.ps1
Fixed ci build break introduced by my previous commit.
The build script calls "runTests" from inside multiple branches, so I've re-instated the old _runTests_ method and made it call out to the new script.
=> Fixed ci build script

its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
There is a ticket to fix the scanner to handle that case: https://jira.sonarsource.com/browse/SONARMSBRU-375
For now, just fixing the tests.
=> Fix ITs: use long paths in test, not DOS (8.3)

src/SonarQube.TeamBuild.Integration.Classic/SonarQube.TeamBuild.Integration.Classic.csproj
The Classic project is Net4.6 only so if a class is available in the .Net Framework then it should use the .NetFx version rather than referencing a NuGet package
=> Removed unnecessary NuGet refs from Classic project

src/SonarQube.Bootstrapper/Program.cs
Methods marked with [Conditional("DEBUG")] are still included in release binaries and so impact code coverage.
=> Changed [Conditional] block to #if DEBUG

src/SonarQube.TeamBuild.PreProcessor/Roslyn/PluginResourceCache.cs
This problem occured on one of the build machines:
`WaitHandleCannotBeOpenedException: A WaitHandle with system-wide name 'Global\90CD3CFF-A12C-4013-A44A-199B8C26818B' cannot be created. A WaitHandle of a different type might have the same name`
This is because we use `Mutex` with the same name as `WaitHandle` used before.
=> Fix potential WaitHandleCannotBeOpenedException

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildLogAssertions.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildRunner.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/MSBuildLocator.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/SimpleXmlLogger.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/SonarScanner.MSBuild.Tasks.IntegrationTests.csproj, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/ImportBeforeTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/packages.config, tests/SonarScanner.MSBuild.Tasks.Integrationtests/MSBuildExecution/BuildLog.cs
Previously the tests hosted the build engine in-memory. However, the tests have been broken several times as new VS updates are released, so this commit changes the tests to execute the build by shelling out to the msbuild.exe process.
When the build engine was hosted in-memory it was easy to check the outcome of the build (e.g. expected targets executed in a particular order). It's more complicated when the build is run out of process: we supply a custom logger that is used during the build that records the task/target execution in an XML file. The tests can then re-load the XML log file and assert against that.
TODO: so far I have only changed the tests that were failing locally. If the tests pass on CIX with this change then I'll modify the remaining tests.
=> Converted failing MSBuild integration tests to execute msbuild.exe

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildAssertions.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildLogAssertions.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildRunner.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/SimpleXmlLogger.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, tests/SonarScanner.MSBuild.Tasks.Integrationtests/MSBuildExecution/BuildLog.cs
Removed redundant methods from _BuildUtilities_ and _BuildAssertions_.
All of the integration tests that run builds now use _msbuild.exe_ rather than executing the build engine in-memory.
There are still some tests in _ImportBeforeTargetsTests_ and _SonarIntegrationTargetsTests_ use the MSBuild API to evaluation properties (i.e. checking that MSBuild is processing conditional properties as expected).
=> Changed RoslynTargetsTests to use msbuild.exe

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
This is to fix tests.
`E2E_NoContentOrManagedFiles` test fails when `AdditionalFiles` item group is one of the item groups we handle. This is because we add one the file during analysis (IIRC FilesToAnalyze.txt). We could adjust the test, but I think it's not worth analyzing `AdditionalFiles` type (and if users want, they could with the new property added in the other PR).
I'll update doc with list of supported item groups after the merge.
=> Remove 'AdditionalFiles' from analyzed ItemGroup types

Tests/SonarScanner.MSBuild.Common.UnitTests/AnalysisConfig/AnalysisConfigExtensionsTests.cs, Tests/SonarScanner.MSBuild.Common.UnitTests/EnvScannerPropertiesProviderTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/AnalysisConfigGeneratorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/Infrastructure/PreprocessTestUtils.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/EnvScannerPropertiesProvider.cs
The Sonar VSTS tasks set the SONARQUBE_SCANNER_PARAMS environment variable, which caused some of the tests to behave differently or fail.
The affected tests have been modified so that they are not affected by, and do not in turn affect, the VSTS build environment.
=> Fixed tests affected by VSTS task environment variable

Tests/TestUtilities/SQPropertiesFileReader.cs
Fixes the remaining VSTS test failures.
Seven of the tests were using this class to check the contents of the setting file, then calling _testContext.AddResultFile(...)_. The call to _AddResultFile_ was failing because this class was still holding a lock on the file.
=> Fix test file locking issue

its/projects/ConsoleMultiLanguage/ConsoleCSharp/ConsoleCSharp.csproj, its/projects/ExcludedTest/Excluded/Excluded.csproj, its/projects/ExcludedTest/Normal/Normal.csproj, its/projects/ProjectUnderTest/ProjectUnderTest/CSProj1.csproj, its/projects/ProjectUnderTest/ProjectUnderTest/Foo.cs, its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
So the QA is now failing because of some change of behaviors on the latest SonarC# (used by the scanner for msbuild ITs).
=> Update ITs to match latest release of SonarC# results

docs/SonarQube.Analysis.xml
Created a docs folder and moved a copy of the sample _SonarQube.Analysis.config_ file into it.
This was prompted by an issue [VSTS-159](https://jira.sonarsource.com/browse/VSTS-159): the help link in the VSTS task should be pointing to a redirect url, but also it would be better if the sample config files for this repo were in a more stable location.
=> Added sample settings file to docs folder

its/pom.xml, its/src/test/java/com/sonar/it/scanner/msbuild/CppTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/SQLServerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java, its/src/test/java/com/sonar/it/scanner/msbuild/VBNetTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/VstsUtils.java
The Scanner for MSBuild detects when it is being run in a VSTS build and behaves differently (e.g. uses VSTS environment variables to configure settings). This broke some of the ITs.
=> Fix up ITs to run under VSTS

Tests/SonarScanner.MSBuild.Common.UnitTests/AnalysisConfig/AnalysisConfigExtensionsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildLogAssertions.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs, Tests/TestUtilities/RulesetAssertions.cs, src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfigExtensions.cs, src/SonarScanner.MSBuild.Common/AnalysisConfig/Include.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs, src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs, src/SonarScanner.MSBuild.Tasks/Resources.resx, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
This commit adds and tests the switching logic in the existing _GetAnalyzerSettings_ custom MSBuild task to decide whether to overwrite all of the Roslyn analyzer configuration in the project (the legacy behaviour) or to merge it.
TODO: new merge behaviour is not implemented
Part 1 of #561
=> Added merge/overwrite switch logic to GetAnalyzerSettings task

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/SimpleXmlLogger.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs, src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs, src/SonarScanner.MSBuild.Tasks/Resources.resx, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets, tests/SonarScanner.MSBuild.Tasks.Integrationtests/MSBuildExecution/BuildLog.cs
The interaction between the targets file and _GetAnalyzerSettings_ custom task was more complicated than necessary so I decided to simplify it before making the next set of changes related to the supporting external analyzers.
I also improved the logging in the test framework to make diagnosing test failures easier.
=> Simplify the GetAnalyzerSettings task

Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
Both the product code and tests where using the wrong value (7.5). Should have been 7.4.
See https://github.com/SonarSource/sonar-scanner-msbuild/issues/561
=> Fix minimum SQ version

Tests/SonarScanner.MSBuild.Tests/BootstrapperClassTests.cs, src/SonarScanner.MSBuild/BootstrapperClass.cs, src/SonarScanner.MSBuild/Resources.Designer.cs, src/SonarScanner.MSBuild/Resources.resx
Fix #535 
The idea is to try to delete as many folders/files as possible inside the `.sonarqube` folder. When reaching the copy dll step, we will compare versions and skip if they are the same of fail with a better message if they are different.
=> Reduce errors linked to locked dlls

Tests/SonarScanner.MSBuild.Shim.Tests/MockProcessRunner.cs, Tests/SonarScanner.MSBuild.Shim.Tests/SonarScanner.MSBuild.Shim.Tests.csproj, Tests/SonarScanner.MSBuild.Shim.Tests/SonarScannerWrapperTests.cs, src/SonarScanner.MSBuild.Common/Interfaces/IProcessRunner.cs, src/SonarScanner.MSBuild.Common/ProcessRunner.cs, src/SonarScanner.MSBuild.Shim/Resources.Designer.cs, src/SonarScanner.MSBuild.Shim/Resources.resx, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
Fix #656 
I suggest reviewing the commits separately. The first is a refactoring of the existing tests so they don't execute a batch file as part of the test.
The second commit is the actual fix, and is much simpler.
=> Don't set the JVM memory size by default

Tests/SonarScanner.MSBuild.Common.UnitTests/MsBuildPathSettingsTests.cs, src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
Fixed #681 
There are two commits. I'd suggest looking at them separately.
The first just fixes a bug in the tests - no product changes.
The second is the fix, which is very simple - just don't try to create the folders. The target installer will do it later.
I've tested this fix on a hosted VSTS Ubuntu agent, and it now works correctly.
=> [Do not squash] Fixed target installation error on Linux

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/ImportBeforeTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarIntegrationTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs
No product code changes
Changed most of the remaining targets tests to create MSBuild projects by substituting values into XML templates, rather than constructing projects using the MSBuild APIs.
Still to do: change the _E2EAnalysisTests_.
=> Refactor MSBuild tests to use XML for project creation

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs, Tests/TestUtilities/ProjectInfoAssertions.cs
With this change, none of the tests use the MSBuild APIs to create project files
=> Refactor E2EAnalysisTests MSBuild tests to use XML for project creation

src/Packaging/Packaging.csproj
There are two commits:
* the first adds a check that the zip file header is correct. This check passes against the zip file created with PowerShell.
* the second replaces PowerShell with an inline task that does the same thing. The new file header check still passes.
=> Replaced powershell in packaging with inline tasks

Tests/SonarScanner.MSBuild.TFS.Tests/BuildVNextCoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Tests/BuildVNextCoverageSearchFallbackTests.cs, Tests/SonarScanner.MSBuild.TFS.Tests/Infrastructure/MockBuildSettings.cs, Tests/SonarScanner.MSBuild.TFS.Tests/Infrastructure/MockSearchFallback.cs, Tests/SonarScanner.MSBuild.TFS.Tests/SonarScanner.MSBuild.TFS.Tests.csproj, src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs, src/SonarScanner.MSBuild.TFS/IBuildVNextCoverageSearchFallback.cs, src/SonarScanner.MSBuild.TFS/Properties/InternalsVisibleTo.cs
=> Workaround for VSTS-179: added fallback search for coverage files

Tests/SonarScanner.MSBuild.TFS.Tests/BuildVNextCoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Tests/Infrastructure/MockReportConverter.cs, src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs, src/SonarScanner.MSBuild.TFS/Resources.Designer.cs, src/SonarScanner.MSBuild.TFS/Resources.resx
New - Behavior of the CoverageReport conversion method has slightly changed : now if we detect an existing .coveragexml file beside the coverage file, the method won't fail and the file will be added to the coverage report list at the end. If the converrsion failed itself (so no coveragexml file found, and trying to convert a provided coverage file), then the method will fail, as before.
A unit test has been modified according to that change.
=> Resolves #735

Tests/SonarScanner.MSBuild.TFS.Tests/BuildVNextCoverageReportProcessorTests.cs, src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs
As per the documentation (https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS) we ask users to provide the property sonar.cs.vscoveragexml.reportsPaths set if they want code coverage to be uploaded to SonarCloud. Thus, with the previous fix, the scanner won't try to convert any coverage file if this setting is present, which can broke existing builds for users.
=> Fix - Reverted setting / TryConvertCoverageReports bloc to avoid regression

its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
Environment variable was already taken in account while checking for … msbuild path. Just clarified the error message to provide the full msbuild path with the exe in that environment variable.
fixes #767
=> Clarify error message for not found MSBuild path

its/pom.xml
fixes #780 
Looks like the only depreciation that we have after the upgrade is the .setComponentKey(componentKey) in the new ComponentWsRequest() class (sonar-ws), but haven't find any alternative yet.
=> Upgrade orchestrator to v3.27.0.2172

azure-pipelines.yml, nuspec/chocolatey/chocolateyInstall-netcoreapp3.0.ps1, nuspec/chocolatey/sonarscanner-msbuild-netcoreapp3.0.nuspec, pom.xml, src/DotnetVersions.props, src/Packaging/Packaging.csproj
fixes #808 
In the process of packaging upcoming 4.8.0, package names were incorrect for some of them in the artifact. This has been correct. 
I took the benefit of this PR for adding .NET Core 3 package to Chocolatey as well, which was not provided nor packaged with the previous .NET Core 3 PR.
=> Fix packages generation and names + Added .NET Core 3 package for Chocolatey

src/Packaging/Packaging.csproj
The symantec server has been replaced.
See https://knowledge.digicert.com/alerts/migration-of-legacy-verisign-and-symantec-time-stamping-services.html
=> Update the timestamp server used for signing

Tests/SonarScanner.MSBuild.TFS.Tests/BuildVNextCoverageSearchFallbackTests.cs, src/SonarScanner.MSBuild.TFS/IBuildVNextCoverageSearchFallback.cs
Changing the way duplicate .coverage files are discovered as explained in #848 
Need to verify whether the possible performance impact is acceptable before merging.
=> Dedupe coverage files on file content

nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
[NuGet description](https://www.nuget.org/packages/dotnet-sonarscanner) for .NET Core mentions explicitly `.NET Core 2.1` only. The NuGet looks obsolete nowadays with .NET Core 3.1 out and .NET 5 on it's way.
I'm not very sure how it should be updated. Here's initial kickoff.
=> Update NuGet description for .NET Core

Tests/SonarScanner.MSBuild.PreProcessor.Tests/SonarWebServiceTest.cs, src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
=> Changed deprecated projectKey parameters while fetching Quality Profile

Tests/SonarScanner.MSBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs, Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/WriteProjectInfoFileTests.cs, Tests/TestUtilities/TestUtils.cs, azure-pipelines.yml, src/SonarScanner.MSBuild.PostProcessor/MSBuildPostProcessor.cs, src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs, src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs, src/SonarScanner.MSBuild.Tasks/Resources.resx, src/SonarScanner.MSBuild.Tasks/WriteProjectInfoFile.cs
fixes #659
When no ProjectGuid has been found in whether the csproj or the solution, then we generate a random one. 
Further improvement, which will not be in the scope of this PR, is to ensure that a shared lib is analyzed only once. This is not currently the case since each "dotnet build" on a csproj that has this shared lib will create a directory for it.
=> Add support for pure .NET Core Projects

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Related to #959 
Move FilesToAnalyze.txt to `conf/0` directory, as it will be need by the new XML file `conf/0/SonarProjectConfig.xml`
Save the file directly after generating the list. The new Target will depend on it and execute it before the build.
If somebody would have a target that depends on `CalculateSonarQubeFilesToAnalyze` and executes before `WriteSonarQubeProjectData` target that would update our `SonarQubeAnalysisFiles` list, this would break such unsupported scenario as users looses the point to inject in. 
This is not a concern, as confirmed by @duncanp-sonar:
>Hi Pavel. The S4MSB targets files were not designed to be publicly extensible in the sense that users can rely on the order in which our targets fire, or even that specific targets exists. So we should feel free to …
=> Move FilesToAnalyze to CONF directory and write it immediately

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RazorTargetTests.cs, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
When `SonarQubeExclude` is true, we reset `ErrorLog` property. We should do the same for the Razor one at the same time to avoid Razor-only reports.
=> Targets: Clear RazorCompilationErrorLog when ErrorLog is cleared.

Tests/SonarScanner.MSBuild.PreProcessor.Tests/DataModel/QualityProfile.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/DataModel/ServerDataModel.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/Infrastructure/MockRoslynAnalyzerProvider.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServer.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/PreProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynRuleSetGeneratorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Tests/SonarWebServiceTest.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/IAnalyzerProvider.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarQubeServer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx, src/SonarScanner.MSBuild.PreProcessor/Roslyn/ActiveRule.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynRuleSetGenerator.cs, src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs, src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
This is preparation for #980
Old state:
* Load active rules.
* Load inactive rules (second request to the server API).
* Propagate two sets of rules
* Merge the lists and process it.
New state:
* Load all rules. 
* Propagate single set.
* Process it.
=> Load all rules from QP at once

azure-pipelines-external.yml, azure-pipelines.yml
It's difficult to read the CI check in GitHub
Before: (see checks on any previous PR)
```
SonarScanner for MSBuild
SonarScanner for MSBuild (Build, UT, analyze on SonarCloud and stage to repox Build, UT, analyze on SonarCloud and stage to repox)
SonarScanner for MSBuild (Build, UT, analyze on SonarCloud and stage to repox Compute variables needed in the Burgr payload)
SonarScanner for MSBuild (Build, UT, analyze on SonarCloud and stage to repox Notify Burgr of the start of the job)
SonarScanner for MSBuild (Build, UT, analyze on SonarCloud and stage to repox Notify Burgr of the success of the job)
SonarScanner for MSBuild (Promote artifacts on repox and notify Burgr Promote artifact on repox and notify Burgr)
SonarScanner for MSBuild (Promote artifacts on repox and notify Burgr …
```
=> Rename CI stages

Tests/SonarScanner.MSBuild.Common.UnitTests/SonarProductTests.cs, Tests/SonarScanner.MSBuild.Common.UnitTests/SonarScanner.MSBuild.Common.UnitTests.csproj, Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs, its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java, src/SonarScanner.MSBuild.Common/SonarProduct.cs, src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
Related to #980
Do not analyze test code for SQ<=8.8 to avoid performance regression. 
Old SQ can be used with latest Scanner.
Old SQ will ignore issues raised on a test code.
This is a draft, rebase will be needed once #986 is merged. First `Squash AnalyzeTest` commit doesn't need a review for the same reason.
=> Do not analyze test code for SQ<=8.8

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
Fixes issue found here https://github.com/SonarSource/sonar-scanner-msbuild/pull/989#discussion_r608510247
`ignoreIssues` should default to `false` according to [docs](https://docs.sonarqube.org/latest/analysis/external-issues/)
It was working before, because server provides the value explicitly.
=> Fix sonar.{langauge}.roslyn.ignoreIssues default value

Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarQubeCategoriseProjectTests.cs, Tests/SonarScanner.MSBuild.Tasks.UnitTests/IsTestByReferenceTests.cs, src/SonarScanner.MSBuild.Tasks/IsTestByReference.cs, src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
I saw this issue when playing with our integration tests. We need to parse `@(AssebmlyName)` format as well in the `IsTestByReference` task.
```
Using "IsTestByReference" task from assembly "C:\Projects\sonar-dotnet\analyzers\its\sources\Nancy\src\.sonarqube\bin\SonarScanner.MSBuild.Tasks.dll".
Task "IsTestByReference" (TaskId:35)
Task Parameter:
References=
@(Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
@(mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
@(System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
@(System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
@(System.Configuration, Version=4.0.0.0, Culture=neutral, …
```
=> Fix assembly name parsing in IsTestByReference

Tests/SonarScanner.MSBuild.PreProcessor.Tests/WebClientDownloaderTest.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs, src/SonarScanner.MSBuild/SonarScanner.MSBuild.csproj
Today the current version is developed to allow ClientCert without password, for the "begin" operation it works good. But for the "end" operation, java required that the clientcert be with a password defined. 
This is why in the current version we have to user two client certs, one (with no pw) for "begin" and another (with pw) for "end". This PR will allow to use only one clientcert with pw, for both operations and simplify the usage of mTLS.
=> mTLS with ClientCert Password

Tests/SonarScanner.MSBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs, Tests/SonarScanner.MSBuild.PostProcessor.Tests/SonarScanner.MSBuild.PostProcessor.Tests.csproj, Tests/SonarScanner.MSBuild.PostProcessor.Tests/TargetsUninstallerTests.cs, src/SonarScanner.MSBuild.PostProcessor/Interfaces/ITargetsUninstaller.cs, src/SonarScanner.MSBuild.PostProcessor/MSBuildPostProcessor.cs, src/SonarScanner.MSBuild.PostProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PostProcessor/Resources.resx, src/SonarScanner.MSBuild.PostProcessor/TargetsUninstaller.cs, src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
Fixes #964
Most of the code is a revert of #945 that removed the uninstallation. 
Main changes:
- `TargetsUninstaller` receives `binDirectory` argument
- `TargetsUninstaller` doesn't delete from `MsBuild` folders
- Added tests for `TargetsUninstallerTests`
- Refactored `MSBuildPostProcessorTests.PostProcTestContext.VerifyTargetsUninstaller` because it was validating `invoked not more than once` but didn't validated `invoked at least once`.
=> Improve uninstall of targets if multiple builds in the same pipeline

Tests/LogArgs/LogArgs.csproj, Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj, Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj, Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj, Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj, Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs, Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj, Tests/TestUtilities/TestUtilities.csproj
Fixes #1155 
Unblocks master, should bring coverage back to normal.
I ignored the tests which started failing locally after this change - #1165 to bring them back.
=> Change test projects TFM to `net48` instead of `net5.0` to fix ccov

its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
Related to #1122
Another approach would be to disable reusing `msbuild` nodes as suggested here: https://github.com/SonarSource/sonar-scanner-msbuild/issues/1122#issuecomment-981351976
=> Add retry mechanism, re-enable IT

its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
Fixes #1122
Should monitor builds and revert #1183 is `nodeReuse:false` fixes the timeouts.
=> Use MSB argument nodeReuse:false in ITs

Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj, Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj, Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj, Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj, Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj, azure-pipelines.yml
Coverlet will add better branch support but this will result in a lower overall coverage since more paths are now considered.
Coverage after the merge will drop to 84.5% from 92.3%.
=> Use coverlet instead of Visual Studio coverage

its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
Related to the following changes: https://github.com/SonarSource/re-ci-images/pull/79
See the tested behavior also on: https://github.com/SonarSource/sonar-scanner-msbuild/pull/1231
Why it worked earlier and not anymore? Explanation:
- With .NET 6, the.NET 6.0.100 SDK can be used in version 16.11 for downlevel targeting. This means that you're not forced to update your SDK and Visual Studio versions simultaneously. However, you won't be able to target .NET 6 because of limitations in 6.0 features and C# 10 features in version 16.11. This compatibility is specifically for targeting 5.0 and below.
- 6.0.300 and newer SDKs require a minimum Visual Studio version of 17.0
See at https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs
=> Do not run Net6 razor ITs for MsBuild16 setUp

Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
All in-memory project loading UTs were already redesigned in #1077
=> Remove unused package references from UTs

Tests/SonarScanner.MSBuild.Common.Test/AnalysisConfig/AnalysisConfigExtensionsTests.cs, Tests/SonarScanner.MSBuild.Common.Test/EnvScannerPropertiesProviderTest.cs, Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/Classic/TfsLegacyCoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/CoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/Infrastructure/MockCodeCoverageProcessor.cs, Tests/SonarScanner.MSBuild.TFS.Test/Infrastructure/MockSummaryReportBuilder.cs, Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs, its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java, src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfigExtensions.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/EnvScannerPropertiesProvider.cs, src/SonarScanner.MSBuild.Common/Resources.Designer.cs, src/SonarScanner.MSBuild.Common/Resources.resx, src/SonarScanner.MSBuild.PostProcessor/MSBuildPostProcessor.cs, src/SonarScanner.MSBuild.Shim/AnalysisConfigExtensions.cs, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs, src/SonarScanner.MSBuild.TFS.Classic/Program.cs, src/SonarScanner.MSBuild.TFS/CoverageReportProcessor.cs, src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs, src/SonarScanner.MSBuild.TFS/Interfaces/ICoverageReportProcessor.cs, src/SonarScanner.MSBuild.TFS/Interfaces/ISummaryReportBuilder.cs, src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs, src/SonarScanner.MSBuild.Tasks/IsTestFileByName.cs
=> Add logging when environment variable parsing fails

Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs, Tests/TestUtilities/TestUtils.cs, src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
=> Do not log warnings about files placed outside the project root directory that are binary or placed in the standard NuGet cache.

Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs, scripts/package-artifacts.ps1, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
This reverts commit 5a8101711d455fe2165c40a95ba4d3f6c8b7bc33.
Community issues:
- https://community.sonarsource.com/t/calling-the-sonarscanner-cli-unhandled-exception/65104
- https://community.sonarsource.com/t/sonarqube-analysis-fails-with-error-code-134/65098
=> Revert fix for "SonarScanner.MSBuild.dll should not require manual CHMOD"

Tests/SonarScanner.MSBuild.Shim.Test/ProjectInfoExtensionsTests.cs, src/SonarScanner.MSBuild.Shim/ProjectInfoExtensions.cs, src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
`FixEncoding` makes the New Code Period look bad.
Even if it was just slightly refactored in [this commit](https://github.com/SonarSource/sonar-scanner-msbuild/pull/1306/files#diff-f79831385eb9ec0eb0115604abf180c8e806ae8d03a220ca778d52d0aa915fbfR412), we need to **clean as we code** 🥷 .
As usual, it's better to review commit by commit.
=> Add UTs for FixEncoding

azure-pipelines.yml
Fixes #1324
Tested in https://github.com/SonarSource/sonar-scanner-msbuild/pull/1322
> Failed!  - Failed:     1, Passed:   212, Skipped:     0, Total:   213, Duration: 4 s - SonarScanner.MSBuild.Common.Test.dll (net48)
ERROR: Unit tests for 'Tests\SonarScanner.MSBuild.Common.Test\SonarScanner.MSBuild.Common.Test.csproj' FAILED.
=> Fail CI if unit tests fail

azure-pipelines.yml
This fixes at least the red vs2022_dev ITs. 
It is a necessary change because of the VM image update.
=> Set MsBuild path to the one in VS 2022 community version

azure-pipelines.yml
`dotnet test`
[Breaking changes in options](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test#options):
Starting in .NET 7: switch -a to alias --arch instead of --test-adapter-path
Starting in .NET 7: switch -r to alias --runtime instead of --results-dir
=> Fix CI after .NET 7 breaking changes

Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, Tests/SonarScanner.MSBuild.Test/AnalysisWarning/NetFrameworkBootstrapperClassTests.cs, Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs, Tests/SonarScanner.MSBuild.Test/DefaultProcessorFactoryTests.cs, src/SonarScanner.MSBuild.PostProcessor/Interfaces/IPostProcessor.cs, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild/DefaultProcessorFactory.cs, src/SonarScanner.MSBuild/Interfaces/IProcessorFactory.cs
Names were messy and hard to navigate.
`TeamBuildPreProcessor` was tested in `PreProcessorTests` and had a counterpart of `MSBuildPostProcessor`
I'm intentionally not fixing the codesmells or coverage. We'll need few PRs for the new code period before release on that
=> Align PreProcessor and PostProcessor names

Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/Properties/InternalsVisibleTo.cs
Fixes #1369 
It works with this Java counterpart:
```java
@Test
public void fixme() throws Throwable {
assertThat(contentHash("EmptyWithBom.cs")).isEqualTo("f1945cd6c19e56b3c1c78943ef5ec18116907a4ca1efc40a57d48ab1db7adfc5");
assertThat(contentHash("EmptyNoBom.cs")).isEqualTo("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
assertThat(contentHash("CodeWithBom.cs")).isEqualTo("b98aaf2ce5a3f9cdf8ab785563951f2309d577baa6351098f78908300fdc610a");
assertThat(contentHash("CodeNoBom.cs")).isEqualTo("8c7535a8e3679bf8cc241b5749cef5fc38243401556f2b7869495c7b48ee4980");
assertThat(contentHash("Utf8.cs")).isEqualTo("13aa54e315a806270810f3a91501f980a095a2ef1bcc53167d4c750a1b78684d");
assertThat(contentHash("Utf16.cs")).isEqualTo("a9b3c4402770855d090ba4b49adeb5ad601cb3bbd6de18495302f4 …
```
=> Incremental PR analysis: Implement the hashing

Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs, src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs
Prerequisite for #1387 
Cache contains `byte[]` so it doesn't make sense to serialize it to string for comparison
=> Change CacheProcessor.ContentHash signature

Tests/SonarScanner.MSBuild.TFS.Test/Classic/BinaryToXmlCoverageReportConverterTests.cs, src/SonarScanner.MSBuild.TFS.Classic/BinaryToXmlCoverageReportConverter.cs, src/SonarScanner.MSBuild.TFS.Classic/Resources.Designer.cs, src/SonarScanner.MSBuild.TFS.Classic/Resources.resx
=> VsTestToolsInstallerInstalledToolLocation: Path to CodeCoverage.exe may contain net462 instead of net451

src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
Related to #1377 
The goal of this PR is strictly to use the Uri. There are plenty of things that can be cleaned up and refactored on this class but we need to take them one by one.
=> Refactor SonarWebService to use Uri

Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs, Tests/SonarScanner.MSBuild.PostProcessor.Test/Infrastructure/MockBuildSettings.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs, Tests/SonarScanner.MSBuild.TFS.Test/Infrastructure/MockBuildSettings.cs, src/SonarScanner.MSBuild.Common/Interfaces/IBuildSettings.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
Prerequisite for #1387 
The key inside the cache needs to be a relative path. 
We need to compute a common base path for S4NET and Java plugin. This value must be computed during `begin` step and passed along to the Scanner CLI.
In the best case scenario, we would use result of [ComputeProjectBaseDir](https://github.com/SonarSource/sonar-scanner-msbuild/blob/92ff75959987f61890032eda123fd4f689bf6561/src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs#L224), but that one is computed during `end` step from data collected during the build - too late. We need path that is available during `begin` step.
=> Incremental PR analysis: Produce deterministic base path

scripts/package-artifacts.ps1
Follow up of #1384
Prerequisite for #1398
CI run without these changes failed: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=57479&view=results
CI run with these changes worked: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=57501&view=results
=> Add Google.Protobuf to packaging

Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarQubeServer.cs, src/SonarScanner.MSBuild.Common/Utilities.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarQubeServer.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
Issue from ITs:
```
16:17:43.319  Processing analysis cache
16:17:43.319  Processing pull request with base branch 'base-branch'.
16:17:43.32  Downloading cache. Project key: incremental-pr-analysis, branch: base-branch.
16:17:43.321  Downloading from http://127.0.0.1:59878/api/analysis_cache/get?project=incremental-pr-analysis&branch=base-branch...
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
at System.Net.Http.HttpClient.CheckDisposed()
at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.GetAsync(Uri requestUri, …
```
=> Fix SonarWebService disposing

azure-pipelines.yml, its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
Currently the tests are run only on `7.9`, `8.9` and `DEV` but the latest release is also supported.
=> Run the integration tests also on the latest release

Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs, src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs
=> Incremental PR Analysis: Validate cache keys

azure-pipelines.yml, its/src/test/java/com/sonar/it/scanner/SonarScannerTestSuite.java
The latest release of sonar-dotnet is failing the build on older versions of SonarQube (<9.4) because it doesn't check the caching API is available before using it.
I think it's preferable to validate against the DEV version (of sonar-dotnet) to find possible compatibility issues before releasing  sonar-dotnet analyzers.
=> Use the dev version of sonar-dotnet (and fix the build)

its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
SonarQube changed their web API and the build is failing. This will fix the build until the situation is clarified.
Related to: #1454
=> Ignore Incremental PR analysis test

.github/workflows/release.yml
* Use jfrog-setup-wrapper instead, that way the credentials are retrieved automatically from Vault and no longer Github
Fixes [BUILD-2292](https://sonarsource.atlassian.net/browse/BUILD-2292)
[BUILD-2292]: https://sonarsource.atlassian.net/browse/BUILD-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-2292 Use Vault

azure-pipelines.yml, scripts/Mend/Mend-Scan.ps1
The pipeline is failing due to the way the mend jar verification is happening.
For more info see https://sonarsource.atlassian.net/browse/BUILD-2478.
For this PR I followed the same pattern with SC: https://github.com/SonarSource/sonarcloud-core/pull/4775/files
To see how mend run step will look like on master: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=61727&view=results
=> Verify Mend jar signature with SHA256 hash instead of checking for certificate pattern.

its/src/test/java/com/sonar/it/scanner/msbuild/others/OthersTestSuite.java, its/src/test/java/com/sonar/it/scanner/msbuild/others/RuntimeConfigTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SonarQubeTestSuite.java
The test will not run yet on the CI. I've added an issue for the update: https://github.com/SonarSource/sonar-scanner-msbuild/issues/1477
=> Make RuntimeConfigTest part of a test suite

Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockIDownloaderHelper.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarWebService.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServiceTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServiceTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarWebService.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/WebService/SonarCloudWebService.cs, src/SonarScanner.MSBuild.PreProcessor/WebService/SonarQubeWebService.cs, src/SonarScanner.MSBuild.PreProcessor/WebService/SonarWebService.cs
Fixes #1476 
- Add `organization` field to the class `SonarWebService`
- Update unit test accordingly
- Removed duplicates
- Refactor existing ones
=> Refactoring: organization field cleanup in SonarWebService

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- sonar.token was introduced by SonarQube team but is not yet supported by the scanner
=> Fix build: update expected warnings

Tests/SonarScanner.MSBuild.Test/ArgumentProcessorTests.cs, src/SonarScanner.MSBuild.Common/CommandLine/CommandLineFlagPrefix.cs, src/SonarScanner.MSBuild/ArgumentProcessor.cs
=> When no parameter is given, the S4NET prints the help message

Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/TestDownloader.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServerTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs, Tests/TestUtilities/TempFile.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/IDownloader.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs, src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarQubeWebServer.cs, src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarWebServer.cs
Fixes #1484
As part of #1484, now relying on relative URL path only:
- Base URL set in the `HttpClient.BaseAddress`
- `IDownloader` using string only for handling relative path.
=> Refactoring: Use of HttpClient.BaseAddress property

Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
- If a wrong URL is used (that is up and returns NotFound), the scanner was terminating without logging anything.
- If the server certificate was not valid, a wrong message was logged.
=> Display a message if the version cannot be parsed

src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalyzerSettings.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
After running an analysis with MSBuild17, I actually realized that the comment is not correct.
It states that the OriginalRulesetFilePath will never be null when the user does not provide a ruleset.
It actually is null, so not to create any confusion I am removing the comment.
=> Remove out of date comment about OriginalRulesetFilePath

azure-pipelines.yml
=> fix(BUILD-3172): pin CycloneDX version to 2.7.0

azure-pipelines.yml
=> Pin sonar-dotnet to 9.7 in old SQ ITs

.editorconfig
see explanation in https://github.com/SonarSource/sonar-scanner-msbuild/pull/1688#issue-1890326418
=> Ignore CS7035 in .editorconfig

azure-pipelines.yml, scripts/variables.ps1, sonar-docs/analysis/scan/sonarscanner-for-msbuild.md, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
This reverts commit a4cdc9239598edf20ea79f26a267ee02bcc93106.
We decided to not drop yet the support for Java 11.
=> Revert "Bump scanner cli to 5.0.1.3006 (#1699)"

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
This reverts commit 5acb0824c0210b9205a0b48fc955d2f41f33f4f4.
We decided not to drop support for Java 11
=> Revert "Bump version to 6.0.0 (#1700)"

azure-pipelines.yml
The current code signing certificate has expired. Until the new one is set up this PR will disable code signing to keep the builds green.
=> Temporarily disable code signing

its/pom.xml
After the latest parent plugin update, the ITs were detecting 0 tests and the run was successful.
This PR rolls back that change.
=> Revert parent pom to 68.0.0.247 to ensure the ITs run

Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/EmbeddedAnalyzerInstallerTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockAnalyzerInstaller.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockRoslynAnalyzerProvider.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/EmbeddedAnalyzerInstaller.cs
Fixes #1638
This should in theory allow the user to specify a temporary directory that will be used by the analyser for it's dll cache.
=> Add option to specify temporary working directory

Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, scripts/package-artifacts.ps1, src/DotnetVersions.props, src/SonarScanner.MSBuild.Common/SingleGlobalInstanceMutex.cs, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.Shim/RuntimeInformationWrapper.cs, src/SonarScanner.MSBuild/Program.cs
This change is temporary to allow us to progress on the sprint. We will have to update the packaging to reflect PMs decision.
Upgrade to Net 462 as it is needed for the https://www.nuget.org/packages/Microsoft.CodeCoverage.IO package.
See also [MMF-2777](https://sonarsource.atlassian.net/browse/MMF-2777)
[MMF-2777]: https://sonarsource.atlassian.net/browse/MMF-2777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Part of #1652
=> Upgrade net46 to net462

src/SonarScanner.MSBuild.TFS.Classic/BinaryToXmlCoverageReportConverter.cs
The `ApplicationCutureInfo` usage is a workaround for https://github.com/microsoft/codecoverage/issues/63. It should be removed once https://github.com/microsoft/codecoverage/issues/63 is resolved and published. A comment on the usage helps track the work and the future me's.
=> Add comment with link to CodeCoverage issue

Tests/SonarScanner.MSBuild.TFS.Test/Classic/BinaryToXmlCoverageReportConverterTests.cs, scripts/package-artifacts.ps1, src/SonarScanner.MSBuild.TFS.Classic/BinaryToXmlCoverageReportConverter.cs, src/SonarScanner.MSBuild.TFS.Classic/Resources.Designer.cs, src/SonarScanner.MSBuild.TFS.Classic/Resources.resx
Fixes issues found during the test release of the extension:
=> CodeCoverage.exe removal fixes

Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
=> Add reproducer for #1706

azure-pipelines.yml, scripts/sign.ps1
The signing steps were disabled in #1724 since the certificate expired. This PR is adding them back.
- https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=80613&view=results
- https://github.com/SonarSource/sonar-scanner-msbuild/pull/1760
While testing the issue, I found: #1759. This should be solved separately (the problem existed before disabling the signing).
=> Re-enable signing

Tests/SonarScanner.MSBuild.PreProcessor.Test/EmbeddedAnalyzerInstallerTests.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/EmbeddedAnalyzerInstaller.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynResources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynResources.resx
=> Fail hard when C# and VB.NET plugins are missing on the server

azure-pipelines.yml, its/pom.xml, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerClassifier.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java, nuspec/chocolatey/chocolateyInstall-net-framework.ps1, nuspec/chocolatey/chocolateyInstall-net46.ps1, nuspec/chocolatey/sonarscanner-net-framework.nuspec, pom.xml, scripts/ci-build.ps1, scripts/package-artifacts.ps1, scripts/sign.ps1
Fixes #1769
This commit also changes the package name on repox. This part was not included in the specification since we were not aware that we publish also on repox.
The repox packages are used by the orchestrator to download the scanner. If there are consumers that need to reference the latest version, they will have to update the artifactId from "sonar-scanner-msbuild" to "sonar-scanner".
I've tested the ps1 script for the chocolatey package with:
```powershell
$version = "6.0.0.81085"
$classicScannerZipPath = Get-Item .\build\sonarscanner-net-framework.zip
$classicZipHash = (Get-FileHash $classicScannerZipPath -Algorithm SHA256).hash
$netFrameworkPs1 = "nuspec\chocolatey\chocolateyInstall-net-framework.ps1"
(Get-Content $netFrameworkPs1) -Replace '-Checksum "not-set"', "-Checksum …
```
=> Rename sonarscanner-msbuild-net46 to sonarscanner-net-framework

Tests/SonarScanner.MSBuild.Common.Test/CommandLine/CommandLineParserTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.Test/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.Test/ProgramTests.cs, src/Directory.Build.targets, src/SonarScanner.MSBuild.Common/CommandLine/CommandLineParser.cs, src/SonarScanner.MSBuild.PostProcessor/ArgumentProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs, src/SonarScanner.MSBuild/ArgumentProcessor.cs, src/SonarScanner.MSBuild/BootstrapperClass.cs, src/SonarScanner.MSBuild/Properties/AssemblyInfo.cs, src/SonarScanner.MSBuild/Properties/InternalsVisibleTo.cs, src/SonarScanner.MSBuild/Resources.Designer.cs, src/SonarScanner.MSBuild/Resources.resx
Fixes #1721 
Additional changes:
- Internals from `SonarScanner.MSBuild` have been exposed to `SonarScanner.MSBuild.Test` 
- CaYC: File based namespaces have been introduced on modified files: use the `Hide whitespaces` feature from GitHub for a better reviewing experience
- ~Changes language version from `9.0` to `latest` for all projects, allowing for the use of recent C# features (including more pattern matching and collections expressions from C# 12)~
- Extracted into [a dedicated PR](https://github.com/SonarSource/sonar-scanner-msbuild/pull/1793)
- Changes the behavior of the log parser in presence of duplicated arguments (that is a blocking error)
- Instead of clearing out the list of arguments, returns the valid arguments
- The change allows to avoid having a second error message …
=> Make `begin`/`end` phase mandatory on command line

src/SonarScanner.MSBuild.Tasks/SonarScanner.MSBuild.Tasks.csproj
Fixes #1596
- Bump `Microsoft.Build` from **14.3.0** to **15.9.20**
- Bump `Microsoft.Build.Utilities.Core` from **14.3.0** to **15.9.20**
=> Bump dependency versions as part of S4NET 6.0.0 release

NuGet.Config, azure-pipelines.yml
Fixes #1795
This has been tested against a NuGet repository that requires authentication. (see 
BUILD-4368)
Until https://repox.jfrog.io/artifactory/api/nuget/nuget enforces authentication, it will work without authentication, issues may raise once authentication is enforced on this repository.
=> Add NuGet authentication

NuGet.Config, azure-pipelines.yml, its/projects/ReproAzureFunctions/NuGet.Config, its/projects/VueWithAspBackend/NuGet.Config
Identified problems:
- the nuget url was not correct, the recommended one is: https://repox.jfrog.io/artifactory/api/nuget/v3/nuget/index.json
- the protocol was not specified
- there are NuGet.config files dedicated to some ITs and those files were not updated to include the authentication section
- the nuget authentication credentials were not provided for the ITs
=> Fix build: ensure that secrets are available during NuGet restore

NuGet.Config
It was previously set directly on the machine, but it's too hard to change since we have to wait for the image to be built and deployed.
PR to remove it: https://github.com/SonarSource/re-ci-images/pull/447
=> Add fingerprint for our certificate

azure-pipelines.yml
This prepares the branch for using the new VMs that do not have Visual Studio installed.
Additionally, the IT task ids have been renamed to specify msbuild version instead of visual studio version.
=> CI: Use build tools paths instead of visual studio

Tests/SonarScanner.MSBuild.Common.Test/EnvironmentBasedPlatformHelperTests.cs, Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs, src/SonarScanner.MSBuild.Common/EnvironmentBasedPlatformHelper.cs, src/SonarScanner.MSBuild.Common/Interfaces/IPlatformHelper.cs, src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs, src/SonarScanner.MSBuild.Shim/TFSProcessor.Wrapper.cs
Fixes #1862
The solution implemented is to place the `targets` file in both locations, specifically for MacOSX.
Because `GetFolderPath` may return either the new path or the old one, depending on the runtime, we do the following.
- First, retrieve the path via `GetFolderPath` with `UserProfile`. That will place us in the right user context.
- Then, include the old and the new locations, as relative paths to the user profile directory (hardcoded).
- We also include the `GetFolderPath` with `LocalApplicationData` to be future-proof (i.e. in case the path may change in the future).
=> Fix analysis on MacOSX with .NET 8 when begin runtime doesn't match with build runtime

.gitattributes, azure-pipelines.yml, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
Fixes #1477
ITs from `others` package were not executed during CI QA.
They need `build` directory to exist. So this PR renames the `build` artifact from `build` directory back to be `build`.
=> ITs: Run QA also for others

.runsettings
This reduces UT runtime from 1m12s to 47s locally.
This will instruct the test adapter to run all test DLLs in parallel when running UTs via Test Explorer.
=> UTs: Add .runsettings to run UTs in parallel

azure-pipelines.yml
According to the following example: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?tabs=yaml&view=azure-devops#examples, wildcards are supported.
=> CI: Add `branch-` prefix to predefined triggers

its/projects/VueWithAspBackend/AspBackend/Program.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
Fixes failing IT after S6966 was merged to sonar-dotnet master.
=> Fix ScannerMSBuildTest after S6966 was merged

NuGet.Config, StylingAnalyzers.targets, Tests/Directory.Build.targets, src/Directory.Build.targets
Same as https://github.com/SonarSource/sonar-dotnet/pull/9207
=> Use SonarAnalyzer.CSharp.Styling

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
To fix the following issue:
```
System.NotSupportedException: Unsupported log file format. Latest supported version is 17, the log file has version 18.
```
=> Bump MSBuild.StructuredLogger

its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
We do not need a specific version of MsBuild for this test, and it simplifies the code.
=> ITs: use dotnet instead of msbuild

Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs, azure-pipelines.yml, scripts/run-unit-tests.ps1
Fixes #1934 
---
I have done some tests and was able to have a green CI for the Build stage.
To do so, I had to disable/comment on any task related to the SBOM file:
- `Dotnet generate SBOM` task
- `Generate packages` task: I commented two lines in the script
- `Stage to repox` task which needs the file to continue
Once the build of the dotnet-ci AMI is working, I do not expect to see any other issues, except maybe in the `Stage to repox`.
**Update (from Zsolt):** I re-enabled the tasks and modified the SBOM generation to make it work with the new image.
=> Run on our infrastructure

azure-pipelines.yml
These files are only used for signing binaries during the Release builds, they don't need to be downloaded for PR builds.
=> Don't download files for signing on PR branches

Tests/SonarScanner.MSBuild.Common.Test/CmdLineArgsPropertiesProviderTests.cs, Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs, src/SonarScanner.MSBuild.PreProcessor/SonarServer.cs
Contributes to https://github.com/SonarSource/sonar-scanner-msbuild/issues/1960
Based on #1967
=> Add support for JRE provisioning: Add sonar.scanner.apiBaseUrl parameter

Tests/SonarScanner.MSBuild.Common.Test/RegexExtensionsTest.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs, src/SonarScanner.MSBuild.Common/RegexExtensions.cs, src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
Currently, the argument validation is split between two classes. This change moves all validation into a single class.
This change is required to simplify the validation for the properties added in
https://github.com/SonarSource/sonar-scanner-msbuild/pull/1981
https://github.com/SonarSource/sonar-scanner-msbuild/pull/1977
=> Move args validation to a single place

Tests/SonarScanner.MSBuild.Common.Test/CmdLineArgsPropertiesProviderTests.cs, Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
Contributes to https://github.com/SonarSource/sonar-scanner-msbuild/issues/1960
=> Add support for JRE provisioning: sonar.scanner.javaExePath + sonar.scanner.skipJreProvisioning

Tests/SonarScanner.MSBuild.Tasks.UnitTest/GetAnalyzerSettingsTests.cs, src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
The check is always true for SonarCloud, as well as SonarQube >= 8.9
*(The earliest supported version of SQ at the time of writing is 9.9)*
=> Remove IsTestAnalysisSupported

Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
Adds logging to JreCache.
Based on #2011
=> Add support for JRE provisioning: Add logging for the Jre download cache

Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreResolverTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/IJreResolver.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreResolver.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
Fixes #2027
Next PR will make use of the resolver in the `Preprocessor.Execute`
=> Add support for JRE provisioning: JreResolver

azure-pipelines.yml
The ITs are failing with the following error:
```
java.lang.IllegalStateException: Can not find the plugin [com.sonarsource.cpp:sonar-cfamily-plugin:LATEST_RELEASE:jar]
at com.sonar.orchestrator.server.ServerInstaller.installPluginIntoDir(ServerInstaller.java:211)
at com.sonar.orchestrator.server.ServerInstaller.copyPlugins(ServerInstaller.java:204)
at com.sonar.orchestrator.server.ServerInstaller.copyExternalPlugins(ServerInstaller.java:188)
at com.sonar.orchestrator.server.ServerInstaller.preparePlugins(ServerInstaller.java:113)
at com.sonar.orchestrator.server.ServerInstaller.install(ServerInstaller.java:94)
at com.sonar.orchestrator.Orchestrator.install(Orchestrator.java:98)
at com.sonar.orchestrator.Orchestrator.start(Orchestrator.java:118)
at …
```
=> CI: Fix the cfamily plugin version

Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
=> Fix sonarUserHome usage in Preprocessor's invocation of the JRE resolver

Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
=> Add support for JRE provisioning: Do checksum validation before rename

NuGet.Config, Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/TarGzUnpackTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/UnpackerFactoryTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs, src/SonarScanner.MSBuild.Common/Interfaces/IOperatingSystemProvider.cs, src/SonarScanner.MSBuild.Common/OperatingSystemProvider.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/IUnpackerFactory.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/TarGzUnpacker.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/UnpackerFactory.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/SonarScanner.MSBuild.PreProcessor.csproj
=> Add support for JRE provisioning: Jre tar.gz unpack

azure-pipelines.yml
This reverts commit 8656dfaaa86ebeffe36b98157cb36b2f40a3c4ef.
Fixes [#2046](https://github.com/SonarSource/sonar-scanner-msbuild/issues/2046)
=> Revert "[TO BE REVERTED] Disable SonarCloud ITs (#2043)"

Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/TarGzUnpackTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/UnpackerFactoryTests.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/FilePermissionsWrapper.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/IFilePermissionsWrapper.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/TarGzUnpacker.cs, src/SonarScanner.MSBuild.PreProcessor/JreCaching/UnpackerFactory.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
=> Add support for JRE provisioning: Jre tar.gz unpack - extract IFilePermissionsProvider

its/projects/JreProvisioning/JreProvisioning.sln, its/projects/JreProvisioning/JreProvisioning/JreProvisioning.csproj, its/projects/JreProvisioning/JreProvisioning/Sample.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/Constants.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/SonarCloudUtils.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
Adds 3 ITs:
- skip-provisioning set to true
- mismatch in host.url and sonarcloudUrl
- E2E with cache miss, downloading the JRE.
There are many more tests that could be added, but I added these as a baby step, so that we at least have something on the pipeline before we start the manual testing.
=> JRE Provisioning: Add ITs for SonarCloud

Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Unpacking/TarGzUnpackTests.cs, src/SonarScanner.MSBuild.PreProcessor/FilePermissionsWrapper.cs, src/SonarScanner.MSBuild.PreProcessor/Interfaces/IFilePermissionsWrapper.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs, src/SonarScanner.MSBuild.PreProcessor/Unpacking/TarGzUnpacker.cs
Follow-up to #2048
Remove the TarEntry dependency from IFilePermissionsWrapper
=> JRE Provisioning: Refactor IFilePermissionsWrapper

scripts/package-artifacts.ps1, src/SonarScanner.MSBuild.PreProcessor/FilePermissionsWrapper.cs, src/SonarScanner.MSBuild.PreProcessor/SonarScanner.MSBuild.PreProcessor.csproj
Mono.Posix did not work on Alpine already, and the way it is build would mess with our release (it requires a multi-platform SO dependency).
We will keep it simple and use `chmod` everywhere.
=> JRE Provisioning: Rework file permissions on linux

its/projects/ReproAzureFunctions/ReproAzureFunctions/ReproAzureFunctions.csproj, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
Updating to fix this alert on Mend: https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!libraryDetails;uuid=61ef33d9-3b91-4826-9579-2e26368667c3;product=285470;orgToken=b55a9158-7eca-400e-809d-5d5f0a5ea7df
=> ITs: Update package in ReproAzureFunctions project to not raise alerts on Mend

Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs, src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs, src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
=> Multi-Language Support: Rework WriteSharedFiles

scripts/package-artifacts.ps1
=> Releases produce zip files with a backslash as a separator (#2087)

Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
[SCAN4NET-23](https://sonarsource.atlassian.net/browse/SCAN4NET-23)
[SCAN4NET-23]: https://sonarsource.atlassian.net/browse/SCAN4NET-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-23: Exclude coverage files manually

README.md, SECURITY.md
This file needs to be present for all Sonar public repositories, for more information please refer to BUILD-6088.
=> BUILD-6088 Create Security.md

Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs, src/SonarScanner.MSBuild.Common/SonarProperties.cs, src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
=> SCAN4NET-26: Exit-early on sonar.sources or sonar.tests

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/generate-packages.ps1, scripts/promote-project-version.ps1, scripts/version/ChangeVersion.proj, scripts/version/Version.props, scripts/version/set-version.ps1
[SCAN4NET-34](https://sonarsource.atlassian.net/browse/SCAN4NET-34)
[SCAN4NET-34]: https://sonarsource.atlassian.net/browse/SCAN4NET-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-34 Change version to 9.0.0-rc

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-39](https://sonarsource.atlassian.net/browse/SCAN4NET-39)
[SCAN4NET-39]: https://sonarsource.atlassian.net/browse/SCAN4NET-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-39 Bump version to 9.0.0

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RoslynTargetsTests.cs, azure-pipelines.yml, its/projects/DotnetProjectTypeDetection/TestProjectWrongReferenceCasing/TestProjectWrongReferenceCasing.csproj, its/projects/ExcludedTest/Excluded/Excluded.csproj, its/projects/ExcludedTest/Normal/Normal.csproj, its/projects/ExcludedTest/Test/Test.csproj, its/projects/IncrementalPRAnalysis/IncrementalPRAnalysis/IncrementalPRAnalysis.csproj, its/projects/XamarinApplication/XamarinApplication/XamarinApplication.csproj
[SCAN4NET-30](https://sonarsource.atlassian.net/browse/SCAN4NET-30)
[SCAN4NET-30]: https://sonarsource.atlassian.net/browse/SCAN4NET-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Infra: Update the UTs and ITs to be able to run on .NET 9 preview

scripts/version/set-version.ps1
[SCAN4NET-41](https://sonarsource.atlassian.net/browse/SCAN4NET-41)
Allows numbering in prereleases, e.g.:
- rc
- rc2
- rc99
[SCAN4NET-41]: https://sonarsource.atlassian.net/browse/SCAN4NET-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-41 Prerelease versioning: Allow numbering

its/projects/MultiLanguageSupportAngular/ClientApp/package-lock.json, its/projects/MultiLanguageSupportReact/ClientApp/package-lock.json
[SCAN4NET-45](https://sonarsource.atlassian.net/browse/SCAN4NET-45)
I used `npm audit fix --force` to resolve vulnerabilities in dependencies of MultiLanguageSupportReact and MultiLanguageSupportAngular projects by updating them to the latest versions.
[SCAN4NET-45]: https://sonarsource.atlassian.net/browse/SCAN4NET-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-45 Bump dependencies on Angular and React ClientApp

Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs, its/projects/MultiLanguageSupport/src/should_be_ignored.xml, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java, src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
[SCAN4NET-42](https://sonarsource.atlassian.net/browse/SCAN4NET-42)
[SCAN4NET-42]: https://sonarsource.atlassian.net/browse/SCAN4NET-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-42 Multi-Language Support: Ignore XML files

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-74](https://sonarsource.atlassian.net/browse/SCAN4NET-74)
[SCAN4NET-74]: https://sonarsource.atlassian.net/browse/SCAN4NET-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-74 Bump version to 8.0.4

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs, src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs, src/SonarScanner.MSBuild.Tasks/Resources.resx, src/SonarScanner.MSBuild.Tasks/WriteProjectInfoFile.cs
[SCAN4NET-88](https://sonarsource.atlassian.net/browse/SCAN4NET-88)
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-59
[SCAN4NET-88]: https://sonarsource.atlassian.net/browse/SCAN4NET-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-88 INFO level for invalid project GUIDs messages

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
[SCAN4NET-90](https://sonarsource.atlassian.net/browse/SCAN4NET-90)
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-47
It has the fix for https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/817
[SCAN4NET-90]: https://sonarsource.atlassian.net/browse/SCAN4NET-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-90 Update MSBuild.StructuredLogger to 2.2.350

Tests/SonarScanner.MSBuild.Common.Test/ILoggerTests.cs, Tests/SonarScanner.MSBuild.Common.Test/Infrastructure/OutputCaptureScope.cs, Tests/SonarScanner.MSBuild.Common.Test/Infrastructure/OutputRecorder.cs, src/SonarScanner.MSBuild.Common/ConsoleLogger.cs
[SCAN4NET-96](https://sonarsource.atlassian.net/browse/SCAN4NET-96)
[SCAN4NET-97](https://sonarsource.atlassian.net/browse/SCAN4NET-97)
[SCAN4NET-96]: https://sonarsource.atlassian.net/browse/SCAN4NET-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-97]: https://sonarsource.atlassian.net/browse/SCAN4NET-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-96 and SCAN4NET-97: Fix logger timestamp duplication

Tests/SonarScanner.MSBuild.Common.Test/ILoggerTests.cs, src/SonarScanner.MSBuild.Common/ConsoleLogger.cs
=> SCAN4NET-100 Remove timestamps from UI Warnings

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
SCAN4NET-105
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-93
Unit tests are failing since the MsBuild structured logger is logging this warning: https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/src/StructuredLogger/BinaryLog.cs#L169 when running on .NET 9 rc-1
=> SCAN4NET-105 Update MSBuild.StructuredLogger to fix build

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-110](https://sonarsource.atlassian.net/browse/SCAN4NET-110)
[SCAN4NET-110]: https://sonarsource.atlassian.net/browse/SCAN4NET-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-110 Bump version to 9.1.0

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj, src/SonarScanner.MSBuild.Tasks/SonarScanner.MSBuild.Tasks.csproj
[SCAN4NET-117](https://sonarsource.atlassian.net/browse/SCAN4NET-117)
This fixes a high-severity security vulnerability reported by Mend.
https://github.com/dotnet/runtime/issues/108678
https://www.mend.io/vulnerability-database/CVE-2024-43485
[SCAN4NET-117]: https://sonarsource.atlassian.net/browse/SCAN4NET-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-117 Upgrade System.Text.Json

its/projects/CSharpAllFlat/ClassLib1.csproj, its/projects/CSharpAllFlat/ClassLib2.csproj
[SCAN4NET-135](https://sonarsource.atlassian.net/browse/SCAN4NET-135)
Part of https://sonarsource.atlassian.net/browse/NET-7
[SCAN4NET-135]: https://sonarsource.atlassian.net/browse/SCAN4NET-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-135 ITs: Update CSharpAllFlat to new format and .NET 9

azure-pipelines.yml
[SCAN4NET-142](https://sonarsource.atlassian.net/browse/SCAN4NET-142)
[SCAN4NET-142]: https://sonarsource.atlassian.net/browse/SCAN4NET-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-142 Revert to using predefined variables to build coverage path

src/SonarScanner.MSBuild.Common/TFS/BuildSettings.cs
[SCAN4NET-148](https://sonarsource.atlassian.net/browse/SCAN4NET-148)
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-147
The environment variables under Unix are case-sensitive. Is set the value from the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#:~:text=No-,TF_BUILD,-Set%20to%20True).
Since the current pipeline is configured to run under Windows, I currently cannot add an integration test. I added a point on https://trello.com/c/f58uStZK to add an integration test once we have a Unix pipeline.
[SCAN4NET-148]: https://sonarsource.atlassian.net/browse/SCAN4NET-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-148 Use the correct environment variable name

its/projects/MultiLanguageSupportAngular/ClientApp/package-lock.json, its/projects/MultiLanguageSupportReact/ClientApp/package-lock.json
I used `npm audit fix—-force` to update the dependencies of MultiLanguageSupportReact and MultiLanguageSupportAngular projects to the latest versions and resolve vulnerabilities.
=> SCAN4NET-99 Bump dependencies on Angular and React ClientApp

its/projects/XamarinApplication/XamarinApplication.iOS/XamarinApplication.iOS.csproj, its/projects/XamarinApplication/XamarinApplication/XamarinApplication.csproj, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
On the latest Golden AMI, when using MSBuild 15, the build fails with 
```
error MSB4018: System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
```
I've updated the dependencies and skipped the test for XAML Compilation on MSBuild 15.
=> SCAN4NET-154 ITs: Update the Xamarin test project dependencies

azure-pipelines.yml
[SCAN4NET-38](https://sonarsource.atlassian.net/browse/SCAN4NET-38)
Published artifacts:
The last run of the python script based promotion:
https://repox.jfrog.io/ui/builds/sonar-scanner-msbuild/99288/1725524835930/published/org.sonarsource.scanner.msbuild:scanner-msbuild-its:9.0.0.99288
The first run with the [JFrogBuildPromotion](https://github.com/jfrog/jfrog-azure-devops-extension?tab=readme-ov-file#jfrog-build-promotion) task
https://repox.jfrog.io/ui/builds/sonar-scanner-msbuild/99295/1725527058518/published/org.sonarsource.scanner.msbuild:scanner-msbuild-its:9.0.0.99295
[SCAN4NET-38]: https://sonarsource.atlassian.net/browse/SCAN4NET-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-38 Remove python promote script

Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
[SCAN4NET-160](https://sonarsource.atlassian.net/browse/SCAN4NET-160)
[SCAN4NET-160]: https://sonarsource.atlassian.net/browse/SCAN4NET-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-160 ComputeProjectBaseDir: Respect SONARQUBE_SCANNER_PARAMS

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-161](https://sonarsource.atlassian.net/browse/SCAN4NET-161)
[SCAN4NET-161]: https://sonarsource.atlassian.net/browse/SCAN4NET-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-161 Bump version (back) to 9.1.0

its/projects/CodeCoverage/CodeCoverage.Test/CodeCoverage.Test.csproj, its/projects/CodeCoverage/CodeCoverage/CodeCoverage.csproj
[SCAN4NET-187](https://sonarsource.atlassian.net/browse/SCAN4NET-187)
Prerequesite for [removing .NET 7 from the CI image](https://trello.com/c/rusfGxhV/1617-remove-dotnet-7-installation-from-the-ci-image)
[SCAN4NET-187]: https://sonarsource.atlassian.net/browse/SCAN4NET-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-187 Upgrade CodeCoverage IT to .NET 9

azure-pipelines.yml, its/projects/CSharp.Framework.4.8/Main/Common.cs, its/projects/CSharp.Framework.4.8/UTs/CommonTest.cs, its/projects/CSharp.SDK.8/Main/Common.cs, its/projects/CSharp.SDK.8/UTs/CommonTest.cs, its/projects/CSharp.SDK.Latest/Main/Common.cs, its/projects/CSharp.SDK.Latest/UTs/CommonTest.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-178](https://sonarsource.atlassian.net/browse/SCAN4NET-178)
https://trello.com/c/p7ix7jIS/1624-s4net-pin-the-bundled-plugin-version-to-sq89-and-sq99-its
[SCAN4NET-178]: https://sonarsource.atlassian.net/browse/SCAN4NET-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-178 Pin bundled plugin version to SQ8.9/9.9 ITs

Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockAnalyzerInstaller.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockRoslynAnalyzerProvider.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynRuleSetGeneratorTests.cs
[SCAN4NET-217](https://sonarsource.atlassian.net/browse/SCAN4NET-217)
Part of SCAN4NET-171
This PR is based on top of https://github.com/SonarSource/sonar-scanner-msbuild/pull/2295. 
[SCAN4NET-217]: https://sonarsource.atlassian.net/browse/SCAN4NET-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-217 Refactor RoslynAnalyzerProviderTests and RoslynRuleSetGeneratorTests

Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynRuleSetGeneratorTests.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs, src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynRuleSetGenerator.cs
[SCAN4NET-221](https://sonarsource.atlassian.net/browse/SCAN4NET-221)
Part of 
[SCAN4NET-221]: https://sonarsource.atlassian.net/browse/SCAN4NET-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-221 Use constants for RoslynRuleSetGenerator legacy attributes

Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/ServerBuilder.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
[SCAN4NET-230](https://sonarsource.atlassian.net/browse/SCAN4NET-230)
`ServerBuilder.StartServer` does not really need a file as input since we moved to the certificate store as the source for the mock server certificates. This change makes starting the server a bit easier and the file indirection is avoided.
[SCAN4NET-230]: https://sonarsource.atlassian.net/browse/SCAN4NET-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-230 ServerBuilder.StartServer takes certificates instead of filename

Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
[SCAN4NET-229](https://sonarsource.atlassian.net/browse/SCAN4NET-229)
[SCAN4NET-229]: https://sonarsource.atlassian.net/browse/SCAN4NET-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-229 Implement ServerCertificateCustomValidationCallback in WebClientDownloaderBuilder for self-signed certificates for direct CAs.

Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
[SCAN4NET-233](https://sonarsource.atlassian.net/browse/SCAN4NET-233)
[SCAN4NET-233]: https://sonarsource.atlassian.net/browse/SCAN4NET-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-233 Implement ServerCertificateCustomValidationCallback in WebClientDownloaderBuilder for intermediate CAs

Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/AnalysisConfigGeneratorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/PropertyAsScannerOptsMappingProcessorTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs, src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfig.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/AnalysisConfigGenerator.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/PropertyAsScannerOptsMappingProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/PropertyMappingProcessor.cs, src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
[SCAN4NET-234](https://sonarsource.atlassian.net/browse/SCAN4NET-234)
Part of SCAN4NET-207
[SCAN4NET-234]: https://sonarsource.atlassian.net/browse/SCAN4NET-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-234 Use SONAR_SCANNER_OPTS to map the new properties

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/SslUtils.java, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
[SCAN4NET-211](https://sonarsource.atlassian.net/browse/SCAN4NET-211)
[SCAN4NET-211]: https://sonarsource.atlassian.net/browse/SCAN4NET-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-211 Add ITs with the new truststore properties

Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
[SCAN4NET-241](https://sonarsource.atlassian.net/browse/SCAN4NET-241)
[SCAN4NET-241]: https://sonarsource.atlassian.net/browse/SCAN4NET-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-241 Add logging for file I/O errors in AddServerCertifcate

Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx, src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
[SCAN4NET-244](https://sonarsource.atlassian.net/browse/SCAN4NET-244)
Part of  SCAN4NET-209
[SCAN4NET-244]: https://sonarsource.atlassian.net/browse/SCAN4NET-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-244 Add logging for ServerCertificateValidationChain

.github/workflows/PullRequestClosed.yml
[SCAN4NET-278](https://sonarsource.atlassian.net/browse/SCAN4NET-278)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SCAN4NET-278]: https://sonarsource.atlassian.net/browse/SCAN4NET-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-278 Autoclose issues created by Jira integration

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-279](https://sonarsource.atlassian.net/browse/SCAN4NET-279)
Testing theory that the logs produced by these two ITs are so big they make the `Finalize Job` step timeout.
Context: https://sonarsource.slack.com/archives/C03HVJQ53M2/p1741099602888699
[SCAN4NET-279]: https://sonarsource.atlassian.net/browse/SCAN4NET-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-279 Remove verbose log from Angular & React ITs

its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java, scripts/build-utils.ps1
[SCAN4NET-286](https://sonarsource.atlassian.net/browse/SCAN4NET-286)
For case when MSBUILD_PATH is not set
[SCAN4NET-286]: https://sonarsource.atlassian.net/browse/SCAN4NET-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-286 Use MsBuild from VS 2022 Professional by default

azure-pipelines.yml
=> SCAN4NET-295 Clean workspace for each job

Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
[SCAN4NET-296](https://sonarsource.atlassian.net/browse/SCAN4NET-296)
[SCAN4NET-296]: https://sonarsource.atlassian.net/browse/SCAN4NET-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-296 Use cloudflarestatus.com instead of httpbin.org for testing

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerClassifier.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-198](https://sonarsource.atlassian.net/browse/SCAN4NET-198)
Key changes are:
* Adding `ScannerCommand`
* Updating `TestUtils` to use `ScannerCommand`
That required changes in tests:
* `ORCHESTRATOR.execute(scanner)` is changed to `scanner.execute(ORCHESTRATOR)` so we can centralize the behavior and eventually simplify the usages
* `SslTest` no longer throws an exception => mechanical refactoring of assertions. Please make sure I did not delete any `server.stop();` calls by accident
Plus there's a bit of auto-formatting noise.
This PR does as few changes as possible, without CaYC to keep it as small as possible. Bunch of methods in `ScannerCommand` are no-op and will be removed later just to enable the new `ScannerCommand` to serve as a in-place replacement with minimal …
=> SCAN4NET-198 Create minimal ScannerCommand class

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-321](https://sonarsource.atlassian.net/browse/SCAN4NET-321)
Nicer way of using keys will be done in https://sonarsource.atlassian.net/browse/SCAN4NET-298
Commit `Remove newScanner` doesn't need a review, it's in #2372
[SCAN4NET-321]: https://sonarsource.atlassian.net/browse/SCAN4NET-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-321 Use unique projectKey in ITs

its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudConstants.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ServerTests.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerClassifier.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-347](https://sonarsource.atlassian.net/browse/SCAN4NET-347)
Prerequisite for [SCAN4NET-346](https://sonarsource.atlassian.net/browse/SCAN4NET-346)
[SCAN4NET-347]: https://sonarsource.atlassian.net/browse/SCAN4NET-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-346]: https://sonarsource.atlassian.net/browse/SCAN4NET-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Rename Cloud-specific files to `Cloud` prefix.
Rename `Tests.java` to `ServerTests.java`, as there will be `CloudTests.java` and we already had issues in sonar-dotnet due to similar confusion in the past of having multiple `Tests.java`
=> SCAN4NET-347 Rename Cloud and Server utilities

Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs
[SCAN4NET-352](https://sonarsource.atlassian.net/browse/SCAN4NET-352)
Part of [SCAN4NET-351](https://sonarsource.atlassian.net/browse/SCAN4NET-351)
Based on #2400
[SCAN4NET-351]: https://sonarsource.atlassian.net/browse/SCAN4NET-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-352]: https://sonarsource.atlassian.net/browse/SCAN4NET-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-352 Adopt trust store exception for sonar cloud region "us"

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
[SCAN4NET-330](https://sonarsource.atlassian.net/browse/SCAN4NET-330)
Part of SCAN4NET-291
Red CI is due to canceled jobs => not worth restarting, as a rebase will be needed anyway
[SCAN4NET-330]: https://sonarsource.atlassian.net/browse/SCAN4NET-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-330 Rename ScannerMsBuildTest

Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs, src/SonarScanner.MSBuild.PreProcessor/HostInfo.cs
[SCAN4NET-358](https://sonarsource.atlassian.net/browse/SCAN4NET-358)
Part of 
[SCAN4NET-358]: https://sonarsource.atlassian.net/browse/SCAN4NET-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-358 host.url = sonarqube.us should infer the us region

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-349](https://sonarsource.atlassian.net/browse/SCAN4NET-349)
[SCAN4NET-349]: https://sonarsource.atlassian.net/browse/SCAN4NET-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-349 Bump version to 10.2.0

its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
[SCAN4NET-377](https://sonarsource.atlassian.net/browse/SCAN4NET-377)
The `describeAs("Lorem ipsum\n Dolor sit amet` produces this in the middle of the logs
```
[ERROR] com.sonar.it.scanner.msbuild.sonarcloud.IncrementalPRAnalysisTest.debug_assertThat_describedAs -- Time elapsed: 0 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Lorem ipsum
Dolor sit amet] 
Expecting value to be true but was false
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at …
```
=> SCAN4NET-377 Dump logs on failed ITs in AnalysisContext

templates/unix-qa-stage.yml
[SCAN4NET-388]
UTs in the overview are displayed like this now:
instead of:
[SCAN4NET-388]: https://sonarsource.atlassian.net/browse/SCAN4NET-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-388 Provide testRunTitle to Linux/MacOS UT

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/BaseCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/GeneralCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/Timeout.java
[SCAN4NET-386](https://sonarsource.atlassian.net/browse/SCAN4NET-386)
SCAN4NET-12 reduced the `end` step timeout from 120sec to 60sec. Some of the ITs need to be restored back
[SCAN4NET-386]: https://sonarsource.atlassian.net/browse/SCAN4NET-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-386 Restore some IT timeouts

SonarScanner.MSBuild.sln, Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.Net.Tests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/ServerBuilder.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs, Tests/TestUtilities/TestCategories.cs, scripts/run-test-docker.ps1, scripts/run-test-linux.ps1, scripts/run-test-wsl.ps1, templates/unix-qa-stage.yml
[SCAN4NET-394](https://sonarsource.atlassian.net/browse/SCAN4NET-394)
Part of SCAN4NET-311
[SCAN4NET-394]: https://sonarsource.atlassian.net/browse/SCAN4NET-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-394 Fix SonarScanner.MSBuild.PreProcessor.Test.CertificateBuilderTests UTs on Linux/MacOS

Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilder.Net.Test.cs
[SCAN4NET-396](https://sonarsource.atlassian.net/browse/SCAN4NET-396)
Part of [SCAN4NET-311](https://sonarsource.atlassian.net/browse/SCAN4NET-311)
[SCAN4NET-311]: https://sonarsource.atlassian.net/browse/SCAN4NET-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-396]: https://sonarsource.atlassian.net/browse/SCAN4NET-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-396 Fix WebClientDownloaderBuilder.Net.Test UT on Linux/MacOS

azure-pipelines.yml, templates/unix-qa-stage.yml
[SCAN4NET-418](https://sonarsource.atlassian.net/browse/SCAN4NET-418)
[SCAN4NET-418]: https://sonarsource.atlassian.net/browse/SCAN4NET-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
`ubuntu-latest` now points to `ubuntu-24.04` which does not contain the .NET9 SDK/runtime.
We'll temporality point to `ubuntu-22.04`.
Github issue opened to solve the issue: https://github.com/actions/runner-images/issues/11965
=> SCAN4NET-418 [To be reverted] Point runner to ubuntu-22.04

.github/workflows/SlackNotification.yml
[SCAN4NET-419](https://sonarsource.atlassian.net/browse/SCAN4NET-419)
sonar-runner is not available to public repos
[SCAN4NET-419]: https://sonarsource.atlassian.net/browse/SCAN4NET-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-419 Fix SlackNotification runner

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java, templates/unix-qa-stage.yml
[SCAN4NET-324](https://sonarsource.atlassian.net/browse/SCAN4NET-324)
The tests has been disabled on Linux and MacOS.
The project built is using windows specific dependencies.
[SCAN4NET-324]: https://sonarsource.atlassian.net/browse/SCAN4NET-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-324 Disable CppTest ITs on Linux & MacOS

AssemblyInfo.Shared.cs, nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec, scripts/version/Version.props
[SCAN4NET-441](https://sonarsource.atlassian.net/browse/SCAN4NET-441)
[SCAN4NET-441]: https://sonarsource.atlassian.net/browse/SCAN4NET-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-441 Bump version to 10.1.2

Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
[SCAN4NET-443](https://sonarsource.atlassian.net/browse/SCAN4NET-443)
[SCAN4NET-443]: https://sonarsource.atlassian.net/browse/SCAN4NET-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-443 Exclude GenerateFile_Duplicate_SameGuid_DifferentCase_ShouldNotIgnoreCase test from Unix until further investigation

testenvironments.json
[SCAN4NET-483](https://sonarsource.atlassian.net/browse/SCAN4NET-483)
Enable Linux UT debugging via VisualStudio:
https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022
[SCAN4NET-483]: https://sonarsource.atlassian.net/browse/SCAN4NET-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-483 Add testenvironment.json

Tests/SonarScanner.MSBuild.Common.Test/AggregatePropertiesProviderTests.cs, Tests/SonarScanner.MSBuild.Common.Test/AnalysisProperties/AnalysisPropertyProviderExtensionsTests.cs, Tests/SonarScanner.MSBuild.Common.Test/EmptyPropertyProviderTest.cs, Tests/SonarScanner.MSBuild.Common.Test/EnvScannerPropertiesProviderTest.cs, Tests/SonarScanner.MSBuild.Common.Test/FilePropertyProviderTests.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/AggregatePropertiesProvider.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/CmdLineArgPropertyProvider.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/EnvScannerPropertiesProvider.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/FilePropertyProvider.cs, src/SonarScanner.MSBuild.Common/AnalysisProperties/ListSettingsProvider.cs, src/SonarScanner.MSBuild.Common/Interfaces/IAnalysisPropertyProvider.cs, src/SonarScanner.MSBuild.Common/Telemetry/PropertyProviderKind.cs
[SCAN4NET-485](https://sonarsource.atlassian.net/browse/SCAN4NET-485)
[SCAN4NET-485]: https://sonarsource.atlassian.net/browse/SCAN4NET-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR:
1. Adds provider kind to IAnalysisPropertyProvider
2. Add new GetAllPropertiesWithProvider to AggregatePropertiesProvider
3. Minor cleanup in coding style
=> SCAN4NET-485 Add Provider Kind to IAnalysisPropertyProvider

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
[SCAN4NET-495](https://sonarsource.atlassian.net/browse/SCAN4NET-495)
We had at least two IT failures in MacOS and Linux because of a timeout in the builds recently:
https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=116948&view=logs&j=7d692771-62aa-5e24-bd85-b4dc8f6bca33&s=ffbece08-db33-5ffe-7537-8ad9d4bf6ce3&t=55d7b6d8-8660-5e3b-2c0a-f098d2482921&l=39061
https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=116948&view=logs&j=1267e320-60a8-5d9d-c934-b8464dbac3b7&s=821e3c99-8c09-5cb8-87e7-cf1391d9ddd1&t=5bce5501-070f-54f9-4cc4-53128a832b5a&l=38054
[SCAN4NET-495]: https://sonarsource.atlassian.net/browse/SCAN4NET-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-495 Increase timeout for whenAddingCoverage_ExclusionsAreRespected

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
[SCAN4NET-502](https://sonarsource.atlassian.net/browse/SCAN4NET-502)
Part of SCAN4NET-461
Caused by merging https://github.com/SonarSource/sonar-scanner-msbuild/pull/2518 without re-running CI from the latest master before merge.
[SCAN4NET-502]: https://sonarsource.atlassian.net/browse/SCAN4NET-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-502 Fix telemetry asserts

its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ServerTests.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
[SCAN4NET-616](https://sonarsource.atlassian.net/browse/SCAN4NET-616)
[SCAN4NET-616]: https://sonarsource.atlassian.net/browse/SCAN4NET-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-616 Fix telemetry ITs and set local sonar-dotnet analyzer version to be dev

Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs
[SCAN4NET-650](https://sonarsource.atlassian.net/browse/SCAN4NET-650)
Part of SCAN4NET-432
[SCAN4NET-650]: https://sonarsource.atlassian.net/browse/SCAN4NET-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
I added SCAN4NET-652 to track refactoring this class
=> SCAN4NET-650 Exclude windows specific tests from MSBuildPathSettingsTests

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Resources/ImportBeforeTargetTestsTemplate.xml, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/ImportBeforeTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/TargetsTestsContext.cs
[SCAN4NET-654](https://sonarsource.atlassian.net/browse/SCAN4NET-654)
Part of [SCAN4NET-387](https://sonarsource.atlassian.net/browse/SCAN4NET-387)
[SCAN4NET-387]: https://sonarsource.atlassian.net/browse/SCAN4NET-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-654]: https://sonarsource.atlassian.net/browse/SCAN4NET-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-654 Fix failing ImportBeforeTargetTests on Linux/MacOS

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarCategoriseProjectTests.cs
[SCAN4NET-664](https://sonarsource.atlassian.net/browse/SCAN4NET-664)
Part of SCAN4NET-387
Technically I think I could make all of these into one single DataTestMethod with large DataRows.
But I think keeping the test names is valuable and that would be messy.
[SCAN4NET-664]: https://sonarsource.atlassian.net/browse/SCAN4NET-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-664 Make SonarCategoriseProjectTests run on Linux

Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RoslynTargetsTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/TargetsTestsContext.cs
[SCAN4NET-657](https://sonarsource.atlassian.net/browse/SCAN4NET-657)
Part of [SCAN4NET-387](https://sonarsource.atlassian.net/browse/SCAN4NET-387)
[SCAN4NET-387]: https://sonarsource.atlassian.net/browse/SCAN4NET-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This is still WIP.
I did not finish migrating all the Windows path to Unix path.
[SCAN4NET-657]: https://sonarsource.atlassian.net/browse/SCAN4NET-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-657 Fix failing RoslynTargetsTests on Linux/MacOS

src/Directory.Build.props
[SCAN4NET-676](https://sonarsource.atlassian.net/browse/SCAN4NET-676)
For a better ubuntu debugging experience, the symbol file format needs to be changed to `portable`.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation
[SCAN4NET-676]: https://sonarsource.atlassian.net/browse/SCAN4NET-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-676 Change DebugType to portable

Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
[SCAN4NET-677](https://sonarsource.atlassian.net/browse/SCAN4NET-677)
[SCAN4NET-677]: https://sonarsource.atlassian.net/browse/SCAN4NET-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-677 Sensitive arguments are passed to the command line

Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
[SCAN4NET-689](https://sonarsource.atlassian.net/browse/SCAN4NET-689)
[SCAN4NET-689]: https://sonarsource.atlassian.net/browse/SCAN4NET-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-689 Fix failing UTs on Linux/MacOS in RoslynAnalyzerProviderTests.cs

Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
[SCAN4NET-686](https://sonarsource.atlassian.net/browse/SCAN4NET-686)
[SCAN4NET-686]: https://sonarsource.atlassian.net/browse/SCAN4NET-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-686 Fix failing UTs on Linux/MacOS in CacheProcessorTests.cs

Tests/SonarScanner.MSBuild.TFS.Test/TrxFileReaderTests.cs, src/SonarScanner.MSBuild.TFS/TrxFileReader.cs
[SCAN4NET-685](https://sonarsource.atlassian.net/browse/SCAN4NET-685)
Part of SCAN4NET-438
[SCAN4NET-685]: https://sonarsource.atlassian.net/browse/SCAN4NET-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-685 Fix failing UTs on Linux/MacOS in TrxFileReaderTests

Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
[SCAN4NET-690](https://sonarsource.atlassian.net/browse/SCAN4NET-690)
[SCAN4NET-690]: https://sonarsource.atlassian.net/browse/SCAN4NET-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-690 Fix failing UTs on Linux/MacOS in TargetsInstallerTests.cs

Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs
[SCAN4NET-652](https://sonarsource.atlassian.net/browse/SCAN4NET-652)
I wasn't able to condense many tests to Test similar behaviour, as they are mostly testing windows/linux specific behaviour.
[SCAN4NET-652]: https://sonarsource.atlassian.net/browse/SCAN4NET-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-652 Refactor tests in MsBuildPathSettingsTests

Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/FileCacheTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreCacheTests.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudJreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/utils/JreProvisioningAssertions.java, src/SonarScanner.MSBuild.PreProcessor/Caching/FileCache.cs, src/SonarScanner.MSBuild.PreProcessor/Caching/IFileCache.cs, src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreCache.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-742](https://sonarsource.atlassian.net/browse/SCAN4NET-742)
I wasn't 100% sure where i was headed, so I just commited every time I made a decision.
If the PR is hard to parse, review by commit and you will see my thought process.
I expect 2 more PRs before EngineResolver uses FileCache.
- Implement DownloadJreAsync equivalent in FileCache, and do minor rework of FileCacheTests 
- Make JreCache inherit directly from FileCache and mark a lot of members private/protected, delete IJreCache, and possible IFileCache.
[SCAN4NET-742]: https://sonarsource.atlassian.net/browse/SCAN4NET-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-742 Untangle UnpackJre from download logic in JreCache

Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/CoverageReportProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/ProgramTests.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java, scripts/package-artifacts.ps1, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.PostProcessor/Properties/AssemblyInfo.cs, src/SonarScanner.MSBuild.PostProcessor/Resources.Designer.cs, src/SonarScanner.MSBuild.PostProcessor/Resources.resx, src/SonarScanner.MSBuild.PostProcessor/SonarScanner.MSBuild.PostProcessor.csproj, src/SonarScanner.MSBuild.TFS.Classic/Program.cs, src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs, src/SonarScanner.MSBuild.TFS/CoverageReportProcessor.cs, src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
[SCAN4NET-705](https://sonarsource.atlassian.net/browse/SCAN4NET-705)
Can be reviewed per commit, if needed.
[SCAN4NET-705]: https://sonarsource.atlassian.net/browse/SCAN4NET-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-705 Rewrite PostProcessor.ProcessCoverageReport

Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
[SCAN4NET-706](https://sonarsource.atlassian.net/browse/SCAN4NET-706)
[SCAN4NET-706]: https://sonarsource.atlassian.net/browse/SCAN4NET-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-706 Append info about coverage files and trx files in GenerateAndValidatePropertiesFile

Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs, src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
[SCAN4NET-709](https://sonarsource.atlassian.net/browse/SCAN4NET-709)
[SCAN4NET-709]: https://sonarsource.atlassian.net/browse/SCAN4NET-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-709 Append the coverage file information to the PropertiesJson

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SlackNotification.yml, .github/workflows/SubmitReview.yml, .github/workflows/ToggleLockBranch.yml, .github/workflows/release.yml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
=> BUILD-8875: Migrate to standardized GitHub runner names

Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs, src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs, src/SonarScanner.MSBuild.PreProcessor/Caching/FileDescriptor.cs, src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs, src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDescriptor.cs, src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs, src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs, src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
[SCAN4NET-751](https://sonarsource.atlassian.net/browse/SCAN4NET-751)
based on #2668
I also renamed:
`FileCache` -> `CachingDownloader`
`JreCache` -> `JreDownloader`
`CacheResult` -> `FileResolution`
`CacheHit` -> `ResolutionSuccess`
`CacheMiss` -> `CacheMiss`
`CacheFailure` -> `ResolutionError`
next PR should break the refactor chain and be actual implementation.
[SCAN4NET-751]: https://sonarsource.atlassian.net/browse/SCAN4NET-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-751 Make JreDownloader and FileDownloader stateful

Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.TryWriteProperties.cs, Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs, src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs, src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-802](https://sonarsource.atlassian.net/browse/SCAN4NET-802)
In `ScannerEngineInput`, there's a ton of logic that depends on `ScannerEngineInputGenerator` that should be in `ScannerEngineInputGenerator`.
It's so duplicated, that it's not very visible on first sight. PR to deduplicate it will follow. This was meant to keep the code as much as-is as possible to make the review eas~~y~~ier
[SCAN4NET-802]: https://sonarsource.atlassian.net/browse/SCAN4NET-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-802 Untangle ScannerEngineInput and ScannerEngineInputGenerator

Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs, Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs, src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs, src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
[SCAN4NET-811](https://sonarsource.atlassian.net/browse/SCAN4NET-811)
[SCAN4NET-811]: https://sonarsource.atlassian.net/browse/SCAN4NET-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-811 Remove logger parameter from ProcessCoverageReports

Tests/SonarScanner.MSBuild.Common.Test/ProjectInfo/ProjectInfoExtensionsTests.cs, Tests/SonarScanner.MSBuild.Common.Test/ProjectInfoTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/ProjectLoaderTest.cs, Tests/TestUtilities/ProjectDescriptor.cs, Tests/TestUtilities/ProjectInfoAssertions.cs, src/SonarScanner.MSBuild.Common/ProjectInfo/AnalysisResult.cs, src/SonarScanner.MSBuild.Common/ProjectInfo/ProjectInfo.cs, src/SonarScanner.MSBuild.Common/ProjectInfo/ProjectInfoExtensions.cs, src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs, src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs, src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs, src/SonarScanner.MSBuild.Shim/SonarProjectPropertiesValidator.cs, src/SonarScanner.MSBuild.Tasks/WriteProjectInfoFile.cs
[SCAN4NET-826](https://sonarsource.atlassian.net/browse/SCAN4NET-826)
Part of SCAN4NET-821
Prerequisite for SCAN4NET-823 - this pre-cleans up files that will be touched later. There will be more PRs like this.
Review per commit is highly recommended, as each commit fixes the same thing in multiple files
[SCAN4NET-826]: https://sonarsource.atlassian.net/browse/SCAN4NET-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-826 AnalysisResult usages cleanup: Remove noise

Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/Unpacking/TarGzUnpackTests.cs, src/SonarScanner.MSBuild.PreProcessor/Unpacking/TarGzUnpacker.cs, src/SonarScanner.MSBuild.PreProcessor/Unpacking/UnpackerFactory.cs
[SCAN4NET-833](https://sonarsource.atlassian.net/browse/SCAN4NET-833)
Skip the first two commits for review. They are coming from #2746.
[SCAN4NET-833]: https://sonarsource.atlassian.net/browse/SCAN4NET-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-833 Use IRuntime in TarGzUnpacker

Tests/Directory.Build.targets, azure-pipelines.yml, src/Directory.Build.targets
[SCAN4NET-832](https://sonarsource.atlassian.net/browse/SCAN4NET-832)
Same as on `sonar-dotnet`
Local build in VS should not waste time running all analyzers. For standalone build, as well as for build before running UTs.
This keeps analyzers working in the IDE.
[SCAN4NET-832]: https://sonarsource.atlassian.net/browse/SCAN4NET-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-832 Disable analysis for dev build

Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs, Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs, src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs
[SCAN4NET-745](https://sonarsource.atlassian.net/browse/SCAN4NET-745)
[SCAN4NET-745]: https://sonarsource.atlassian.net/browse/SCAN4NET-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-745 "EnsureFileIsDownloaded" should attempt to re-download the file if the file in cache is invalid

Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/AnalysisConfigGenerator.cs, src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessor.cs
[SCAN4NET-869](https://sonarsource.atlassian.net/browse/SCAN4NET-869)
Skip first 5 commits when reviewing, they come from other branches.
[SCAN4NET-869]: https://sonarsource.atlassian.net/browse/SCAN4NET-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-869 Use IRuntime in TruststorePropertiesProcessor

Tests/SonarScanner.MSBuild.Shim.Test/SonarEngineWrapperTest.cs, Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs, Tests/TestUtilities/TestLogger.cs, src/SonarScanner.MSBuild.Shim/Resources.Designer.cs, src/SonarScanner.MSBuild.Shim/Resources.resx, src/SonarScanner.MSBuild.Shim/SonarEngineWrapper.cs
[SCAN4NET-837](https://sonarsource.atlassian.net/browse/SCAN4NET-837)
`We need the "Find java.exe like the batch/bash scripts" task next.`
[V5 ScannerCli .bat](https://github.com/SonarSource/sonar-scanner-cli/blob/5.0.2.4997/src/main/assembly/bin/sonar-scanner.bat)
The above script has 3 main logical steps for finding the java.exe:
- Check embedded java if `use_embedded_jre` 
- Check `JAVA_HOME` if `JAVA_HOME`
- fallback to the system `PATH`
from Martin regarding `use_embedded_jre` 
> The emebbed JRE is not relevant for us. It is used by the standalone scanner-cli only.
from Martin regarding the %PATH% fallback:
> Regarding the "PATH" fallback:
> I think it is the best to rely on the Process own logic. We set [UseShellExecute = false](https://github.com/SonarSource/sonar-scanner-msbuild/bl …
=> SCAN4NET-837 Find Java.exe in SonarEngineWrapper

Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarEngineWrapperTest.cs, Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs, Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildRunner.cs, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java, its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java, src/SonarScanner.MSBuild.Common/ProcessRunner.cs, src/SonarScanner.MSBuild.Common/ProcessRunnerArguments.cs, src/SonarScanner.MSBuild.Shim/SonarEngineWrapper.cs, src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs, src/SonarScanner.MSBuild.Shim/TFSProcessor.Wrapper.cs
[SCAN4NET-860](https://sonarsource.atlassian.net/browse/SCAN4NET-860)
TODO:
Follow up PR - Copy [SonarScannerWrapper](https://github.com/SonarSource/sonar-scanner-msbuild/blob/66618b506d3d951e7ca4ca00d9f86dba35b12e48/src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs#L178) in mapping from 
cli `sonar.scanner.truststorePassword` -> `-Djavax.net.ssl.trustStorePassword`
Should fix remaining tests:
selfSignedCertificateInGivenTrustStore
selfSignedCertificateInGivenTrustStore_PathAndPasswordWithSpace
defaultTruststoreExist_ProvidedPassword
truststorePasswordNotProvided_UseDefaultPassword
[SCAN4NET-860]: https://sonarsource.atlassian.net/browse/SCAN4NET-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCAN4NET-860 Scanner Engine: Fix Proxy ITs
