SonarSource/sonar-scanner-msbuild

- SonarRunner.Shim/PropertiesWriter.cs
- Tests/SonarRunner.Shim.Tests/PropertiesWriterTest.cs
Fixes http://jira.sonarsource.com/browse/SONARMSBRU-8
@duncanpMS Could you please review?
> SONARMSBRU-8 SCM provider (Git, TFVC) is not automatically detected

- SonarQube.Bootstrapper/ArgumentProcessor.cs
- SonarQube.Bootstrapper/Resources.Designer.cs
- SonarQube.Bootstrapper/Resources.resx
- SonarQube.Common/AnalysisProperties/CmdLineArgPropertyProvider.cs
- SonarQube.Common/Resources.Designer.cs
- SonarQube.Common/Resources.resx
- Tests/SonarQube.Bootstrapper.Tests/ArgumentProcessorTests.cs
- Tests/SonarQube.Bootstrapper.Tests/BootstrapperExeTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/ArgumentProcessorTests.cs
Updated code, comments and resource strings.
Added case to parser tests to check /p: is invalid
> SONARMSBRU-30: changed the property switch from /p: to /d:

- SonarQube.Bootstrapper/ArgumentProcessor.cs
- SonarQube.Common/AnalysisProperties/FilePropertyProvider.cs
- SonarQube.Common/SonarQube.Common.csproj
- SonarQube.TeamBuild.PreProcessor/ArgumentProcessor.cs
- Tests/SonarQube.Common.UnitTests/FilePropertyProviderTests.cs
- Tests/SonarQube.Common.UnitTests/SonarQube.Common.UnitTests.csproj
This pull request is for info. I'll merge it directly.
> [Technical] Renaming AnalysisPropertyFileProvider to FilePropertyProvider

- PackagingProjects/BuildAgentPayload/BuildAgentPayload.csproj
- SonarQube.Bootstrapper/SonarQube.Analysis.xml
- SonarQube.Bootstrapper/SonarQube.Bootstrapper.csproj
Sending PR for information only as the change is trivial. Committing this.
> SONARMSBRU-79: Add a template analysis file

- AssemblyInfo.Shared.cs
- SonarQube.TeamBuild.Integration/Properties/AssemblyInfo.cs
- SonarQube.TeamBuild.PostProcessor/Properties/AssemblyInfo.cs
- V0_9UpgradeMessageExe/V0_9UpgradeMessageExe.csproj
Fixed up exe names in AssemblyInfo.cs files following earlier renames
> [Technical] Changing version number to 1.0

- SonarQube.Common/AnalysisConfig/AnalysisConfig.cs
- SonarQube.Common/AnalysisProperties/IAnalysisPropertyProvider.cs
- SonarQube.TeamBuild.Integration/TeamBuildSettings.cs
- SonarQube.TeamBuild.PreProcessor/AnalysisConfigGenerator.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.TeamBuild.Integration.Tests/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/SummaryReportBuilderTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/AnalysisConfigGeneratorTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/PreprocessTestUtils.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
Re-arranged existing tests.
This is a pre-cursor to further work on SONARMSBRU-127 (don't write secrets to the config file)
> [Technical] Extracted analysis config creation code to separate class

- SonarQube.Common/Interfaces/ILogger.cs
- SonarQube.MSBuild.Tasks/IsTestFileByName.cs
- SonarQube.TeamBuild.PostProcessor/CoverageReportProcessor.cs
- SonarQube.TeamBuild.PostProcessor/Interfaces/ISummaryReportBuilder.cs
- SonarQube.TeamBuild.PostProcessor/MSBuildPostProcessor.cs
- SonarQube.TeamBuild.PostProcessor/Program.cs
- SonarQube.TeamBuild.PostProcessor/SonarQube.TeamBuild.PostProcessor.csproj
- SonarQube.TeamBuild.PostProcessor/SummaryReportBuilder.cs
- SonarQube.TeamBuild.PreProcessor/Program.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/SummaryReportBuilderTests.cs
- Tests/TestUtilities/TestLogger.cs
> [Technical] Refactored the post-processor to improve testability

- SonarQube.Common/AnalysisProperties/Property.cs
- SonarQube.Common/ProcessRunnerArguments.cs
- SonarQube.Common/ProjectInfo/ProjectInfoExtensions.cs
- SonarQube.TeamBuild.PostProcessor/ArgumentProcessor.cs
- SonarQube.TeamBuild.PostProcessor/Resources.Designer.cs
- SonarQube.TeamBuild.PostProcessor/Resources.resx
- SonarQube.TeamBuild.PostProcessor/SonarQube.TeamBuild.PostProcessor.csproj
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/ArgumentProcessorTests.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/SonarQube.TeamBuild.PostProcessor.Tests.csproj
TODO: change the post-processor to use the argument processor
> [SONARMSBRU-127] Added argument processor for the post-processor

- Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- Tests/SonarQube.MSBuild.Tasks.IntegrationTests/E2ETests/E2EFxCopTests.cs
- Tests/SonarQube.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs
- Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs
- Tests/SonarRunner.Shim.Tests/ProjectLoaderTest.cs
- Tests/TestUtilities/ProjectDescriptor.cs
No product changes.
No changes to the test cases.
> [Technical] Tidied up MSBuild tests

- SonarQube.Common/ProcessRunnerArguments.cs
- Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/ArgumentProcessorTests.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/AnalysisConfigGeneratorTests.cs
- Tests/SonarRunner.Shim.Tests/PropertiesFileGeneratorTests.cs
- Tests/SonarRunner.Shim.Tests/SonarRunnerWrapperTests.cs
Required to make v1.0.1 backwards-compatible with v1.0
> [SONARMSBRU-137] Allowed sensitive data to be written to files

- SonarQube.TeamBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- SonarQube.TeamBuild.PreProcessor/Resources.Designer.cs
- SonarQube.TeamBuild.PreProcessor/Resources.resx
- SonarQube.TeamBuild.PreProcessor/SonarLintAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/SonarWebService.cs
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/DataModel/QualityProfile.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/DataModel/ServerDataModel.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServer.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarLintAnalyzerProviderTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
Added tests
This implementation uses the new profile export that was added in C# plugin 4.3.
> [SONARMSBRU-163] Amended pre-processor to download SonarLint ruleset

- SonarQube.TeamBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- SonarQube.TeamBuild.PreProcessor/Interfaces/ISonarQubeServerFactory.cs
- SonarQube.TeamBuild.PreProcessor/SonarQubeServerFactory.cs
- SonarQube.TeamBuild.PreProcessor/SonarWebService.cs
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServer.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServerFactory.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarWebServiceTest.cs
Removed the logger method parameter from the interface.
Fixed up tests.
> [Technical] Minor cleanup of ISonarQubeServer interface

- SonarQube.TeamBuild.PreProcessor/Interfaces/IDownloader.cs
- SonarQube.TeamBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- SonarQube.TeamBuild.PreProcessor/Resources.Designer.cs
- SonarQube.TeamBuild.PreProcessor/Resources.resx
- SonarQube.TeamBuild.PreProcessor/SonarLintAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/SonarWebService.cs
- SonarQube.TeamBuild.PreProcessor/WebClientDownloader.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/DataModel/ServerDataModel.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServer.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServerFactory.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarLintAnalyzerProviderTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarWebServiceTest.cs
Added unit tests
TODO: update the targets files to use the downloaded analyser
> [SONARMSBRU-171] Added download of SonarLint.zip from server

- SonarRunner.Shim/Resources.Designer.cs
- SonarRunner.Shim/Resources.resx
- SonarRunner.Shim/RoslynV1SarifFixer.cs
Added extra logging statements
> [SONARMSBRU-177] Fixed error in log message (missing parameter)

- SonarQube.MSBuild.Tasks/MergeRulesets.cs
- Tests/SonarQube.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/MergeRuleSetsTests.cs
- Tests/TestUtilities/RulesetAssertions.cs
> [SONARMSBRU-201] Change ruleset Include action to "Warning"

- SonarQube.TeamBuild.PreProcessor/Interfaces/IAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/Program.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockRoslynAnalyzerProvider.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorExeTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
Amended the pre-processor to call the analyzer provider (WIP)
> [Technical] Added interface for the Roslyn analyzer provider

- SonarQube.Common/AnalysisConfig/AnalysisConfig.cs
- SonarQube.Common/AnalysisConfig/AnalyzerSettings.cs
- SonarQube.Common/SonarQube.Common.csproj
- SonarQube.TeamBuild.PreProcessor/Interfaces/IAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.Common.UnitTests/AnalysisConfigTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockRoslynAnalyzerProvider.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs
Renamed to AnalyzerSettings
Added to AnalysisConfig and added serialization tests
> [SONARMSBRU-207] Move analyzer config data class to Common

- SonarQube.MSBuild.Tasks/IsTestFileByName.cs
- SonarQube.MSBuild.Tasks/Resources.Designer.cs
- SonarQube.MSBuild.Tasks/Resources.resx
- SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj
- SonarQube.MSBuild.Tasks/TaskUtilities.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/IsTestFileByNameTests.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/SonarQube.MSBuild.Tasks.UnitTests.csproj
- Tests/SonarQube.MSBuild.Tasks.UnitTests/TaskUtilitiesTests.cs
Fixed up unit tests
The new build task will need to load the analysis config too, so I factored the code out into a shared location.
> [Technical] Refactored shared task code into common class

- SonarQube.MSBuild.Tasks/GetAnalyzerSettings.cs
- SonarQube.MSBuild.Tasks/Resources.Designer.cs
- SonarQube.MSBuild.Tasks/Resources.resx
- SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj
- Tests/SonarQube.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/SonarQube.MSBuild.Tasks.UnitTests.csproj
> [SONARMSBR-207] Added build task to fetch analyzer settings from config

- SonarQube.TeamBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/EmbeddedAnalyzerInstaller.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/Model/Plugin.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynResources.Designer.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynResources.resx
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/EmbeddedAnalyzerInstallerTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
Added another analyser installer implementation that downloads and unzips embedded files from the SonarQube server using the same mechanism as the old SonarLintAnalyzerProvider.
> [SONARMSBRU-212] Added the embedded analyzer installer

- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs
My mistake: I push the original changes before committing these alterations that I referred to in the comments for the previous commit. I'm creating this as a PR just to trigger an AppVeyor run.
> [SONARMSBRU-212] Code review changes

- Tests/SonarQube.Common.UnitTests/ProcessRunnerTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/SampleExportXml.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/RoslynExportProfileTests.cs
Minor changes to two unit tests
> [Technical] changes to unit tests

- SonarQube.TeamBuild.PreProcessor/PreprocessorObjectFactory.cs
- SonarQube.TeamBuild.PreProcessor/Resources.Designer.cs
- SonarQube.TeamBuild.PreProcessor/Resources.resx
- SonarQube.TeamBuild.PreProcessor/Roslyn/EmbeddedAnalyzerInstaller.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynResources.Designer.cs
- SonarQube.TeamBuild.PreProcessor/Roslyn/RoslynResources.resx
- SonarQube.TeamBuild.PreProcessor/WebClientDownloader.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/EmbeddedAnalyzerInstallerTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/WebClientDownloaderTest.cs
> [SONARMSBRU-212] Made caching check more robust

- SonarQube.TeamBuild.PreProcessor/BuildWrapperInstaller.cs
- SonarQube.TeamBuild.PreProcessor/Interfaces/IBuildWrapperInstaller.cs
- SonarQube.TeamBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs
- SonarQube.TeamBuild.PreProcessor/PreprocessorObjectFactory.cs
- SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- SonarQube.TeamBuild.PreProcessor/TeamBuildPreProcessor.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockBuildWrapperInstaller.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/Infrastructure/MockObjectFactory.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/PreProcessorTests.cs
- Tests/SonarQube.TeamBuild.PreProcessor.Tests/SonarQube.TeamBuild.PreProcessor.Tests.csproj
This commit just modifies the orchestration code in the preprocessor; the build wrapper implementation is currently empty (done to keep the make the changes easier to review)
> [SONARMSBRU-238] Modified preprocessor to call the build wrapper installer

- SonarQube.MSBuild.Tasks/AttachBuildWrapper.cs
- SonarQube.MSBuild.Tasks/Resources.Designer.cs
- SonarQube.MSBuild.Tasks/Resources.resx
- SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj
- Tests/SonarQube.MSBuild.Tasks.UnitTests/AttachBuildWrapperTests.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/SonarQube.MSBuild.Tasks.UnitTests.csproj
- Tests/TestUtilities/DummyExeHelper.cs
- Tests/TestUtilities/EmbeddedCode/DummyExe.cs
Added task to attach the C++ build wrapper
Added unit tests
TODO: we haven't yet finalised the mechanism used to decide whether the build wrapper is already attached. I've implemented the approach we originally discussed by not written tests for it.
> [SONARMSBRU-237] Added C++ build wrapper task

- SonarQube.TeamBuild.PostProcessor/Resources.Designer.cs
- SonarQube.TeamBuild.PostProcessor/Resources.resx
https://jira.sonarsource.com/browse/SONARMSBRU-234
> SONARMSBRU-234: Remove styling from the summary md report

- SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets
- its/projects/AssemblyAttribute/ConsoleApp2017.sln
- its/projects/AssemblyAttribute/ConsoleApp2017/App.config
- its/projects/AssemblyAttribute/ConsoleApp2017/ConsoleApp2017.csproj
- its/projects/AssemblyAttribute/ConsoleApp2017/Program.cs
- its/projects/AssemblyAttribute/ConsoleApp2017/Properties/AssemblyInfo.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
> SONARMSBRU-159, SONARMSBRU-199 Exclude generated AssemblyAttributes from

- SonarQube.MSBuild.Tasks/Targets/SonarQube.Integration.targets
- SonarQube.MSBuild.Tasks/WriteProjectInfoFile.cs
- Tests/SonarQube.MSBuild.Tasks.UnitTests/WriteProjectInfoFileTests.cs
Use the Guid in the solution if available
> SONARMSBRU-167 Support projects with no ProjectGuid

- SonarQube.MSBuild.Tasks/IsTestFileByName.cs
Removed the word 'is' which was redundant
> Fixed a typo in the xml documentation

- SonarScanner.Shim/PropertiesFileGenerator.cs
- SonarScanner.Shim/Resources.Designer.cs
- SonarScanner.Shim/Resources.resx
- Tests/SonarScanner.Shim.Tests/PropertiesFileGeneratorTests.cs
- its/projects/CSharpSharedFileWithOneProject/CSharpSharedFileWithOneProject.sln
- its/projects/CSharpSharedFileWithOneProject/ClassLib1/Class1.cs
- its/projects/CSharpSharedFileWithOneProject/ClassLib1/ClassLib1.csproj
- its/projects/CSharpSharedFileWithOneProject/ClassLib1/Properties/AssemblyInfo.cs
- its/projects/CSharpSharedFileWithOneProject/Common.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
SONARMSBRU-333: SONARMSBRU-334: Handle correctly /d:sonar.projectBaseDir
SONARMSBRU-362: sonar.projectBaseDir should handle relative paths and short paths
> Multiple tickets related to /d:sonar.projectBaseDir

- SonarScanner.Shim/PropertiesFileGenerator.cs
Not sure how to write a test for that because it should be executed on non-Windows OS to fail
> SONARMSBRU-365 Fix cross-platform path check

- src/SonarQube.Common/SonarQube.Common.csproj
- src/SonarQube.TeamBuild.Integration.XamlBuild/SonarQube.TeamBuild.Integration.XamlBuild.csproj
- src/SonarQube.TeamBuild.Integration/SonarQube.TeamBuild.Integration.csproj
- src/SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- src/SonarQube.TeamBuild.PreProcessor/SonarWebService.cs
- src/SonarScanner.Shim/SonarScanner.Shim.csproj
Required for targetting Core/Standard.
> Update json to 10.0.3

- Tests/SonarQube.Common.UnitTests/MutexWrapperTests.cs
- Tests/SonarQube.Common.UnitTests/SonarQube.Common.UnitTests.csproj
- src/SonarQube.Common/MutexWrapper.cs
- src/SonarQube.TeamBuild.PreProcessor/Roslyn/PluginResourceCache.cs
SONARMSBRU-373: Change synchronization mechanism
> Use mutex instead of EventWaitHandle

- Tests/SonarScanner.Shim.Tests/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.Shim.Tests/PropertiesWriterTest.cs
- Tests/SonarScanner.Shim.Tests/SonarScanner.Shim.Tests.csproj
- src/SonarQube.Common/FileInfoEqualityComparer.cs
- src/SonarQube.Common/ProjectInfo/ProjectInfoExtensions.cs
- src/SonarQube.MSBuild.Tasks/GetAnalyzerSettings.cs
- src/SonarScanner.Shim/PathHelper.cs
- src/SonarScanner.Shim/ProjectData.cs
- src/SonarScanner.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.Shim/PropertiesWriter.cs
- src/SonarScanner.Shim/Resources.Designer.cs
- src/SonarScanner.Shim/Resources.resx
- src/SonarScanner.Shim/SonarProjectPropertiesValidator.cs
- tests/SonarScanner.Shim.Tests/PathHelperTests.cs
Fix [SONARMSBRU-375](https://jira.sonarsource.com/browse/SONARMSBRU-375)
> SONARMSBRU-375: Ensure all path comparisons within the scanner are done using OS-specific case and separator sensitivity

- src/Directory.Build.props
- src/SonarQube.Bootstrapper/SonarQube.Bootstrapper.csproj
- src/SonarQube.Common/SonarQube.Common.csproj
- src/SonarQube.MSBuild.Tasks/SonarQube.MSBuild.Tasks.csproj
- src/SonarQube.Old.Bootstrapper/SonarQube.Old.Bootstrapper.csproj
- src/SonarQube.TeamBuild.Integration.Classic/SonarQube.TeamBuild.Integration.Classic.csproj
- src/SonarQube.TeamBuild.Integration/SonarQube.TeamBuild.Integration.csproj
- src/SonarQube.TeamBuild.PostProcessor/SonarQube.TeamBuild.PostProcessor.csproj
- src/SonarQube.TeamBuild.PreProcessor/SonarQube.TeamBuild.PreProcessor.csproj
- src/SonarScanner.Shim/SonarScanner.Shim.csproj
Allows the target frameworks to target can be set in a single place
> Added properties in Directory.Build.props for target frameworks

- Tests/SonarQube.Bootstrapper.Tests/BootstrapperClassTests.cs
- Tests/SonarQube.TeamBuild.Integration.Tests/CoverageReportProcessorTests.cs
- Tests/SonarQube.TeamBuild.Integration.Tests/SonarQube.TeamBuild.Integration.Tests.csproj
- Tests/SonarQube.TeamBuild.Integration.Tests/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/Infrastructure/MockCodeCoverageProcessor.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/Infrastructure/MockSummaryReportBuilder.cs
- Tests/SonarQube.TeamBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs
- src/SonarQube.Bootstrapper/BootstrapperClass.cs
- src/SonarQube.Bootstrapper/DefaultProcessorFactory.cs
- src/SonarQube.TeamBuild.Integration.XamlBuild/LegacyTeamBuildFactory.cs
- src/SonarQube.TeamBuild.Integration.XamlBuild/TfsLegacyCoverageReportLocator.cs
- src/SonarQube.TeamBuild.Integration/CoverageReportProcessor.cs
- src/SonarQube.TeamBuild.Integration/Interfaces/ICoverageReportLocator.cs
- src/SonarQube.TeamBuild.Integration/Interfaces/ICoverageReportProcessor.cs
- src/SonarQube.TeamBuild.Integration/Interfaces/ICoverageReportProcessorFactory.cs
- src/SonarQube.TeamBuild.Integration/Interfaces/ILegacyTeamBuildFactory.cs
- src/SonarQube.TeamBuild.Integration/Interfaces/ITeamBuildSettings.cs
- src/SonarQube.TeamBuild.Integration/NotSupportedLegacyTeamBuildFactory.cs
- src/SonarQube.TeamBuild.Integration/TeamBuildSettings.cs
- src/SonarQube.TeamBuild.Integration/TfsCoverageReportLocator.cs
- src/SonarQube.TeamBuild.PostProcessor/CoverageReportProcessorFactory.cs
- src/SonarQube.TeamBuild.PostProcessor/Interfaces/IMSBuildPostProcessor.cs
- src/SonarQube.TeamBuild.PostProcessor/MSBuildPostProcessor.cs
- src/SonarQube.TeamBuild.PostProcessor/SummaryReportBuilder.cs
This is just a small refactoring to enable easier testing for CoverageReportProcessor
> Improving testability, adding tests for CoverageReportProcessor

- src/SonarQube.TeamBuild.PostProcessor/Resources.Designer.cs
- src/SonarQube.TeamBuild.PostProcessor/Resources.resx
- src/SonarQube.TeamBuild.PostProcessor/SonarQube.TeamBuild.PostProcessor.csproj
- src/SonarQube.TeamBuild.PostProcessor/SummaryReportBuilder.cs
TODO: agree the wording of the message, and that it should appear in the build summary
> Added warning that XAML builds are deprecated

- build/build.ps1
- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
- pom.xml
- src/PackagingProjects/BuildAgentPayload.csproj
> Publish dotnet framework and dotnet core scanners in two separate artifacts

- Tests/SonarScanner.MSBuild.PostProcessor.Tests/SummaryReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.PostProcessor/SummaryReportBuilder.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoValidity.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
> Ignore projects with duplicate Guids

- src/Packaging/Directory.Build.props
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Embed Scanner Cli 3.1.0

- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Add user extension point for ItemGroup target types

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/WebClientDownloaderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Make sure UserAgent is always sent, not only on first request

- src/Packaging/Directory.Build.props
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Scanner should not suggest to use -X

- src/Packaging/Directory.Build.targets
> Digitally sign binaries to not be blacklisted by antivirus

- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
> Changing error message when version of MSBuild is not supported

- src/Packaging/Directory.Build.targets
> Update hashing algorithm used to sign binaries

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
> Break the build when running under local system account

- its/pom.xml
Update orchestrator to a version compatible with SQ 6.7.5
> Fix ITs against SQ LTS 6.7.5

- its/src/test/java/com/sonar/it/scanner/msbuild/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/SQLServerTest.java
* speeds up the ITs because only one edition of SQ needs to be downloaded
> Standardise ITs to all use SQ Developer edition

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
- src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
- src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs
- src/SonarScanner.MSBuild.Tasks/Resources.resx
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Change merged ruleset output location to "conf"
> Added more logging to GetAnalyzerSettings

- Tests/SonarScanner.MSBuild.Common.UnitTests/AnalysisConfig/AnalysisConfigExtensionsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildLogAssertions.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/SimpleXmlLogger.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
- Tests/TestUtilities/RulesetAssertions.cs
- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfigExtensions.cs
- src/SonarScanner.MSBuild.Common/AnalysisConfig/Include.cs
- src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
- src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs
- src/SonarScanner.MSBuild.Tasks/Resources.resx
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
- tests/SonarScanner.MSBuild.Tasks.Integrationtests/MSBuildExecution/BuildLog.cs
> Added support for third-party Roslyn analyzers

- scripts/build/ci-build.ps1
The build script is totally outdated compared to C#. Making change is impossible, let's revert.
> Revert analyzing to SonarCloud

- Tests/SonarScanner.MSBuild.Common.UnitTests/MsBuildPathSettingsTests.cs
- Tests/SonarScanner.MSBuild.Common.UnitTests/SonarScanner.MSBuild.Common.UnitTests.csproj
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
> Fail scanner when environment special folders return empty string

- scripts/build/ci-build.ps1
Move the analysis of our source code from Next to SonarCloud.
> Analyze code on SonarCloud

- Tests/SonarScanner.MSBuild.Common.UnitTests/MsBuildPathSettingsTests.cs
- Tests/SonarScanner.MSBuild.Common.UnitTests/SonarScanner.MSBuild.Common.UnitTests.csproj
- Tests/SonarScanner.MSBuild.Common.UnitTests/StringExtensions_ReplaceCaseInsensitive.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
- src/SonarScanner.MSBuild.Common/StringExtensions.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
> Support analysis when running as System Account

- Tests/SonarScanner.MSBuild.TFS.Tests/Classic/TfsLegacyCoverageReportProcessorTests.cs
- src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs
> Don't override coverage and unit test report settings

- Tests/SonarScanner.MSBuild.Common.UnitTests/MsBuildPathSettingsTests.cs
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
> Fix the check for AppData existence by using Directory.Exists instead of File.Exists

- Tests/SonarScanner.MSBuild.TFS.Tests/Classic/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Tests/TrxFileReaderTests.cs
- src/SonarScanner.MSBuild.TFS.Classic/XamlBuild/TfsLegacyCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs
- src/SonarScanner.MSBuild.TFS/Resources.Designer.cs
- src/SonarScanner.MSBuild.TFS/Resources.resx
- src/SonarScanner.MSBuild.TFS/TrxFileReader.cs
Fix #560 
This PR requires more manual tests with TFS and VSTS.
> Allow multiple trx/coverage files from TFS/VSTS

- Tests/SonarScanner.MSBuild.Common.UnitTests/FilePropertyProviderTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Tests/MSBuildPostProcessorTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Tests/SummaryReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/ProjectLoaderTest.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/SonarScannerWrapperTests.cs
- Tests/SonarScanner.MSBuild.TFS.Tests/Classic/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Tests/TrxFileReaderTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/ImportBeforeTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
- Tests/TestUtilities/TestUtils.cs
- src/SonarScanner.MSBuild.Common/IO/DirectoryWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/FileWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IDirectoryWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IFileWrapper.cs
- src/SonarScanner.MSBuild.Common/UniqueDirectory.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
- src/SonarScanner.MSBuild.TFS/TrxFileReader.cs
- src/SonarScanner.MSBuild.Tasks/MakeUniqueDir.cs
> Refactor the TrxFileReader to use IDirectory/IFile

- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
Fixed #568 
Manually smoke-tested the scanner containing the new version of the CLI.
> Updated scanner cli to version 3.3.0.1492

- src/SonarScanner.MSBuild.PostProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PostProcessor/Resources.resx
- src/SonarScanner.MSBuild.PostProcessor/SummaryReportBuilder.cs
> Remove dashboard link

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
> Do not fail analysis when targets files are unexpectedly copied by and other concurrent analysis

- Tests/SonarScanner.MSBuild.PostProcessor.Tests/SummaryReportBuilderTests.cs
- src/SonarScanner.MSBuild.PostProcessor/SummaryReportBuilder.cs
> [#529] Drop generation of summary.md file for VSTS builds

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/BuildUtilities.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/SonarScanner.MSBuild.Tasks.IntegrationTests.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarQubeCategoriseProjectTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> [#651] Fixed recognition of test projects

- Tests/SonarScanner.MSBuild.Common.UnitTests/AnalysisConfig/AnalyzerSettingsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynRuleSetGeneratorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalyzerSettings.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IAnalyzerProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynRuleSetGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynSonarLint.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RuleAction.cs
> Generate an additional ruleset that disables all rules except utility rules

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs
- src/SonarScanner.MSBuild.Tasks/Resources.resx
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
- src/SonarScanner.MSBuild.Tasks/WriteZeroLengthFiles.cs
> Changed targets to execute analyzers on test projects

- Tests/SonarScanner.MSBuild.Common.UnitTests/MsBuildPathSettingsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Add support for MSBuild 16.0 / NET Core SDK 3.0

- Tests/SonarScanner.MSBuild.Common.UnitTests/ConsoleLoggerTests.cs
- src/SonarScanner.MSBuild.Common/ConsoleLogger.cs
- src/SonarScanner.MSBuild.PostProcessor/MSBuildPostProcessor.cs
- src/SonarScanner.MSBuild.PostProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PostProcessor/Resources.resx
- src/SonarScanner.MSBuild.PostProcessor/TargetsUninstaller.cs
Two commits:
* the first adds debug messages to the target uninstaller
* the second fixes a bug in the logger that prevented the debug messages from appearing.
> [Do not squash] Added debug logging and fixed logging bug

- pom.xml
> Update the version of the parent pom

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
> Set bug-fix version to 4.6.1

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/BuildRunner.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/MSBuildExecution/MSBuildLocator.cs
> Change MSBuildLocator to handle VS2019

- README.md
- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
Following https://jira.sonarsource.com/browse/SC-724
> Updated README.md & sonarscanner-for-msbuild.md

- its/src/test/java/com/sonar/it/scanner/msbuild/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/VBNetTest.java
Added logging of actual measures in asserts.
> De-duped code in ITs.

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/WriteProjectInfoFileTargetTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Added Page and ApplicationDefinition in the targets file
Updated Unit Tests.
Fixes #746
> (#746) Include XAML files on default item types.

- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
> Changed the MSBuild version supported in possible cause of failure message

- Tests/SonarScanner.MSBuild.Common.UnitTests/CommandLine/CommandLineFlagPrefixTests.cs
- Tests/SonarScanner.MSBuild.Common.UnitTests/SonarScanner.MSBuild.Common.UnitTests.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.Tests/ArgumentProcessorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/CmdLineArgPropertyProvider.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/FilePropertyProvider.cs
- src/SonarScanner.MSBuild.Common/CommandLine/CommandLineFlagPrefix.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild/ArgumentProcessor.cs
> Added support for dashed arguments

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
> Fix test failure due to change in targets files

- Tests/SonarScanner.MSBuild.Common.UnitTests/AnalysisProperties/ListPropertiesProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/Infrastructure/MockRoslynAnalyzerProvider.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/PreProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynAnalyzerProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/RoslynRuleSetGeneratorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/ListSettingsProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IAnalyzerProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynRuleSetGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynSonarLint.cs
- src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
Fixes the argument processing logic so that local arguments are merged with server settings when generating SonarLint.xml
Relates to #699
> Fix input argument processing for SonarLint.xml

- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/SonarScanner.MSBuild.Shim.Tests.csproj
- Tests/SonarScanner.MSBuild.Shim.Tests/packages.config
- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/RuntimeInformationWrapper.cs
- src/SonarScanner.MSBuild.Shim/SonarScanner.MSBuild.Shim.csproj
- src/SonarScanner.MSBuild.Tasks/SonarScanner.MSBuild.Tasks.csproj
> Add case-insensitive comparison for paths in ProjectInfo.xml files

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
> Fixed organization argument name on documentation.

- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Update Scanner CLI 4.1.0.1829

- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Bumped Scanner CLI to version 4.2.0.1873

- pom.xml
Previous version was failing recently, updated it to 53.
> Update POM parent version

- azure-pipelines.yml
- nuspec/chocolatey/chocolateyInstall-net46.ps1
- nuspec/chocolatey/chocolateyInstall-netcoreapp2.0.ps1
- nuspec/chocolatey/chocolateyInstall-netcoreapp3.0.ps1
https://github.com/SonarSource/sonar-scanner-msbuild/pull/817
> [Cherry-pick external] Use fixed version number in Chocolatey package 

- azure-pipelines.yml
- its/pom.xml
- its/projects/CppSharedFiles/Project1/Project1.vcxproj
- its/projects/CppSharedFiles/Project2/Project2.vcxproj
- its/projects/CppSolution/ConsoleApp/ConsoleApp.vcxproj
- its/src/test/java/com/sonar/it/scanner/SonarScannerTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ProxyAuthenticator.java
- its/src/test/java/com/sonar/it/scanner/msbuild/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/VstsUtils.java
- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Bumped ScannerCLI to version 4.3.0.2102

- src/Packaging/Packaging.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
…he scanner name and version.
fixes #871
> Changed embedded flag to from for invocation of ScannerCLI

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/ProcessedArgsTests.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
> Fail fast if sonar.organization is provided in SonarQube.Analysis.xml

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/Infrastructure/MockSonarQubeServer.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/SonarWebServiceTest.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
- src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Fail fast in case of invalid license (or unlicensed) SonarQube instance.

- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
> fixed bug - skipped shared across projects files

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Fix error parsing for license check

- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
same PR as #923 but different target branch
> #917 merge to mc/917

- AssemblyInfo.Shared.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/SonarWebServiceTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/WebClientDownloaderTest.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
- src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
fixes #917 
Co-authored-by: Jan Nielsen <ext-jan.nielsen@eurowag.com>
> Fix license check

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarQubeCategoriseProjectTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Add clarification message to test project detection

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/SonarQubeCategoriseProjectTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/IsTestFileByNameTests.cs
- src/SonarScanner.MSBuild.Tasks/IsTestFileByName.cs
- src/SonarScanner.MSBuild.Tasks/Resources.Designer.cs
- src/SonarScanner.MSBuild.Tasks/Resources.resx
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Don't inspect project name in test project detection by default

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Resources/CaptureDataTargetsFileTemplate.xml
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/SonarScanner.MSBuild.Tasks.UnitTests.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/WriteProjectConfigFileTests.cs
- src/SonarScanner.MSBuild.Common/FileConstants.cs
- src/SonarScanner.MSBuild.Common/ProjectInfo/ProjectInfo.cs
- src/SonarScanner.MSBuild.Tasks/ProjectConfig.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
- src/SonarScanner.MSBuild.Tasks/WriteProjectConfigFile.cs
Fixes #959
Rebase will be needed after merge of #960
First commit `Move FilesToAnalyze to CONF directory and write it immediately` doesn't need a review.
Review per commit is suggested to follow the steps.
> Pass configuration to analyzers

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/SonarScanner.MSBuild.Tasks.IntegrationTests.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/app.config
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/packages.config
> Update MSBuild package refs to fix failing CI build

- its/pom.xml
- pom.xml
> Update orchestrator to 3.35.1.2719

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTests/GetAnalyzerSettingsTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Fixes #980
This is the final step after preparation PRs #984 and #985
> Analyze Test code

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
Related to #976
We'll need to update SQ and SC repos afterwards.
> Document sonar.dotnet.excludeTestProjects

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
I'm not sure if `master` is the correct branch to target.
This is my attempt to align all 3 documents as they are out of sync. I don't know full history of all 3 documents, please point out any changes that shouldn't have been done.
Same thing will happen on SQ and SC repo.
I imported changes present on SC. And then from SQ.
I fixed few glitches like `/d:sonar.login=` begin excluded from SQ
> Align Docs with SC and SQ

- scripts/variables.ps1
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Update SonarScanner CLI to 4.6.1.2450

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
Fixing formatting issues on the SQ docs due to the SC tag. https://jira.sonarsource.com/browse/SONAR-14814
> SONAR-14814 SonarScanner NET docs formatting issue

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
Updated documentation to account for the Microsoft.NET.Sdk project format that includes all files by default. Closes #1027
> Updated documentation text for analyzing languages other than C# and VB

- Tests/SonarScanner.MSBuild.Shim.Tests/MockRoslynV1SarifFixer.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Tests/PropertiesWriterTest.cs
- Tests/TestUtilities/SQPropertiesFileReader.cs
- Tests/TestUtilities/TestUtils.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
> Remove duplicated properties from `sonar-project.properties`

- Tests/SonarScanner.MSBuild.PreProcessor.Tests/PreProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Tests/SonarWebServiceTest.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
- src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Fix bug in WS error handling: ArgumentNullException

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Hi !
Small change to output FilesToAnalyze.txt as UTF8
Fixes #1037
> Use Utf8 instead of Unicode for FilesToAnalyze.txt

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/Resources/CaptureDataTargetsFileTemplate.xml
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RazorTargetTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Fixes #1020
Will also fix #1003 once the consecutive release will be analyzed with S4NET 5.3
> Move Sarif reports to out directory

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/SonarScanner.MSBuild.Tasks.IntegrationTests.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RazorTargetTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/RoslynTargetsTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
Fixes #1015
This is draft to prevent merging, rebase will be needed after #1049 is merged. `Squash Pavel/MoveSarif` commit doesn't need a review for the same reason.
> Targets file doesn't pick up explicit ErrorLog value

- its/projects/CSharp.SDK.2.1/AspNetCoreMvc/Views/Home/Index.cshtml
- its/projects/CSharp.SDK.3.1/AspNetCoreMvc/Views/Home/Index.cshtml
- its/projects/CSharp.SDK.5/AspNetCoreMvc/Views/Home/Index.cshtml
- its/projects/CSharp.SDK.Latest/AspNetCoreMvc/Views/Home/Index.cshtml
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
> Document behaviour of importing external issues from cshtml.

- scripts/variables.ps1
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Update scanner-cli to 4.6.2.2472

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTests/TargetsTests/ImportBeforeTargetsTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.ImportBefore.targets
> 5.3.0 removes msbuild targets, but leaves projects configured to use sonarqube analysis

- SonarScanner.MSBuild.sln
- azure-pipelines.yml
I've also added Scanner booms to LT wallboard
> Schedule nightly builds

- azure-pipelines.yml
- scripts/whitesource/WhiteSource-Scan.ps1
- scripts/whitesource/wss-unified-agent.config
Successful WhiteSource scan: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=39809&view=results
> Implement WhiteSource scan

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/SonarScannerTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ProxyAuthenticator.java
- its/src/test/java/com/sonar/it/scanner/msbuild/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/VstsUtils.java
Contributes to #1104 
Align Java license headers with C#.
> Update Java license headers

- .editorconfig
- StyleCopAnalyzers.targets
- Tests/Directory.Build.targets
- Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs
- src/Directory.Build.targets
- stylecop.json
Fixes #1105
Coding style is already documented https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/CONTRIBUTING.md#pull-request-pr
> Configure coding style rules

- src/SonarScanner.MSBuild.Common/SonarScanner.MSBuild.Common.csproj
- src/SonarScanner.MSBuild.PreProcessor/SonarScanner.MSBuild.PreProcessor.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.MSBuild.Shim.csproj
- src/SonarScanner.MSBuild.TFS.Classic/SonarScanner.MSBuild.TFS.Classic.csproj
- src/SonarScanner.MSBuild/SonarScanner.MSBuild.csproj
> Bump Newtonsoft.Json to 13.0.1

- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Change supported TLS protocol versions to SystemDefault

- Tests/SonarScanner.MSBuild.Common.Test/AggregatePropertiesProviderTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/CmdLineArgsPropertiesProviderTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/CommandLine/CommandLineParserTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/FilePropertyProviderTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/Classic/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/TrxFileReaderTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarCategoriseProjectTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarResolveReferencesTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/WriteProjectInfoFileTargetTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/IsTestFileByNameTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/TaskUtilitiesTests.cs
> Remove TestCategory attributes from UTs

- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
> Ignore flaky test

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
- Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs
> Re-enable and fix some of the ignored UTs

- Tests/SonarScanner.MSBuild.TFS.Test/ProgramTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildLog.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildRunner.cs
- Tests/SonarScanner.MSBuild.Test/ProgramTests.cs
- azure-pipelines-external.yml
- azure-pipelines.yml
> Change the pipeline to use .Net Bubble - GCP image

- azure-pipelines.yml
> Disable Dev version of ITs

- azure-pipelines.yml
> Adds integartion tests with latest SQ LTS and VS 2022

- azure-pipelines.yml
> Enable ITs targeting DEV version of SQ

- scripts/whitesource/WhiteSource-Scan.ps1
> Add retry mechanism for whitesource download

- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Remove TLS 1.3 for older runtimes

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RazorTargetTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Fix "MSB3677 Unable to move file" regression

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Resources/ImportBeforeTargetTestsTemplate.xml
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Resources/TargetTestsProjectTemplate.xml
> Try to be explicit about the TargetFramework in the Integration UTs

- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerClassifier.java
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/TestUtils.java
> Add IT with S4NET netcore 2.1 build

- scripts/variables.ps1
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Bump scanner-cli version to 4.7.0.2747

- NuGet.Config
- its/projects/VueWithAspBackend/NuGet.Config
> Add nuget config

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
> Drop SQ compatibility matrix from the documentation

- src/SonarScanner.MSBuild.Common/CommandLine/CommandLineFlagPrefix.cs
- src/SonarScanner.MSBuild/ArgumentProcessor.cs
- src/SonarScanner.MSBuild/Program.cs
> Improve scanner help message

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
> Add "/:s:Analysis.xml parameter" back to the docs

- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
> Document minimal runtime requirements for the scanner

- src/SonarScanner.MSBuild/App.config
- src/SonarScanner.MSBuild/SonarScanner.MSBuild.csproj
- src/SonarScanner.MSBuild/app.manifest
Tentative fix for https://github.com/SonarSource/sonar-scanner-msbuild/issues/939
> Add longPathAware manifest and app.config

- Tests/SonarScanner.MSBuild.Common.Test/EnvScannerPropertiesProviderTest.cs
- Tests/TestUtilities/TestLogger.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- src/SonarScanner.MSBuild.Common/AnalysisProperties/EnvScannerPropertiesProvider.cs
> Only log warning when env var parsing fails for Tasks

- Tests/Directory.Build.targets
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- azure-pipelines.yml
- src/Directory.Build.targets
> Use C# 10 language version

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
Cleanup before #1294 and #1298
This is a draft, rebase will be needed.
These commits doesn't need review, they are in #1301 
* Use C# 10 language version
* Use .NET 6 SDK in CI
* Do not set version explicitly
> Cleanup PropertiesFileGenerator

- Tests/SonarScanner.MSBuild.Shim.Test/PathHelperTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/Interfaces/IPropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/PathHelper.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
Fixes #1294
This is draft for now, rebase will be needed once #1306 is merged
> Use BestCommonRoot to calculate analysis base path

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
Fixes #1298 
This is draft, rebase will be needed.
Review per commit is suggested.
Current commit history:
`Update StyleCop to 1.2.0-beta.435` - doesn't need a review, is in #1303 
`Use C# 10 language version` - doesn't need a review, is in #1301 
`Cleanup` - doesn't need a review, is in #1306 
`UT cleanup` - doesn't need a review, is in #1306 
`Remove confusing message about...` - actual implementation
> Remove confusing message about "project without guid will not be analyzed"

- Tests/SonarScanner.MSBuild.Shim.Test/PathHelperTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/PathHelper.cs
to fix New Code Period code coverage
> Bump code coverage

- Tests/Directory.Build.targets
- azure-pipelines.yml
- src/Directory.Build.targets
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
> use vs2019 to fix ccov issue

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
Prepare next development iteration.
> Bump version to 5.9.0

- Tests/SonarScanner.MSBuild.Common.Test/SerializerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
- azure-pipelines.yml
Details: https://community.sonarsource.com/t/please-do-not-change-the-ordering-of-attributes-or-elements-in-the-sonartlint-xml-and-ruleset-files/63262/4?u=andrei_epure
Fixes #1315
> Fix x64 XML tests in order to be able to run tests on windows latest

- Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/MSBuildPostProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild/SonarQube.Analysis.xml
> Remove jdbc related properties.

- its/analyzers/TestAnalyzers/TestAnalyzers/TestAnalyzers/packages.config
> Bump NuGet.CommandLine in ITs

- its/projects/CSharp.SDK.Latest/AspNetCoreMvc/AspNetCoreMvc.csproj
- its/projects/CSharp.SDK.Latest/Main/Main.csproj
- its/projects/CSharp.SDK.Latest/UTs/UTs.csproj
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
> Update target framework to .NET6 in Csharp.SDK.Latest IT

- azure-pipelines.yml
> Fix broken ITs: Change tested plugin versions

- pom.xml
- scripts/version/set-version.ps1
> Update the set-version.ps1 script to change also the java plugin version

- .github/GitHub.shproj
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- SonarScanner.MSBuild.sln
Related to #1351 
Uses these actions, see sample yml:
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardToReview
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardAfterReview
> GitHub workflow: Add RequestReview and SubmitReview

- .github/workflows/CreatePullRequest.yml
Related to #1351 
Same as https://github.com/SonarSource/sonar-dotnet/pull/6333
> GitHub workflow: Add CreatePullRequest

- src/SonarScanner.MSBuild.PreProcessor/TeamBuildPreProcessor.cs
Part of https://sonarsource.atlassian.net/browse/MMF-2875
> Cleanup TeamBuildPreProcessor

- .github/workflows/MilestoneIssue.yml
> GitHub workflow: Add MilestoneIssue

- its/pom.xml
Follow up of #1236
Same thing happened on sonar-dotnet https://github.com/SonarSource/sonar-dotnet/pull/6374
> Remove version from ITs

- NuGet.Config
- src/SonarScanner.MSBuild.PreProcessor/Protobuf/AnalysisCacheMsg.proto
- src/SonarScanner.MSBuild.PreProcessor/SonarScanner.MSBuild.PreProcessor.csproj
Part of #1377
Source of the protobuf: https://github.com/SonarSource/sonarqube/blob/a62adeea05495e24836f7857d598e46d2befd9f7/sonar-scanner-protocol/src/main/protobuf/scanner_internal.proto
> Incremental PR-analysis: Install protobuf and add the analysis cache message

- Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- Tests/SonarScanner.MSBuild.TFS.Test/Classic/BinaryToXmlCoverageReportConverterTests.cs
- Tests/TestUtilities/TestLogger.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
Fixes #1370
MMF: https://sonarsource.atlassian.net/browse/MMF-2875
> Incremental PR analysis: download cache

- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Extract CreateHttpClient

- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarQubeServer.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs
- src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarQubeServer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
> Implement the protobuf deserialization

- azure-pipelines.yml
The other half of #1375 
I don't want to talk about it 🤦
> Fix CI after .NET 7 breaking changes - part 2

- NuGet.Config
> NuGet restore fix - include the protobuf-packages owner

- azure-pipelines.yml
> Consider NuGet.Config when restoring packages

- Tests/Directory.Build.targets
- Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj
- Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- Tests/TestUtilities/TestUtilities.csproj
- azure-pipelines.yml
Fixes #1403 
See: 
Source: https://sonarcloud.io/summary/new_code?id=sonarscanner-msbuild&pullRequest=1406
> Fix coverage

- azure-pipelines.yml
Next analysis should rename https://sonarcloud.io/project/overview?id=sonarscanner-msbuild
> Rename SC project

- Tests/SonarScanner.MSBuild.Common.Test/AnalysisConfig/AnalysisConfigExtensionsTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/AnalysisConfig/AnalysisConfigTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/AnalysisProperties/ListPropertiesProviderTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/FilePropertyProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarCategoriseProjectTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/WriteProjectInfoFileTargetTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/GetAnalyzerSettingsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/IsTestFileByNameTests.cs
- Tests/SonarScanner.MSBuild.Test/ArgumentProcessorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/CmdLineArgPropertyProvider.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/EnvScannerPropertiesProvider.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/ListSettingsProvider.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/Property.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
- src/SonarScanner.MSBuild.Shim/AnalysisConfigExtensions.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Tasks/WriteProjectInfoFile.cs
Cleanup `SonarScanner.MSBuild.Common.Property` and add appropriate constructor.
https://github.com/SonarSource/sonar-scanner-msbuild/pull/1389#discussion_r1030299514
> Add Common.Property constructor

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
> Incremental PR analysis: Fix DownloadCache

- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
> Incremental PR analysis: Log stats

- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
> Add User-Agent header

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServiceTest.cs
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
> Fix the building of url requests

- azure-pipelines.yml
Upgrade JDK from 1.11 to 1.17 for the orchestrator after the azure pipeline image update after SQ update after.
> Upgrade JDK version

- azure-pipelines.yml
- its/src/test/java/com/sonar/it/scanner/SonarScannerTestSuite.java
Updates the JDK and changes the sonar-dotnet version used in ITs to DEV
> Fix master

- scripts/variables.ps1
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
Upgrade sonar scanner CLI - changes should not affect current behaviour
> Bump scanner-cli version to 4.8.0.2856

- Tests/SonarScanner.MSBuild.TFS.Test/Classic/BinaryToXmlCoverageReportConverterTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisProperties/Property.cs
- src/SonarScanner.MSBuild.Common/RegexConstants.cs
- src/SonarScanner.MSBuild.Common/StringExtensions.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild.TFS.Classic/BinaryToXmlCoverageReportConverter.cs
- src/SonarScanner.MSBuild.Tasks/IsTestFileByName.cs
In order to increase the coverage more than that I would have to make the tests update the windows registry on the build machine. I would avoid doing that.
> Address hotspots

- src/SonarScanner.MSBuild.Common/RegexConstants.cs
- PR merge timing was not great and this file skipped the validation
> Fix header (update year)

- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarWebService.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/ScannerMSBuildTest.java
- src/SonarScanner.MSBuild.Common/SonarProduct.cs
- src/SonarScanner.MSBuild.PreProcessor/CacheProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarWebService.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/SonarWebService.cs
> Check server for product type and version before downloading the cache

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
A new rule was introduced in the analyzer and it finds new issues in the analyzed projects (ITs).
> Fix build: updated expected issues

- .github/workflows/ToggleLockBranch.yml
Fixes #1479
Add [ToggleLockBranch](https://github.com/SonarSource/gh-action-lt-backlog/tree/master/ToggleLockBranch)
To review this, just make sure that the file is identical with AutoScan one (name, location, content)
https://github.com/SonarSource/sonar-dotnet-autoscan/blob/master/.github/workflows/ToggleLockBranch.yml
> GitHub workflow: Add ToggleLockBranch

- CONTRIBUTING.md
> Document environment variables needed for SonarCloud ITs

- azure-pipelines.yml
- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/SonarCloudTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
> Incremental PR analysis - SonarCloud: Add ITs

- Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- Tests/SonarScanner.MSBuild.Test/DefaultPropertiesFileTests.cs
- Tests/SonarScanner.MSBuild.Test/ProgramTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarCloudWebServer.cs
- src/SonarScanner.MSBuild/Program.cs
- src/SonarScanner.MSBuild/SonarQube.Analysis.xml
Fixes #1520
I will update the integration tests in a separate PR.
> Add support for sonar.token property

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
> Update ITs to use the new property `sonar.token`

- Tests/SonarScanner.MSBuild.PreProcessor.Test/EmbeddedAnalyzerInstallerTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/EmbeddedAnalyzerInstaller.cs
Fixes #1489
Update the log level when installing plugins.
> Always display plugins version

- Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj
- Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- Tests/TestUtilities/TestUtilities.csproj
- its/projects/CSharp.SDK.2.1/AspNetCoreMvc/AspNetCoreMvc.csproj
- its/projects/CSharp.SDK.2.1/UTs/UTs.csproj
- its/projects/CSharp.SDK.3.1/AspNetCoreMvc/AspNetCoreMvc.csproj
- its/projects/CSharp.SDK.3.1/UTs/UTs.csproj
- its/projects/CSharp.SDK.5/AspNetCoreMvc/AspNetCoreMvc.csproj
- its/projects/CSharp.SDK.5/UTs/UTs.csproj
- its/projects/CSharp.SDK.Latest/AspNetCoreMvc/AspNetCoreMvc.csproj
- its/projects/CSharp.SDK.Latest/UTs/UTs.csproj
- its/projects/RazorWebApplication.net2.1/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net3.1/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net5/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net6.withSourceGenerators/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net6.withoutSourceGenerators/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net7.withSourceGenerators/RazorWebApplication/RazorWebApplication.csproj
- its/projects/RazorWebApplication.net7.withoutSourceGenerators/RazorWebApplication/RazorWebApplication.csproj
- src/SonarScanner.MSBuild.Tasks/SonarScanner.MSBuild.Tasks.csproj
- src/SonarScanner.MSBuild/SonarScanner.MSBuild.csproj
> Remove useless package dependencies

- SonarScanner.MSBuild.sln
> Dependabot workaround: Update SLN to case sensitive paths

- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
merge after #1271
leftover after #1270
> Add back SonarScannerWrapper test

- its/analyzers/TestAnalyzers/TestAnalyzers/TestAnalyzers/TestAnalyzers.csproj
- its/analyzers/TestAnalyzers/TestAnalyzers/TestAnalyzers/packages.config
> Update NuGet.CommandLine to 6.6.1

- scripts/variables.ps1
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Update scanner-cli to 4.8.1.3023

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
I will have a talk with TomH and AlexG on Wednesday about doing a 6.0 release for scanner-cli 5.0 and Java 17.
For now, keeping it simple.
> Bump version to 5.14.0

- azure-pipelines.yml
> Remove ITs for SQ 7.9

- .github/ISSUE_TEMPLATE.md
Update outdated community forum links.
> replace outdated links in ISSUE_TEMPLATE.md

- azure-pipelines.yml
- scripts/variables.ps1
- sonar-docs/analysis/scan/sonarscanner-for-msbuild.md
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Bump scanner cli to 5.0.1.3006

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/RuleSearchPaging.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarQubeWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarWebServer.cs
> Support new api/rules/search API

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/others/OthersTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/others/RuntimeConfigTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/SonarCloudTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SonarQubeTestSuite.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
> Update orchestrator to 4.2.0.542

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.TFS.Test/BuildSettingsTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/BuildVNextCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/Classic/TfsLegacyCoverageReportProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/Infrastructure/MockReportConverter.cs
- src/SonarScanner.MSBuild.Common/TFS/BuildSettings.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.TFS.Classic/Program.cs
- src/SonarScanner.MSBuild.TFS.Classic/XamlBuild/TfsLegacyCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs
- src/SonarScanner.MSBuild.TFS/Interfaces/ICoverageReportConverter.cs
- src/SonarScanner.MSBuild.TFS/Interfaces/ICoverageReportProcessor.cs
- src/SonarScanner.MSBuild/BootstrapperClass.cs
> Remove ICoverageReportConverter.Initialize (not needed anymore)

- Tests/SonarScanner.MSBuild.TFS.Test/Classic/TfsLegacyCoverageReportProcessorTests.cs
- its/projects/CodeCoverage/CodeCoverage.Test/CalculatorTest.cs
- its/projects/CodeCoverage/CodeCoverage.Test/CodeCoverage.Test.csproj
- its/projects/CodeCoverage/CodeCoverage.Test/GlobalUsings.cs
- its/projects/CodeCoverage/CodeCoverage.sln
- its/projects/CodeCoverage/CodeCoverage/Calculator.cs
- its/projects/CodeCoverage/CodeCoverage/CodeCoverage.csproj
- its/projects/CodeCoverage/global.json
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
- src/SonarScanner.MSBuild.TFS/CoverageReportProcessorBase.cs
> Implement ITs for code coverage

- Tests/SonarScanner.MSBuild.Tasks.UnitTest/GetAnalyzerSettingsTests.cs
- src/SonarScanner.MSBuild.Tasks/GetAnalyzerSettings.cs
> Consider all SonarAnalyzer* DLLs as Sonar analyzers

- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
> Remove wrong UserAgent header

- Tests/Directory.Build.targets
- src/Directory.Build.targets
Extracted from https://github.com/SonarSource/sonar-scanner-msbuild/pull/1789 (see [this comment](https://github.com/SonarSource/sonar-scanner-msbuild/pull/1789#discussion_r1402999129)).
> Change LangVersion from 9.0 to latest

- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
> Remove runtime version from the tool description

- README.md
- azure-pipelines.yml
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
> Add links to user guides in README and include in nuget

- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
Tested on external test organization repo
> GitHub workflow: Improve author_association

- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
Same as https://github.com/SonarSource/sonar-dotnet/pull/8618
> Java ITs: Fix CE task extraction

- NuGet.Config
Same as https://github.com/SonarSource/sonar-dotnet/pull/9104
> Add 2024 NuGet certificate

- its/projects/VueWithAspBackend/AspBackend/Program.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
> Fix ScannerMSBuildTest after S6966 was merged

- .sonarlint/SonarScanner.MSBuild.json
Same as https://github.com/SonarSource/sonar-dotnet/pull/9266
> SonarLint: Use shared connected mode

- .github/workflows/SlackNotification.yml
> Add GH action slack notification

- azure-pipelines.yml
Fixes #1935
Performance gain:
- ~5min on PR branches
- ~8min on release branches (because of Mend Scan)
> Run UTs and SC Analysis during Test stage

- azure-pipelines.yml
> Cleanup YML

- azure-pipelines.yml
Fixes #1937 
The changes in indentation makes the PR more difficult to review, so I marked the actual changes with comments.
> Remove Dependency on Burgr

- azure-pipelines.yml
- scripts/generate-packages.ps1
- scripts/promote-project-version.ps1
- scripts/run-unit-tests.ps1
> Extract longer Powershell scripts

- Tests/SonarScanner.MSBuild.Common.Test/CmdLineArgsPropertiesProviderTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
> Add support for JRE provisioning: sonar.scanner.arch

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/IJreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCacheEntry.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCacheResult.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreDescriptor.cs
> Add support for JRE provisioning: JRE cache hit test logic.

- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfig.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
> Add JavaExePath to AnalysisConfig

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs
- src/SonarScanner.MSBuild.Common/IO/FileWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IFileWrapper.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/IJreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
Contributes to https://github.com/SonarSource/sonar-scanner-msbuild/issues/1998
Based on #2007
> Add support for JRE provisioning: JRE cache download

- Tests/SonarScanner.MSBuild.Common.Test/SonarProductTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisSonarCloudTest.java
- src/SonarScanner.MSBuild.Common/SonarProduct.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> Add support for JRE provisioning: Server version check

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/ChecksumSha256Tests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/ChecksumSha256.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/IChecksum.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
Fixes #1997
Contributes to https://github.com/SonarSource/sonar-scanner-msbuild/issues/1998
Based on https://github.com/SonarSource/sonar-scanner-msbuild/pull/2015
> Add support for JRE provisioning: Jre download checksum validation

- Tests/SonarScanner.MSBuild.Shim.Test/MockProcessRunner.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- src/SonarScanner.MSBuild.Common/IO/DirectoryWrapper.cs
- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
> Use JAVA_HOME in the end step

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/HttpMessageHandlerMock.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarWebServer.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/ChecksumSha256.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarCloudWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarQubeWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarWebServer.cs
Fixes #1996
Also some cleanup on the downloader tests.
> Add support for JRE provisioning: JRE download (/analysis/jres/{jre_id})

- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/IJreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
Fixes #2029
Needs #2006 
Also did some cleanup, either go commit by commit, or hide whitespace on github.
> Add support for JRE provisioning: Use JreResolver in Preprocessor

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreCaching/JreCacheTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreCaching/JreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
> Add support for JRE provisioning: Delete archive when checksum validation fails.

- azure-pipelines.yml
> Revert: CI: Fix the cfamily plugin version (Revert #2034)

- azure-pipelines.yml
> CI: Update Nuget version

- azure-pipelines.yml
There seems to be a problem with Incremental PR analysis, which doesn't have to do with us.
An email has been sent.
> [TO BE REVERTED] Disable SonarCloud ITs

- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
> Breaking change UX: Add a message if the change of the default sonar.hostUrl is breaking the analysis

- StylingAnalyzers.targets
- Tests/LogArgs/LogArgs.csproj
- Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj
- Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- Tests/TestUtilities/TestUtilities.csproj
See https://sonarsource.slack.com/archives/C03HVJQ53M2/p1721214022848499
> Update Test project dependencies

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
> JRE Provisioning: Support not specifying sonar.host.url

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarCloudWebServer.cs
> API Endpoint change: prepare_read URI

- azure-pipelines.yml
- scripts/package-artifacts.ps1
> Releases produce zip files with a backslash as a separator

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- src/SonarScanner.MSBuild.Common/IO/DirectoryWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IDirectoryWrapper.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
- src/SonarScanner.MSBuild.Shim/Interfaces/IAdditionalFilesService.cs
> Multi-Language Support: Read file extensions from SonarqubeAnalysis.xml

- Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
- src/SonarScanner.MSBuild.Shim/Interfaces/IAdditionalFilesService.cs
> Multi-Language Support: Test file detection

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- azure-pipelines.yml
> Add Reference to Microsoft.IO.Redist so we can update the dependency (CVE-2024-38081)

- Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
> Multi-Language Support: Add sonar.scanner.multiFileAnalysis parameter

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
> Multi-Language Support: Fix read file extensions from SonarqubeAnalysis.xml

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarWebServer.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServerTest.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/ISonarWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarQubeWebServer.cs
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarWebServer.cs
> JRE provisioning: Don't try JRE provisioning for SQ <10.6

- Tests/SonarScanner.MSBuild.Common.Test/ILoggerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderTest.cs
- src/SonarScanner.MSBuild.Common/Interfaces/ILoggerExtensions.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloader.cs
> JRE provisioning: Turn version check info message to debug

- azure-pipelines.yml
> CI: Remove the SIGNTOOL_PATH env

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Common/IO/DirectoryWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IDirectoryWrapper.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
> Multi-language Support: Exclude .sonarqube/ and .sonar/

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
Cherry-picked from: https://github.com/SonarSource/sonar-scanner-msbuild/pull/2138/commits/755e923e391ada66034f29d90e1fdaf1a736a6b1
> Multi-file Analysis: Add css plugin and assertions

- Tests/SonarScanner.MSBuild.Common.Test/SonarPropertiesTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfig.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.PostProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PostProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
> Multi-Language Support: sonar.scanner.multiFileAnalysis argument naming

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests_MultiTarget.cs
- src/SonarScanner.MSBuild.Common/SonarScanner.MSBuild.Common.csproj
- src/SonarScanner.MSBuild.Shim/ProjectLoader.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/Resources.Designer.cs
- src/SonarScanner.MSBuild.Shim/Resources.resx
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
> Root directory detection: OS root (/ on Unix or C: on Windows) is identified as the project directory

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
[SCAN4NET-22](https://sonarsource.atlassian.net/browse/SCAN4NET-22)
[SCAN4NET-22]: https://sonarsource.atlassian.net/browse/SCAN4NET-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-22 Multi-Language Support: Re-enable exclusions

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests_MultiTarget.cs
- Tests/TestUtilities/TestUtils.cs
- src/SonarScanner.MSBuild.Common/ProjectInfo/ProjectInfoValidity.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
https://sonarsource.atlassian.net/browse/SCAN4NET-27
> SCAN4NET-27 Skip projects that no longer exist

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-31](https://sonarsource.atlassian.net/browse/SCAN4NET-31)
[SCAN4NET-31]: https://sonarsource.atlassian.net/browse/SCAN4NET-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-31 Version bump to 9.0.0

- azure-pipelines.yml
[SCAN4NET-37](https://sonarsource.atlassian.net/browse/SCAN4NET-37)
[SCAN4NET-37]: https://sonarsource.atlassian.net/browse/SCAN4NET-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-37 Azure Pipelines: Remove pipelines-yaml-templates dependency

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RoslynTargetsTests.cs
- azure-pipelines.yml
- its/projects/DotnetProjectTypeDetection/TestProjectWrongReferenceCasing/TestProjectWrongReferenceCasing.csproj
- its/projects/ExcludedTest/Excluded/Excluded.csproj
- its/projects/ExcludedTest/Normal/Normal.csproj
- its/projects/ExcludedTest/Test/Test.csproj
- its/projects/IncrementalPRAnalysis/IncrementalPRAnalysis/IncrementalPRAnalysis.csproj
- its/projects/XamarinApplication/XamarinApplication/XamarinApplication.csproj
[SCAN4NET-30](https://sonarsource.atlassian.net/browse/SCAN4NET-30)
[SCAN4NET-30]: https://sonarsource.atlassian.net/browse/SCAN4NET-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Infra: Update the UTs and ITs to be able to run on .NET 9 preview 

- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigGeneratorTests.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigGenerator.cs
[SCAN4NET-48](https://sonarsource.atlassian.net/browse/SCAN4NET-48)
[SCAN4NET-48]: https://sonarsource.atlassian.net/browse/SCAN4NET-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-48 Multi Language Support: Make sure the server side exclusions are not overwritten

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
[SCAN4NET-84](https://sonarsource.atlassian.net/browse/SCAN4NET-84)
Part of 
[SCAN4NET-84]: https://sonarsource.atlassian.net/browse/SCAN4NET-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-84 Jira integration: Use repo vault token

- azure-pipelines.yml
- scripts/generate-packages.ps1
- scripts/generate-packages.tests.ps1
[SCAN4NET-94](https://sonarsource.atlassian.net/browse/SCAN4NET-94)
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-93
[SCAN4NET-94]: https://sonarsource.atlassian.net/browse/SCAN4NET-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-94 Fix Choco packaging scripts

- src/SonarScanner.MSBuild.Common/Interfaces/ILogger.cs
[SCAN4NET-102](https://sonarsource.atlassian.net/browse/SCAN4NET-102)
[SCAN4NET-102]: https://sonarsource.atlassian.net/browse/SCAN4NET-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-102 SQ<9.9 UI warning comment

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
[SCAN4NET-103](https://sonarsource.atlassian.net/browse/SCAN4NET-103)
[SCAN4NET-103]: https://sonarsource.atlassian.net/browse/SCAN4NET-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-103 Additional Files: Exclude C++ build wrapper output

- azure-pipelines.yml
- scripts/generate-packages.ps1
- scripts/generate-packages.tests.ps1
[SCAN4NET-101](https://sonarsource.atlassian.net/browse/SCAN4NET-101)
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-93
[SCAN4NET-101]: https://sonarsource.atlassian.net/browse/SCAN4NET-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-101 Run tests for package generation script

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- azure-pipelines.yml
- scripts/generate-packages.ps1
- scripts/generate-packages.tests.ps1
SCAN4NET-106
Part of https://sonarsource.atlassian.net/browse/SCAN4NET-93
Cherry-pick from https://github.com/SonarSource/sonar-scanner-msbuild/pull/2211
> SCAN4NET-106 Fix Choco packaging scripts (branch-8.0)

- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
[SCAN4NET-104](https://sonarsource.atlassian.net/browse/SCAN4NET-104)
[SCAN4NET-104]: https://sonarsource.atlassian.net/browse/SCAN4NET-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-104 Jira integration: Use repo vault token

- azure-pipelines.yml
[SCAN4NET-107](https://sonarsource.atlassian.net/browse/SCAN4NET-107)
Left over from https://github.com/SonarSource/sonar-scanner-msbuild/pull/1933
[SCAN4NET-107]: https://sonarsource.atlassian.net/browse/SCAN4NET-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-107 Use installed CycloneDX

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
[SCAN4NET-130](https://sonarsource.atlassian.net/browse/SCAN4NET-130)
Fix branch-8.0: cherrypick #2232 commit 6fa74479
[SCAN4NET-130]: https://sonarsource.atlassian.net/browse/SCAN4NET-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-130 Fix branch-8.0 build

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-133](https://sonarsource.atlassian.net/browse/SCAN4NET-133)
[SCAN4NET-133]: https://sonarsource.atlassian.net/browse/SCAN4NET-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-133 ITs: Remove unused function

- azure-pipelines.yml
[SCAN4NET-140](https://sonarsource.atlassian.net/browse/SCAN4NET-140)
[SCAN4NET-140]: https://sonarsource.atlassian.net/browse/SCAN4NET-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-140 Infra: Update the sonar coud tasks to the latest version

- azure-pipelines.yml
[SCAN4NET-141](https://sonarsource.atlassian.net/browse/SCAN4NET-141)
[SCAN4NET-141]: https://sonarsource.atlassian.net/browse/SCAN4NET-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-141 Infra: Update coverage paths

- docs/SonarQube.Analysis.xml
- src/SonarScanner.MSBuild/SonarQube.Analysis.xml
[SCAN4NET-143](https://sonarsource.atlassian.net/browse/SCAN4NET-143)
[SCAN4NET-143]: https://sonarsource.atlassian.net/browse/SCAN4NET-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-143 Config: Remove the deprecated login and password parameters

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-149](https://sonarsource.atlassian.net/browse/SCAN4NET-149)
[SCAN4NET-149]: https://sonarsource.atlassian.net/browse/SCAN4NET-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-149 Set version to 9.0.1 for hotfix release

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-151](https://sonarsource.atlassian.net/browse/SCAN4NET-151)
[SCAN4NET-151]: https://sonarsource.atlassian.net/browse/SCAN4NET-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-151 Bump version after release

- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
[SCAN4NET-155](https://sonarsource.atlassian.net/browse/SCAN4NET-155)
[SCAN4NET-155]: https://sonarsource.atlassian.net/browse/SCAN4NET-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-155 Clean up: Remove unused variable

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-159](https://sonarsource.atlassian.net/browse/SCAN4NET-159)
[SCAN4NET-159]: https://sonarsource.atlassian.net/browse/SCAN4NET-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-159 Set version to 9.0.2 to prepare hotfix

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-164](https://sonarsource.atlassian.net/browse/SCAN4NET-164)
[SCAN4NET-164]: https://sonarsource.atlassian.net/browse/SCAN4NET-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-164 ITs: Extend testScannerRespectsSonarqubeScannerParams

- azure-pipelines.yml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
[SCAN4NET-167](https://sonarsource.atlassian.net/browse/SCAN4NET-167)
[SCAN4NET-167]: https://sonarsource.atlassian.net/browse/SCAN4NET-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-167 Use SQ DEV 10.8 for testing

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
[SCAN4NET-176](https://sonarsource.atlassian.net/browse/SCAN4NET-176)
[SCAN4NET-176]: https://sonarsource.atlassian.net/browse/SCAN4NET-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-176 Disable telemetry for the integration tests

- Tests/Directory.Build.targets
- Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj
- Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildLog.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/GetAnalyzerSettingsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/WriteProjectConfigFileTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/WriteProjectInfoFileTests.cs
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- Tests/TestUtilities/TestUtilities.csproj
- src/Directory.Build.targets
- src/SonarScanner.MSBuild.PreProcessor/SonarScanner.MSBuild.PreProcessor.csproj
- src/SonarScanner.MSBuild.Shim/SonarScanner.MSBuild.Shim.csproj
- src/SonarScanner.MSBuild.TFS.Classic/SonarScanner.MSBuild.TFS.Classic.csproj
- src/SonarScanner.MSBuild.TFS/SonarScanner.MSBuild.TFS.csproj
[SCAN4NET-219](https://sonarsource.atlassian.net/browse/SCAN4NET-219)
Part of NET-733
[SCAN4NET-219]: https://sonarsource.atlassian.net/browse/SCAN4NET-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-219 Configure Global Usings

- NuGet.Config
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/ServerBuilder.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/TestUtilities/TempFile.cs
[SCAN4NET-213](https://sonarsource.atlassian.net/browse/SCAN4NET-213)
[SCAN4NET-213]: https://sonarsource.atlassian.net/browse/SCAN4NET-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-213 Certificate creation framework for testing

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-215](https://sonarsource.atlassian.net/browse/SCAN4NET-215)
[SCAN4NET-215]: https://sonarsource.atlassian.net/browse/SCAN4NET-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-215 Truststore path validation (file exists/can be opened)

- azure-pipelines.yml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-223](https://sonarsource.atlassian.net/browse/SCAN4NET-223)
Part of 
[SCAN4NET-223]: https://sonarsource.atlassian.net/browse/SCAN4NET-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-223 Add IT with SQ 2025.1 LTA

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockRoslynAnalyzerProvider.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
[SCAN4NET-220](https://sonarsource.atlassian.net/browse/SCAN4NET-220)
Part of SCAN4NET-171
[SCAN4NET-220]: https://sonarsource.atlassian.net/browse/SCAN4NET-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-220 Refactor RoslynAnalyzerProvider Constructor

- azure-pipelines.yml
- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/HttpsReverseProxy.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/SslUtils.java
- scripts/generate-and-trust-self-signed-certificate.ps1
- scripts/trust-self-signed-certificate.ps1
[SCAN4NET-210](https://sonarsource.atlassian.net/browse/SCAN4NET-210)
[SCAN4NET-210]: https://sonarsource.atlassian.net/browse/SCAN4NET-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-210 Add IT SSL test for current state

- Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynSonarLint.cs
[SCAN4NET-231](https://sonarsource.atlassian.net/browse/SCAN4NET-231)
Part of 
[SCAN4NET-231]: https://sonarsource.atlassian.net/browse/SCAN4NET-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-231 Cleanup RoslynAnalyzerProviderTest

- NuGet.Config
- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/ServerBuilder.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/X509Certificate2Extensions.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
- Tests/TestUtilities/TestUtilities.csproj
- scripts/run-unit-tests.ps1
[SCAN4NET-236](https://sonarsource.atlassian.net/browse/SCAN4NET-236)
[SCAN4NET-236]: https://sonarsource.atlassian.net/browse/SCAN4NET-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-236 Multi-target SonarScanner.MSBuild.PreProcessor.Test

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.Net.Tests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.Net.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/ServerBuilder.cs
[SCAN4NET-237](https://sonarsource.atlassian.net/browse/SCAN4NET-237)
[SCAN4NET-237]: https://sonarsource.atlassian.net/browse/SCAN4NET-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-237 Add CertificateBuilder.CreateCrlExtension and tests

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-238](https://sonarsource.atlassian.net/browse/SCAN4NET-238)
Part of 
[SCAN4NET-238]: https://sonarsource.atlassian.net/browse/SCAN4NET-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-238 Bump version to 9.2.0

- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
- src/SonarScanner.MSBuild.PreProcessor/WebClientDownloaderBuilder.cs
> SCAN4NET-242 Add logging for self-signed cert not found in truststore file

- Tests/SonarScanner.MSBuild.PreProcessor.Test/EmbeddedAnalyzerInstallerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Roslyn/PluginTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
[SCAN4NET-257](https://sonarsource.atlassian.net/browse/SCAN4NET-257)
[SCAN4NET-257]: https://sonarsource.atlassian.net/browse/SCAN4NET-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-257 Fix Quality Gate

- azure-pipelines.yml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
[SCAN4NET-261](https://sonarsource.atlassian.net/browse/SCAN4NET-261)
Fixes #1486
[SCAN4NET-261]: https://sonarsource.atlassian.net/browse/SCAN4NET-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-261 Use plugin versions from released SQ

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-266](https://sonarsource.atlassian.net/browse/SCAN4NET-266)
[SCAN4NET-266]: https://sonarsource.atlassian.net/browse/SCAN4NET-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-266 Set version to 9.2.1 for hotfix

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- azure-pipelines.yml
- its/projects/MultiLanguageSupport/main.bicep
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
[SCAN4NET-271](https://sonarsource.atlassian.net/browse/SCAN4NET-271)
[SCAN4NET-271]: https://sonarsource.atlassian.net/browse/SCAN4NET-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-271 Add AzureResourceManager support

- Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/LocalJreTruststoreResolverTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/MockProcessRunner.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/TFSProcessorWrapperTest.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildRunner.cs
- src/SonarScanner.MSBuild.Common/ProcessResult.cs
- src/SonarScanner.MSBuild.Common/ProcessRunner.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/AnalysisConfigGenerator.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/LocalJreTruststoreResolver.cs
- src/SonarScanner.MSBuild.Shim/SonarScanner.Wrapper.cs
- src/SonarScanner.MSBuild.Shim/TFSProcessor.Wrapper.cs
[SCAN4NET-268](https://sonarsource.atlassian.net/browse/SCAN4NET-268)
Part of SCAN4NET-227
[SCAN4NET-268]: https://sonarsource.atlassian.net/browse/SCAN4NET-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-268 ProcessRunner improvement

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- its/projects/MultiLanguageSupport/src/MultiLanguageSupport/terraform.tf
- its/projects/MultiLanguageSupport/src/Outside.tf
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
[SCAN4NET-277](https://sonarsource.atlassian.net/browse/SCAN4NET-277)
[SCAN4NET-277]: https://sonarsource.atlassian.net/browse/SCAN4NET-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-277 Add Terraform support

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-267](https://sonarsource.atlassian.net/browse/SCAN4NET-267)
[SCAN4NET-267]: https://sonarsource.atlassian.net/browse/SCAN4NET-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-267 Update version to 9.3.0

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- azure-pipelines.yml
- its/projects/MultiLanguageSupport/main.go
- its/projects/MultiLanguageSupport/src/MultiLanguageSupport/main.go
- its/projects/MultiLanguageSupport/src/main.go
- its/projects/MultiLanguageSupport/vendor/main.go
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
[SCAN4NET-275](https://sonarsource.atlassian.net/browse/SCAN4NET-275)
[SCAN4NET-275]: https://sonarsource.atlassian.net/browse/SCAN4NET-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-275 Add Go support

- its/projects/MultiLanguageSupport/cloudformation.yaml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-280](https://sonarsource.atlassian.net/browse/SCAN4NET-280)
[SCAN4NET-280]: https://sonarsource.atlassian.net/browse/SCAN4NET-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-280 Add cloudformation support

- .github/workflows/PullRequestClosed.yml
[SCAN4NET-282](https://sonarsource.atlassian.net/browse/SCAN4NET-282)
Part of 
[SCAN4NET-282]: https://sonarsource.atlassian.net/browse/SCAN4NET-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-282 Rename PullRequestClosed action

- azure-pipelines.yml
[SCAN4NET-284](https://sonarsource.atlassian.net/browse/SCAN4NET-284)
[SCAN4NET-284]: https://sonarsource.atlassian.net/browse/SCAN4NET-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-284 AzDevops: Upgrade to Maven@4

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-289](https://sonarsource.atlassian.net/browse/SCAN4NET-289)
[SCAN4NET-289]: https://sonarsource.atlassian.net/browse/SCAN4NET-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-289 Update version to 10.0.0

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-285](https://sonarsource.atlassian.net/browse/SCAN4NET-285)
Part of 
[SCAN4NET-285]: https://sonarsource.atlassian.net/browse/SCAN4NET-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-285 Replace allIssues with projectIssues

- azure-pipelines.yml
- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-294](https://sonarsource.atlassian.net/browse/SCAN4NET-294)
Part of 
[SCAN4NET-294]: https://sonarsource.atlassian.net/browse/SCAN4NET-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-294 Deduplicate help message IT

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-313](https://sonarsource.atlassian.net/browse/SCAN4NET-313)
[SCAN4NET-313]: https://sonarsource.atlassian.net/browse/SCAN4NET-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-313 Bump version to 10.2

- its/projects/Empty/Empty.csproj
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
[SCAN4NET-318](https://sonarsource.atlassian.net/browse/SCAN4NET-318)
Make sure ITs fail when startup fails
[SCAN4NET-318]: https://sonarsource.atlassian.net/browse/SCAN4NET-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-318 Improve OrchestratorState startup

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/Constants.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/SonarCloudUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/Property.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
[SCAN4NET-319](https://sonarsource.atlassian.net/browse/SCAN4NET-319)
[SCAN4NET-319]: https://sonarsource.atlassian.net/browse/SCAN4NET-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-319 Migrate SonarCloud ITs to ScannerCommand

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
- its/src/test/resources/junit-platform.properties
[SCAN4NET-197](https://sonarsource.atlassian.net/browse/SCAN4NET-197)
Part of 
[SCAN4NET-197]: https://sonarsource.atlassian.net/browse/SCAN4NET-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-197 Run ITs in parallel

- azure-pipelines.yml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/Tests.java
[SCAN4NET-303](https://sonarsource.atlassian.net/browse/SCAN4NET-303)
Some context: https://sonarsource.slack.com/archives/C03HVJQ53M2/p1741795197251509
[SCAN4NET-303]: https://sonarsource.atlassian.net/browse/SCAN4NET-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-303 Improve ITs plugin registration

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-292](https://sonarsource.atlassian.net/browse/SCAN4NET-292)
Commit history helps a little
[SCAN4NET-292]: https://sonarsource.atlassian.net/browse/SCAN4NET-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-292 Extract MultiLanguageTest

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudTests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-346](https://sonarsource.atlassian.net/browse/SCAN4NET-346)
Simplified version of `ServerTests` + `OrchestratorStartup` classes for Cloud
[SCAN4NET-346]: https://sonarsource.atlassian.net/browse/SCAN4NET-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-346 Fix Cloud startup race condition

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ServerTests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-293](https://sonarsource.atlassian.net/browse/SCAN4NET-293)
Part of 
[SCAN4NET-293]: https://sonarsource.atlassian.net/browse/SCAN4NET-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-293 Rework token handling

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-335](https://sonarsource.atlassian.net/browse/SCAN4NET-335)
[SCAN4NET-335]: https://sonarsource.atlassian.net/browse/SCAN4NET-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-335 Extract ProxyTest

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-333](https://sonarsource.atlassian.net/browse/SCAN4NET-333)
[SCAN4NET-333]: https://sonarsource.atlassian.net/browse/SCAN4NET-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-333 Extract Incremental PR Analysis

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
[SCAN4NET-331](https://sonarsource.atlassian.net/browse/SCAN4NET-331)
Part of 
[SCAN4NET-331]: https://sonarsource.atlassian.net/browse/SCAN4NET-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-331 Extract ParameterTest and BaseDirTest

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProjectKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerMSBuildTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
[SCAN4NET-334](https://sonarsource.atlassian.net/browse/SCAN4NET-334)
Move ITs into another file, without any modifications
[SCAN4NET-334]: https://sonarsource.atlassian.net/browse/SCAN4NET-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-334 Extract ProjectKindTest

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/HostInfo.cs
[SCAN4NET-351](https://sonarsource.atlassian.net/browse/SCAN4NET-351)
Part of 
[SCAN4NET-351]: https://sonarsource.atlassian.net/browse/SCAN4NET-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-351 Unify Cloud support

- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessor.cs
[SCAN4NET-359](https://sonarsource.atlassian.net/browse/SCAN4NET-359)
[SCAN4NET-359]: https://sonarsource.atlassian.net/browse/SCAN4NET-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-359 Custom certificates should be supported for SQ cloud as well

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisResult.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-342](https://sonarsource.atlassian.net/browse/SCAN4NET-342)
Cloud support and unified environment variable handling will be in the next PR
[SCAN4NET-342]: https://sonarsource.atlassian.net/browse/SCAN4NET-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-342 Prepare AnalysisContext

- azure-pipelines.yml
- its/pom.xml
- templates/its-jobs.yml
- templates/unix-qa-stage.yml
[SCAN4NET-308](https://sonarsource.atlassian.net/browse/SCAN4NET-308)
[SCAN4NET-308]: https://sonarsource.atlassian.net/browse/SCAN4NET-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-308 Create a new stage in azure-pipeline.yaml for Linux QA and MacOS QA

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisResult.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
[SCAN4NET-356](https://sonarsource.atlassian.net/browse/SCAN4NET-356)
[SCAN4NET-356]: https://sonarsource.atlassian.net/browse/SCAN4NET-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-356 Prepare AnalysisContext for Cloud

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
[SCAN4NET-357](https://sonarsource.atlassian.net/browse/SCAN4NET-357)
Part of 
[SCAN4NET-357]: https://sonarsource.atlassian.net/browse/SCAN4NET-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-357 Unify environment variable handling in AnalysisContext

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ContextExtension.java
[SCAN4NET-298](https://sonarsource.atlassian.net/browse/SCAN4NET-298)
[SCAN4NET-298]: https://sonarsource.atlassian.net/browse/SCAN4NET-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-298 Use test method name as projectKey

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-290](https://sonarsource.atlassian.net/browse/SCAN4NET-290)
[SCAN4NET-290]: https://sonarsource.atlassian.net/browse/SCAN4NET-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-290 Remove TestUtils.hasModules

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BaseCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
[SCAN4NET-312](https://sonarsource.atlassian.net/browse/SCAN4NET-312)
[SCAN4NET-312]: https://sonarsource.atlassian.net/browse/SCAN4NET-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-312 Implement BuildCommand

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-337](https://sonarsource.atlassian.net/browse/SCAN4NET-337)
Alternative to #2351
[SCAN4NET-337]: https://sonarsource.atlassian.net/browse/SCAN4NET-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-337 Update sonar-ws to 25.3.0.104237

- its/projects/CSharpAllFlat/ClassLib1.csproj
- its/projects/CSharpAllFlat/ClassLib2.csproj
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ContextExtension.java
- templates/its-jobs.yml
- templates/unix-qa-stage.yml
[SCAN4NET-315](https://sonarsource.atlassian.net/browse/SCAN4NET-315)
4 (+1 skipped) ITs are running and are green :D
[SCAN4NET-315]: https://sonarsource.atlassian.net/browse/SCAN4NET-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-315 Make one IT successfully run on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudTests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ContextExtension.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TempDirectory.java
[SCAN4NET-368](https://sonarsource.atlassian.net/browse/SCAN4NET-368)
Part of SCAN4NET-355
[SCAN4NET-368]: https://sonarsource.atlassian.net/browse/SCAN4NET-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-368 Use AnalysisContext in Cloud tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
[SCAN4NET-370](https://sonarsource.atlassian.net/browse/SCAN4NET-370)
Part of 
[SCAN4NET-370]: https://sonarsource.atlassian.net/browse/SCAN4NET-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-370 Use AnalysisContext in Parameter tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ContextExtension.java
[SCAN4NET-372](https://sonarsource.atlassian.net/browse/SCAN4NET-372)
Part of 
[SCAN4NET-372]: https://sonarsource.atlassian.net/browse/SCAN4NET-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-372 Use AnalysisContext in Coverage and ExternalIssues tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudConstants.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerClassifier.java
[SCAN4NET-380](https://sonarsource.atlassian.net/browse/SCAN4NET-380)
[SCAN4NET-380]: https://sonarsource.atlassian.net/browse/SCAN4NET-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-380 Cleanup ScannerClassifier

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudConstants.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-371](https://sonarsource.atlassian.net/browse/SCAN4NET-371)
Part of 
[SCAN4NET-371]: https://sonarsource.atlassian.net/browse/SCAN4NET-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-371 Use AnalysisContext in MultiLanguage tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
> SCAN4NET-369 Use AnalysisContext in SolutionKind tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-375](https://sonarsource.atlassian.net/browse/SCAN4NET-375)
Part of 
[SCAN4NET-375]: https://sonarsource.atlassian.net/browse/SCAN4NET-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-375 Use AnalysisContext in Scanner and SQL tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/OSPlatform.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/OperatingSystem.java
[SCAN4NET-384](https://sonarsource.atlassian.net/browse/SCAN4NET-384)
Part of SCAN4NET-10
[SCAN4NET-384]: https://sonarsource.atlassian.net/browse/SCAN4NET-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-384 Create OSPlatform test utils

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/GeneralCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-365](https://sonarsource.atlassian.net/browse/SCAN4NET-365)
Replaces #2426
[SCAN4NET-365]: https://sonarsource.atlassian.net/browse/SCAN4NET-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-365 Better logs for whenMajorityOfProjectsIsOnSameDrive_AnalysisSucceeds

- its/projects/TwoDrivesThreeProjects/DefaultDrive/DefaultDriveFirstProject.csproj
- its/projects/TwoDrivesThreeProjects/DefaultDrive/Program.cs
- its/projects/TwoDrivesThreeProjects/DefaultDriveSecondProject/DefaultDriveSecondProject.vbproj
- its/projects/TwoDrivesThreeProjects/DriveY/Subfolder/DriveY.csproj
- its/projects/TwoDrivesThreeProjects/DriveY/Subfolder/Program.cs
- its/projects/TwoDrivesTwoProjects/DefaultDrive/DefaultDrive.csproj
- its/projects/TwoDrivesTwoProjects/DefaultDrive/Program.cs
- its/projects/TwoDrivesTwoProjects/DriveZ/Subfolder/DriveZ.csproj
- its/projects/TwoDrivesTwoProjects/DriveZ/Subfolder/Program.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java
[SCAN4NET-374](https://sonarsource.atlassian.net/browse/SCAN4NET-374)
Part of 
[SCAN4NET-374]: https://sonarsource.atlassian.net/browse/SCAN4NET-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-374 Use AnalysisContext in BaseDir and Proxy tests

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
[SCAN4NET-322](https://sonarsource.atlassian.net/browse/SCAN4NET-322)
Part of 
[SCAN4NET-322]: https://sonarsource.atlassian.net/browse/SCAN4NET-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-322 Cleanup project baseDir in ITs

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/GeneralCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/TestUtils.java
- templates/its-jobs.yml
[SCAN4NET-385](https://sonarsource.atlassian.net/browse/SCAN4NET-385)
[SCAN4NET-385]: https://sonarsource.atlassian.net/browse/SCAN4NET-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-385 Use AnalysisContext in CppTest

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/QualityProfile.java
[SCAN4NET-383](https://sonarsource.atlassian.net/browse/SCAN4NET-383)
Part of 
[SCAN4NET-383]: https://sonarsource.atlassian.net/browse/SCAN4NET-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-383 Use AnalysisContext to setup QPs

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/IncrementalPRAnalysisTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SQLServerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
[SCAN4NET-381](https://sonarsource.atlassian.net/browse/SCAN4NET-381)
Part of 
[SCAN4NET-381]: https://sonarsource.atlassian.net/browse/SCAN4NET-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-381 Cleanup IT test names

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/HttpsReverseProxy.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/SslExceptionMessages.java
- scripts/Dockerfile
- scripts/ci-self-signed-certificate.ps1
- scripts/run-test-docker.ps1
- scripts/run-test-linux.ps1
- templates/its-jobs.yml
- templates/unix-qa-stage.yml
[SCAN4NET-232](https://sonarsource.atlassian.net/browse/SCAN4NET-232)
[SCAN4NET-232]: https://sonarsource.atlassian.net/browse/SCAN4NET-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-232 Support SSL ITs on Linux

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudConstants.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudTests.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
[SCAN4NET-379](https://sonarsource.atlassian.net/browse/SCAN4NET-379)
Part of 
[SCAN4NET-379]: https://sonarsource.atlassian.net/browse/SCAN4NET-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-379 Document Cloud ITs

- Tests/SonarScanner.MSBuild.Common.Test/ProcessRunnerTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Unpacking/TarGzUnpackTests.cs
- scripts/run-test-docker.ps1
- scripts/run-test-linux.ps1
- scripts/run-test-wsl.ps1
- src/SonarScanner.MSBuild.PreProcessor/Unpacking/TarGzUnpacker.cs
[SCAN4NET-398](https://sonarsource.atlassian.net/browse/SCAN4NET-398)
Part of SCAN4NET-311
[SCAN4NET-398]: https://sonarsource.atlassian.net/browse/SCAN4NET-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-398 Fix TarGzUnpackTests on Linux/MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/OrchestratorState.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/AnalysisContext.java
[SCAN4NET-325](https://sonarsource.atlassian.net/browse/SCAN4NET-325)
[SCAN4NET-325]: https://sonarsource.atlassian.net/browse/SCAN4NET-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-325 Update ScannerCommand to use NET version by default

- templates/its-jobs.yml
- templates/unix-qa-stage.yml
[SCAN4NET-416](https://sonarsource.atlassian.net/browse/SCAN4NET-416)
[SCAN4NET-416]: https://sonarsource.atlassian.net/browse/SCAN4NET-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-416 Azure pipeline config cleanup

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/OSPlatform.java
- scripts/run-test-linux.ps1
- templates/unix-qa-stage.yml
[SCAN4NET-402](https://sonarsource.atlassian.net/browse/SCAN4NET-402)
[SCAN4NET-402]: https://sonarsource.atlassian.net/browse/SCAN4NET-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-402 Support JreProvisioningTest SQS ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/JreProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/JreProvisioningAssertions.java
- scripts/run-test-linux.ps1
- templates/unix-qa-stage.yml
[SCAN4NET-407](https://sonarsource.atlassian.net/browse/SCAN4NET-407)
Same as #2461 but for SQC!
[SCAN4NET-407]: https://sonarsource.atlassian.net/browse/SCAN4NET-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-407 Support JreProvisioningTest SQC ITs on Linux & MacOS

- .github/workflows/SlackNotification.yml
[SCAN4NET-421](https://sonarsource.atlassian.net/browse/SCAN4NET-421)
[SCAN4NET-421]: https://sonarsource.atlassian.net/browse/SCAN4NET-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-421 Add actions: read to Slack notification

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/RegionTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-403](https://sonarsource.atlassian.net/browse/SCAN4NET-403)
[SCAN4NET-403]: https://sonarsource.atlassian.net/browse/SCAN4NET-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-403 Support RegionTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ParameterTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-409](https://sonarsource.atlassian.net/browse/SCAN4NET-409)
[SCAN4NET-409]: https://sonarsource.atlassian.net/browse/SCAN4NET-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-409 Support ParameterTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/IncrementalPRAnalysisTest.java
- scripts/run-test-linux.ps1
- templates/unix-qa-stage.yml
[SCAN4NET-406](https://sonarsource.atlassian.net/browse/SCAN4NET-406)
Only the first commit will make to master.
~Second commit is to make the PR until #2469 is merged.~
> ~⚠️ Second commit should be reverted/dropped before merging~
[SCAN4NET-406]: https://sonarsource.atlassian.net/browse/SCAN4NET-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-406 Support IncrementalPRAnalysisTest SQC ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CodeCoverageTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-404](https://sonarsource.atlassian.net/browse/SCAN4NET-404)
[SCAN4NET-404]: https://sonarsource.atlassian.net/browse/SCAN4NET-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-404 Support CodeCoverageTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-399](https://sonarsource.atlassian.net/browse/SCAN4NET-399)
[SCAN4NET-399]: https://sonarsource.atlassian.net/browse/SCAN4NET-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-399 Support BaseDirTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProxyTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-410](https://sonarsource.atlassian.net/browse/SCAN4NET-410)
[SCAN4NET-410]: https://sonarsource.atlassian.net/browse/SCAN4NET-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-410 Support ProxyTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/MSBuildMinVersion.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/MSBuildMinVersionCondition.java
[SCAN4NET-425](https://sonarsource.atlassian.net/browse/SCAN4NET-425)
Part of SCAN4NET-314
[SCAN4NET-425]: https://sonarsource.atlassian.net/browse/SCAN4NET-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-425 Create MSBuildMinVersion annotation

- its/projects/IgnoreIssuesDoesNotRemoveSourceGenerator/global.json
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ExternalIssuesTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SolutionKindTest.java
- templates/unix-qa-stage.yml
[SCAN4NET-411](https://sonarsource.atlassian.net/browse/SCAN4NET-411)
[SCAN4NET-411]: https://sonarsource.atlassian.net/browse/SCAN4NET-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-411 Support SolutionKindTest ITs on Linux & MacOS

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudUtils.java
[SCAN4NET-430](https://sonarsource.atlassian.net/browse/SCAN4NET-430)
[SCAN4NET-430]: https://sonarsource.atlassian.net/browse/SCAN4NET-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-430 Fix StringIndexOutOfBoundsException in CloudUtils

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-442](https://sonarsource.atlassian.net/browse/SCAN4NET-442)
[SCAN4NET-442]: https://sonarsource.atlassian.net/browse/SCAN4NET-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-442 Bump version to 10.2

- its/pom.xml
[SCAN4NET-444](https://sonarsource.atlassian.net/browse/SCAN4NET-444)
[SCAN4NET-444]: https://sonarsource.atlassian.net/browse/SCAN4NET-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-444 Bump orchestrator to 5.5.0.2535

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Certificates/CertificateBuilder.Net.Tests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilder.Net.Test.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/WebClientDownloaderBuilderTest.cs
- Tests/TestUtilities/Certificates/CertificateBuilder.Net.cs
- Tests/TestUtilities/Certificates/CertificateBuilder.cs
[SCAN4NET-415](https://sonarsource.atlassian.net/browse/SCAN4NET-415)
[SCAN4NET-415]: https://sonarsource.atlassian.net/browse/SCAN4NET-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-415 Fix certificate related Unit Tests on MacOS

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/AzureTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BaseCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BuildCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/GeneralCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/RestoreCommand.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
[SCAN4NET-328](https://sonarsource.atlassian.net/browse/SCAN4NET-328)
[SCAN4NET-328]: https://sonarsource.atlassian.net/browse/SCAN4NET-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-328 Add IT testing TF_BUILD case

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
[SCAN4NET-431](https://sonarsource.atlassian.net/browse/SCAN4NET-431)
[SCAN4NET-431]: https://sonarsource.atlassian.net/browse/SCAN4NET-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Repro SCAN4NET-431

- Tests/SonarScanner.MSBuild.Common.Test/ILoggerTests.cs
- Tests/TestUtilities/TestLogger.cs
- src/SonarScanner.MSBuild.Common/ConsoleLogger.cs
- src/SonarScanner.MSBuild.Common/FileConstants.cs
- src/SonarScanner.MSBuild.Common/IO/FileWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IFileWrapper.cs
- src/SonarScanner.MSBuild.Common/Interfaces/ILogger.cs
- src/SonarScanner.MSBuild.Tasks/MSBuildLoggerAdapter.cs
[SCAN4NET-453](https://sonarsource.atlassian.net/browse/SCAN4NET-453)
[SCAN4NET-453]: https://sonarsource.atlassian.net/browse/SCAN4NET-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-453 Add telemetry endpoint to ILogger in S4NET

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/MSBuildExecution/BuildRunner.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/WriteTelemetryTaskTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/WriteTelemetryTests.cs
- src/SonarScanner.MSBuild.Common/IO/FileWrapper.cs
- src/SonarScanner.MSBuild.Common/IO/IFileWrapper.cs
- src/SonarScanner.MSBuild.Tasks/WriteTelemetry.cs
[SCAN4NET-455](https://sonarsource.atlassian.net/browse/SCAN4NET-455)
[SCAN4NET-455]: https://sonarsource.atlassian.net/browse/SCAN4NET-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-455 Create Custom Task to write telemetry from targets

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/Infrastructure/TargetConstants.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarIntegrationTargetsTests.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
[SCAN4NET-482](https://sonarsource.atlassian.net/browse/SCAN4NET-482)
[SCAN4NET-482]: https://sonarsource.atlassian.net/browse/SCAN4NET-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-482 Calculate the SonarTelemetryFilePath property in Sonarqube.Intergration.targets

- .github/renovate.json
- .github/workflows/ToggleLockBranch.yml
[SCAN4NET-479](https://sonarsource.atlassian.net/browse/SCAN4NET-479)
It's a draft for now to prevent merging, so we can see if something pops up on AutoScan first
[SCAN4NET-479]: https://sonarsource.atlassian.net/browse/SCAN4NET-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-479 Use Renovate

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/WriteSonarTelemetryTaskTests.cs
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/WriteSonarTelemetryTests.cs
- src/SonarScanner.MSBuild.Tasks/WriteSonarTelemetry.cs
[SCAN4NET-492](https://sonarsource.atlassian.net/browse/SCAN4NET-492)
[SCAN4NET-492]: https://sonarsource.atlassian.net/browse/SCAN4NET-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-492 Rename WriteTelemetry to WriteSonarTelemetry

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RazorTargetTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/RoslynTargetsTests.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/TargetsTests/SonarIntegrationTargetsTests.cs
- src/SonarScanner.MSBuild.Common/FileConstants.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
[SCAN4NET-456](https://sonarsource.atlassian.net/browse/SCAN4NET-456)
[SCAN4NET-456]: https://sonarsource.atlassian.net/browse/SCAN4NET-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-456 Create Telemetry for MSBuild parameters and project build.

- its/projects/Telemetry/SonarQube.Analysis.xml
- its/projects/Telemetry/Telemetry.sln
- its/projects/Telemetry/Telemetry/Telemetry.cs
- its/projects/Telemetry/Telemetry/Telemetry.csproj
- its/projects/Telemetry/TelemetryLibrary/TelemetryLibrary.cs
- its/projects/Telemetry/TelemetryLibrary/TelemetryLibrary.csproj
- its/projects/Telemetry/TelemetryUtils/TelemetryUtils.cs
- its/projects/Telemetry/TelemetryUtils/TelemetryUtils.csproj
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
[SCAN4NET-496](https://sonarsource.atlassian.net/browse/SCAN4NET-496)
[SCAN4NET-496]: https://sonarsource.atlassian.net/browse/SCAN4NET-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-496 Add telemetry IT

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
[SCAN4NET-519](https://sonarsource.atlassian.net/browse/SCAN4NET-519)
Part of SCAN4NET-460
Extracted from #2520
[SCAN4NET-519]: https://sonarsource.atlassian.net/browse/SCAN4NET-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-519 Change target telemetry to MSBuildVersion

- azure-pipelines.yml
- scripts/Mend/wss-unified-agent.config
[SCAN4NET-520](https://sonarsource.atlassian.net/browse/SCAN4NET-520)
[SCAN4NET-520]: https://sonarsource.atlassian.net/browse/SCAN4NET-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-520 Scan CLI Jar in Mend

- scripts/Mend/wss-unified-agent.config
[SCAN4NET-528](https://sonarsource.atlassian.net/browse/SCAN4NET-528)
Part of SCAN4NET-520
[SCAN4NET-528]: https://sonarsource.atlassian.net/browse/SCAN4NET-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-528 Extract Jar archive in Mend

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudTests.java
[SCAN4NET-488](https://sonarsource.atlassian.net/browse/SCAN4NET-488)
[SCAN4NET-488]: https://sonarsource.atlassian.net/browse/SCAN4NET-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-488 Fail SQ-C ITs like the SslTest early

- its/pom.xml
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
[SCAN4NET-625](https://sonarsource.atlassian.net/browse/SCAN4NET-625)
[SCAN4NET-625]: https://sonarsource.atlassian.net/browse/SCAN4NET-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-625 Update JGit dependency

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/CppTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/Workload.java
[SCAN4NET-490](https://sonarsource.atlassian.net/browse/SCAN4NET-490)
[SCAN4NET-490]: https://sonarsource.atlassian.net/browse/SCAN4NET-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-490 Fix CppTest

- .github/renovate.json
[SCAN4NET-629](https://sonarsource.atlassian.net/browse/SCAN4NET-629)
[SCAN4NET-629]: https://sonarsource.atlassian.net/browse/SCAN4NET-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-629 Renovate: Set rebaseWhen to auto

- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/LocalJreTruststoreResolverTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
[SCAN4NET-638](https://sonarsource.atlassian.net/browse/SCAN4NET-638)
Part of 
[SCAN4NET-638]: https://sonarsource.atlassian.net/browse/SCAN4NET-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-638 UTs: Fix Quality Gate

- AssemblyInfo.Shared.cs
- nuspec/netcoreglobaltool/dotnet-sonarscanner.nuspec
- scripts/version/Version.props
[SCAN4NET-662](https://sonarsource.atlassian.net/browse/SCAN4NET-662)
[SCAN4NET-662]: https://sonarsource.atlassian.net/browse/SCAN4NET-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-662 Bump version to 10.4

- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
[SCAN4NET-649](https://sonarsource.atlassian.net/browse/SCAN4NET-649)
Part of [SCAN4NET-387](https://sonarsource.atlassian.net/browse/SCAN4NET-387)
[SCAN4NET-387]: https://sonarsource.atlassian.net/browse/SCAN4NET-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-649]: https://sonarsource.atlassian.net/browse/SCAN4NET-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-649 Cleanup E2EAnalysisTests

- Tests/SonarScanner.MSBuild.PostProcessor.Test/AnalysisWarningProcessorTests.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/TargetsUninstallerTests.cs
[SCAN4NET-433](https://sonarsource.atlassian.net/browse/SCAN4NET-433)
[SCAN4NET-433]: https://sonarsource.atlassian.net/browse/SCAN4NET-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-433 SonarScanner.MSBuild.PostProcessor.Test: Fix failing UTs on Linux/MacOS

- Tests/SonarScanner.MSBuild.Common.Test/UtilitiesTests.cs
[SCAN4NET-679](https://sonarsource.atlassian.net/browse/SCAN4NET-679)
Part of SCAN4NET-432
probably easiest to review by commit
[SCAN4NET-679]: https://sonarsource.atlassian.net/browse/SCAN4NET-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-679 Mark UtilitiesTests Tests as non-Unix

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
[SCAN4NET-683](https://sonarsource.atlassian.net/browse/SCAN4NET-683)
[SCAN4NET-683]: https://sonarsource.atlassian.net/browse/SCAN4NET-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-683 Make ArgumentProcessorTests.cs work on Linux

- Tests/TestUtilities/TestCategories.cs
[SCAN4NET-699](https://sonarsource.atlassian.net/browse/SCAN4NET-699)
Part of SCAN4NET-414
[SCAN4NET-699]: https://sonarsource.atlassian.net/browse/SCAN4NET-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-699 Remove TestCategories.NoUnixNeedsReview

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/FileCacheTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreCacheTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/FileCache.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/IFileCache.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreCache.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-734](https://sonarsource.atlassian.net/browse/SCAN4NET-734)
I hope to pull out the download logic in the next PR, but we'll see.
[SCAN4NET-734]: https://sonarsource.atlassian.net/browse/SCAN4NET-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-734 Extract IChecksum to IFileCache

- Tests/SonarScanner.MSBuild.PostProcessor.Test/Infrastructure/MockSonarScanner.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/Infrastructure/MockTFSProcessor.cs
- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
[SCAN4NET-743](https://sonarsource.atlassian.net/browse/SCAN4NET-743)
Part of SCAN4NET-705
[SCAN4NET-743]: https://sonarsource.atlassian.net/browse/SCAN4NET-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-743 Improve PostProcessorTests

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/FileCacheTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/FileCache.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/IFileCache.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreCache.cs
[SCAN4NET-744](https://sonarsource.atlassian.net/browse/SCAN4NET-744)
based on #2666
[SCAN4NET-744]: https://sonarsource.atlassian.net/browse/SCAN4NET-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-744 Implement DownloadFileAsync in FileCache

- Tests/SonarScanner.MSBuild.Shim.Test/JsonPropertiesWriterTest.cs
- src/SonarScanner.MSBuild.Shim/JsonPropertiesWriter.cs
[SCAN4NET-769](https://sonarsource.atlassian.net/browse/SCAN4NET-769)
~~`Squash mary/jsonwriter-implementation` commit is squash of #2665 and should be ignored during review~~
[SCAN4NET-769]: https://sonarsource.atlassian.net/browse/SCAN4NET-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-769 JsonPropertiesWriter: Rework sonar.modules

- src/SonarScanner.MSBuild.PostProcessor/Properties/AssemblyInfo.cs
[SCAN4NET-773](https://sonarsource.atlassian.net/browse/SCAN4NET-773)
Part of 
[SCAN4NET-773]: https://sonarsource.atlassian.net/browse/SCAN4NET-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-773 Update PostProcessor InternalsVisibleTo with PublicKey when Signed

- Tests/SonarScanner.MSBuild.Shim.Test/JsonPropertiesWriterTest.cs
- src/SonarScanner.MSBuild.Shim/JsonPropertiesWriter.cs
[SCAN4NET-766](https://sonarsource.atlassian.net/browse/SCAN4NET-766)
[SCAN4NET-766]: https://sonarsource.atlassian.net/browse/SCAN4NET-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-766 Add missing content to JsonPropertiesWriter

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
[SCAN4NET-774](https://sonarsource.atlassian.net/browse/SCAN4NET-774)
Part of SCAN4NET-708
[SCAN4NET-774]: https://sonarsource.atlassian.net/browse/SCAN4NET-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-774 Rename JsonPropertiesWriter to ScannerEngineInput

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectInfoReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests_MultiTarget.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoAnalysisResult.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoReportBuilder.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
- src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs
[SCAN4NET-779](https://sonarsource.atlassian.net/browse/SCAN4NET-779)
Part of SCAN4NET-708
[SCAN4NET-779]: https://sonarsource.atlassian.net/browse/SCAN4NET-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-779 Cleanup ProjectInfoAnalysisResult and add engine input

- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.GenerateFile.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.MultiTarget.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.TryWriteProperties.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesFileGeneratorTests.cs
- src/SonarScanner.MSBuild.Shim/PropertiesFileGenerator.cs
[SCAN4NET-752](https://sonarsource.atlassian.net/browse/SCAN4NET-752)
[SCAN4NET-752]: https://sonarsource.atlassian.net/browse/SCAN4NET-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-752 Call new ScannerEngineInput in PropertiesFileGenerator

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.ComputeProjectBaseDir.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateFile.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.MultiTarget.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.ToProjectData.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.TryWriteProperties.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/E2ETests/E2EAnalysisTests.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
- src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs
- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
[SCAN4NET-794](https://sonarsource.atlassian.net/browse/SCAN4NET-794)
Part of SCAN4NET-708
[SCAN4NET-794]: https://sonarsource.atlassian.net/browse/SCAN4NET-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-794 Rename PropertiesFileGenerator to ScannerEngineInputGenerator

- Tests/SonarScanner.MSBuild.Shim.Test/MockRuntimeInformation.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.ComputeProjectBaseDir.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateFile.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- src/SonarScanner.MSBuild.Common/RuntimeInformationWrapper.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-792](https://sonarsource.atlassian.net/browse/SCAN4NET-792)
Part of SCAN4NET-778
[SCAN4NET-792]: https://sonarsource.atlassian.net/browse/SCAN4NET-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-792 Rework RuntimeInformationWrapper

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectDataTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectInfoReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarProjectPropertiesValidatorTest.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs
- src/SonarScanner.MSBuild.Shim/ProjectData.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoExtensions.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-795](https://sonarsource.atlassian.net/browse/SCAN4NET-795)
[SCAN4NET-795]: https://sonarsource.atlassian.net/browse/SCAN4NET-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-795 Move ToProjectData out of PropertiesFileGenerator

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectDataTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectInfoReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.TryWriteProperties.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarProjectPropertiesValidatorTest.cs
- Tests/SonarScanner.MSBuild.TFS.Test/ProgramTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoExtensions.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
- src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs
[SCAN4NET-778](https://sonarsource.atlassian.net/browse/SCAN4NET-778)
Review per commit is highly recommended, as there are few steps to go through
The `SummaryReportBuilder` gets bit more noisy on the way, to show what it really does, before it gets cleaned up.
[SCAN4NET-778]: https://sonarsource.atlassian.net/browse/SCAN4NET-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-778 Untangle ProjectInfoAnalysisResult from SummaryReportBuilder

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockSonarWebServer.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarCloudWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarQubeWebServerTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServerTest.cs
[SCAN4NET-762](https://sonarsource.atlassian.net/browse/SCAN4NET-762)
[SCAN4NET-762]: https://sonarsource.atlassian.net/browse/SCAN4NET-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-762 Cleanup SonarWebServer Tests

- Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-799](https://sonarsource.atlassian.net/browse/SCAN4NET-799)
[SCAN4NET-799]: https://sonarsource.atlassian.net/browse/SCAN4NET-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-799 EngineResolver Downloads ScannerEngine

- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
[SCAN4NET-801](https://sonarsource.atlassian.net/browse/SCAN4NET-801)
Part of SCAN4NET-767
[SCAN4NET-801]: https://sonarsource.atlassian.net/browse/SCAN4NET-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-801 Cleanup ScannerEngineInput syntax

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ProvisioningAssertions.java
[SCAN4NET-809](https://sonarsource.atlassian.net/browse/SCAN4NET-809)
[SCAN4NET-809]: https://sonarsource.atlassian.net/browse/SCAN4NET-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-809 Scanner Engine Provisioning ITs

- Tests/SonarScanner.MSBuild.TFS.Test/TrxFileReaderTests.cs
- src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/TrxFileReader.cs
[SCAN4NET-812](https://sonarsource.atlassian.net/browse/SCAN4NET-812)
[SCAN4NET-812]: https://sonarsource.atlassian.net/browse/SCAN4NET-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-812 Use IRuntime in TrxFileReader

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Interfaces/IPreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
[SCAN4NET-815](https://sonarsource.atlassian.net/browse/SCAN4NET-815)
[SCAN4NET-815]: https://sonarsource.atlassian.net/browse/SCAN4NET-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-815 Use IRuntime in PreporcessorObjectFactor

- Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
[SCAN4NET-819](https://sonarsource.atlassian.net/browse/SCAN4NET-819)
[SCAN4NET-819]: https://sonarsource.atlassian.net/browse/SCAN4NET-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-819 Use IRuntime in EngineResolver

- Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
[SCAN4NET-834](https://sonarsource.atlassian.net/browse/SCAN4NET-834)
[SCAN4NET-834]: https://sonarsource.atlassian.net/browse/SCAN4NET-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-834 Use IRuntime in TargetsInstaller

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
[SCAN4NET-818](https://sonarsource.atlassian.net/browse/SCAN4NET-818)
[SCAN4NET-818]: https://sonarsource.atlassian.net/browse/SCAN4NET-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-818 Use IRuntime in JreResolver

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Unpacking/UnpackerFactoryTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/Unpacking/UnpackerFactory.cs
[SCAN4NET-820](https://sonarsource.atlassian.net/browse/SCAN4NET-820)
[SCAN4NET-820]: https://sonarsource.atlassian.net/browse/SCAN4NET-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-820 Use IRuntime in UnpackerFactory

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
[SCAN4NET-828](https://sonarsource.atlassian.net/browse/SCAN4NET-828)
[SCAN4NET-828]: https://sonarsource.atlassian.net/browse/SCAN4NET-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-828 Use IRuntime in JreDownloader

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
[SCAN4NET-829](https://sonarsource.atlassian.net/browse/SCAN4NET-829)
Skip the first two commits. They are coming from #2746.
[SCAN4NET-829]: https://sonarsource.atlassian.net/browse/SCAN4NET-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-829 Use IRuntime in CachedDownloader

- Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.Common/Interfaces/IMsBuildPathsSettings.cs
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
[SCAN4NET-836](https://sonarsource.atlassian.net/browse/SCAN4NET-836)
[SCAN4NET-836]: https://sonarsource.atlassian.net/browse/SCAN4NET-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-836 Use IRuntime in MsBuildPathSettings

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ScannerCommand.java
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
[SCAN4NET-840](https://sonarsource.atlassian.net/browse/SCAN4NET-840)
Part of [SCAN4NET-710](https://sonarsource.atlassian.net/browse/SCAN4NET-710)
Replaces https://github.com/SonarSource/sonar-scanner-msbuild/pull/2757
[SCAN4NET-710]: https://sonarsource.atlassian.net/browse/SCAN4NET-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCAN4NET-840]: https://sonarsource.atlassian.net/browse/SCAN4NET-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-840 Enable ScannerEngine code path

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild/DefaultProcessorFactory.cs
[SCAN4NET-849](https://sonarsource.atlassian.net/browse/SCAN4NET-849)
Part of 
[SCAN4NET-849]: https://sonarsource.atlassian.net/browse/SCAN4NET-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-849 Use IRuntime in PostProcessor

- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/Infrastructure/MockObjectFactory.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs
[SCAN4NET-851](https://sonarsource.atlassian.net/browse/SCAN4NET-851)
[SCAN4NET-851]: https://sonarsource.atlassian.net/browse/SCAN4NET-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-851 Use IRuntime in MockObjectFactory

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.ComputeProjectBaseDir.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateProperties.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateResult.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.MultiTarget.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-850](https://sonarsource.atlassian.net/browse/SCAN4NET-850)
Part of 
[SCAN4NET-850]: https://sonarsource.atlassian.net/browse/SCAN4NET-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-850 Use IRuntime in ScannerEngineInputGenerator

- Tests/SonarScanner.MSBuild.Test/BootstrapperClassTests.cs
[SCAN4NET-871](https://sonarsource.atlassian.net/browse/SCAN4NET-871)
[SCAN4NET-871]: https://sonarsource.atlassian.net/browse/SCAN4NET-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-871 Fix BootstrapperClassTests merge conflict

- Tests/SonarScanner.MSBuild.Shim.Test/AdditionalFilesServiceTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.ComputeProjectBaseDir.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateResult.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-846](https://sonarsource.atlassian.net/browse/SCAN4NET-846)
[SCAN4NET-846]: https://sonarsource.atlassian.net/browse/SCAN4NET-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-846 Use IRuntime in AdditionalFilesService

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectDataTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ProjectInfoReportBuilderTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateProperties.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/SonarProjectPropertiesValidatorTest.cs
- Tests/SonarScanner.MSBuild.TFS.Test/SummaryReportBuilderTests.cs
- src/SonarScanner.MSBuild.Shim/ProjectData.cs
- src/SonarScanner.MSBuild.Shim/ProjectInfoExtensions.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
- src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs
[SCAN4NET-874](https://sonarsource.atlassian.net/browse/SCAN4NET-874)
Part of 
[SCAN4NET-874]: https://sonarsource.atlassian.net/browse/SCAN4NET-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-874 Use IRuntime in ProjectData

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputTest.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
[SCAN4NET-875](https://sonarsource.atlassian.net/browse/SCAN4NET-875)
Part of SCAN4NET-710
[SCAN4NET-875]: https://sonarsource.atlassian.net/browse/SCAN4NET-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-875 Deduplicate keys in ScannerEngineInput

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
[SCAN4NET-864](https://sonarsource.atlassian.net/browse/SCAN4NET-864)
[SCAN4NET-864]: https://sonarsource.atlassian.net/browse/SCAN4NET-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-864 Use IRuntime in ArgumentProcessor

- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/LocalJreTruststoreResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/LocalJreTruststoreResolver.cs
[SCAN4NET-870](https://sonarsource.atlassian.net/browse/SCAN4NET-870)
[SCAN4NET-870]: https://sonarsource.atlassian.net/browse/SCAN4NET-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-870 Use IRuntime in LocalJreTruststoreResolver

- Tests/SonarScanner.MSBuild.Shim.Test/SonarEngineWrapperTest.cs
- src/SonarScanner.MSBuild.Shim/SonarEngineWrapper.cs
[SCAN4NET-880](https://sonarsource.atlassian.net/browse/SCAN4NET-880)
Part of 
[SCAN4NET-880]: https://sonarsource.atlassian.net/browse/SCAN4NET-880
> SCAN4NET-880 Parse SONAR_SCANNER_OPTS and send to Scanner Engine

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/ProgramTests.cs
- Tests/TestUtilities/TestRuntime.cs
- src/SonarScanner.MSBuild.Common/Interfaces/ILogger.cs
- src/SonarScanner.MSBuild.Common/Interfaces/IRuntime.cs
- src/SonarScanner.MSBuild.Common/Runtime.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/LocalJreTruststoreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreprocessorObjectFactory.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
- src/SonarScanner.MSBuild.Shim/AdditionalFilesService.cs
- src/SonarScanner.MSBuild.Shim/ProjectData.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
- src/SonarScanner.MSBuild.Shim/SonarEngineWrapper.cs
- src/SonarScanner.MSBuild.TFS.Classic/Program.cs
- src/SonarScanner.MSBuild.TFS/BuildVNextCoverageReportProcessor.cs
- src/SonarScanner.MSBuild.TFS/SummaryReportBuilder.cs
- src/SonarScanner.MSBuild.TFS/TrxFileReader.cs
- src/SonarScanner.MSBuild/Program.cs
[SCAN4NET-894](https://sonarsource.atlassian.net/browse/SCAN4NET-894)
[SCAN4NET-894]: https://sonarsource.atlassian.net/browse/SCAN4NET-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-894 Create convenience Log methods in IRuntime

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/CacheResult.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
[SCAN4NET-884](https://sonarsource.atlassian.net/browse/SCAN4NET-884)
Part of SCAN4NET-881
[SCAN4NET-884]: https://sonarsource.atlassian.net/browse/SCAN4NET-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-884 Remove ResolveCacheRoot from IsJreCached

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ProvisioningAssertions.java
- src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/DownloadResult.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-891](https://sonarsource.atlassian.net/browse/SCAN4NET-891)
Part of SCAN4NET-881
[SCAN4NET-891]: https://sonarsource.atlassian.net/browse/SCAN4NET-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-891 Remove IsFileCached

- its/src/test/java/com/sonar/it/scanner/msbuild/utils/BaseCommand.java
[SCAN4NET-897](https://sonarsource.atlassian.net/browse/SCAN4NET-897)
Part of SCAN4NET-114
[SCAN4NET-897]: https://sonarsource.atlassian.net/browse/SCAN4NET-897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-897 Increase default timeout to two minutes

- Tests/SonarScanner.MSBuild.Shim.Test/SonarEngineWrapperTest.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/BaseDirTest.java
- src/SonarScanner.MSBuild.Shim/SonarEngineWrapper.cs
[SCAN4NET-861](https://sonarsource.atlassian.net/browse/SCAN4NET-861)
[SCAN4NET-861]: https://sonarsource.atlassian.net/browse/SCAN4NET-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-861 Scanner Engine: Fix ProjectBaseDir ITs

- Tests/SonarScanner.MSBuild.Shim.Test/SonarScannerWrapperTests.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
[SCAN4NET-905](https://sonarsource.atlassian.net/browse/SCAN4NET-905)
Part of SCAN4NET-114
Fixes two issues present in the feature branch at the moment:
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&pullRequest=2763&id=sonarscanner-msbuild
[SCAN4NET-905]: https://sonarsource.atlassian.net/browse/SCAN4NET-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-905 Fix SQ issues

- Tests/SonarScanner.MSBuild.PreProcessor.Test/Caching/CachedDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/CachedDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/Caching/DownloadResult.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-881](https://sonarsource.atlassian.net/browse/SCAN4NET-881)
This is a cleanup and simplification PR after the main changes were done in sub-tasks.
[SCAN4NET-881]: https://sonarsource.atlassian.net/browse/SCAN4NET-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-881 Consolidate caching and download functionality

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ProvisioningAssertions.java
[SCAN4NET-858](https://sonarsource.atlassian.net/browse/SCAN4NET-858)
[SCAN4NET-858]: https://sonarsource.atlassian.net/browse/SCAN4NET-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-858 Scanner Engine: Fix Provisioning ITs

- Tests/SonarScanner.MSBuild.Common.Test/Telemetry/TelemetryUtilsTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/TelemetryTest.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/EngineResolution/EngineResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.Telemetry.cs
- Tests/TestUtilities/Assertions/TestTelemetryAssertions.cs
- Tests/TestUtilities/TestTelemetry.cs
- src/SonarScanner.MSBuild.Common/Interfaces/ITelemetry.cs
- src/SonarScanner.MSBuild.Common/Telemetry.cs
- src/SonarScanner.MSBuild.Common/Telemetry/TelemetryUtils.cs
- src/SonarScanner.MSBuild.PostProcessor/PostProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/EngineResolution/EngineResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
[SCAN4NET-910](https://sonarsource.atlassian.net/browse/SCAN4NET-910)
Part of SCAN4NET-114
[SCAN4NET-910]: https://sonarsource.atlassian.net/browse/SCAN4NET-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-910 Make Telemetry.messages a Dictionary

- Tests/SonarScanner.MSBuild.Common.Test/AnalysisConfig/AnalysisConfigExtensionsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs
- Tests/SonarScanner.MSBuild.Shim.Test/PropertiesWriterTest.cs
- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateResult.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/MultiLanguageTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/SslTest.java
- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfigExtensions.cs
- src/SonarScanner.MSBuild.Common/SonarProperties.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/AnalysisConfigProcessorBase.cs
- src/SonarScanner.MSBuild.PreProcessor/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessor.cs
- src/SonarScanner.MSBuild.Shim/PropertiesWriter.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInput.cs
- src/SonarScanner.MSBuild.Shim/ScannerEngineInputGenerator.cs
[SCAN4NET-901](https://sonarsource.atlassian.net/browse/SCAN4NET-901)
This reverts commit 4ac2c3ee0ee7b099f3405da528a27c6db2cde873.
Part of 
[SCAN4NET-901]: https://sonarsource.atlassian.net/browse/SCAN4NET-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "SCAN4NET-901 Pass ScannerOpts to Scanner-Engine (#2809)"

- Tests/SonarScanner.MSBuild.Common.Test/MsBuildPathSettingsTests.cs
- Tests/SonarScanner.MSBuild.Common.Test/OperatingSystemProviderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/TargetsInstallerTests.cs
- src/SonarScanner.MSBuild.Common/MsBuildPathSettings.cs
- src/SonarScanner.MSBuild.Common/OperatingSystemProvider.cs
- src/SonarScanner.MSBuild.PreProcessor/TargetsInstaller.cs
[SCAN4NET-920](https://sonarsource.atlassian.net/browse/SCAN4NET-920)
[SCAN4NET-920]: https://sonarsource.atlassian.net/browse/SCAN4NET-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-920 Remove OperatingSystem.DirectoryExists

- Tests/SonarScanner.MSBuild.PostProcessor.Test/PostProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/AnalysisConfigGeneratorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/AnalysisConfigProcessing/Processors/TruststorePropertiesProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArgumentProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/CacheProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/LocalJreTruststoreResolverTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreProcessorTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/PreprocessorObjectFactoryTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/ProcessedArgsTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/RoslynAnalyzerProviderTests.cs
- Tests/SonarScanner.MSBuild.TFS.Test/Classic/TfsLegacyCoverageReportProcessorTests.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarcloud/CloudProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProvisioningTest.java
- its/src/test/java/com/sonar/it/scanner/msbuild/utils/ProvisioningAssertions.java
- src/SonarScanner.MSBuild.Common/TFS/BuildSettings.cs
- src/SonarScanner.MSBuild.PreProcessor/ArgumentProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/PreProcessor.cs
- src/SonarScanner.MSBuild.PreProcessor/ProcessedArgs.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-929](https://sonarsource.atlassian.net/browse/SCAN4NET-929)
Part of SCAN4NET-114
[SCAN4NET-929]: https://sonarsource.atlassian.net/browse/SCAN4NET-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-929 Set UseSonarScannerCli when in TFS Legacy build

- Tests/SonarScanner.MSBuild.Shim.Test/ScannerEngineInputGeneratorTest.GenerateResult.cs
[SCAN4NET-887](https://sonarsource.atlassian.net/browse/SCAN4NET-887)
Seems like most of the work was done already by other PRs.
[SCAN4NET-887]: https://sonarsource.atlassian.net/browse/SCAN4NET-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-887 Cleanup ScannerEngineInputGeneratorTest.GenerateResult.cs

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ScannerTest.java
[SCAN4NET-868](https://sonarsource.atlassian.net/browse/SCAN4NET-868)
[SCAN4NET-868]: https://sonarsource.atlassian.net/browse/SCAN4NET-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-868 ScannerEngine: Fix ScannerTest Its

- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarWebServerTest.cs
- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/ProvisioningTest.java
- src/SonarScanner.MSBuild.PreProcessor/WebServer/SonarWebServerBase.cs
[SCAN4NET-926](https://sonarsource.atlassian.net/browse/SCAN4NET-926)
SCAN4NET-926 Don't warn when sonar.jreAutoProvisioning.disabled is true
[SCAN4NET-926]: https://sonarsource.atlassian.net/browse/SCAN4NET-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-926 Don't warn when sonar.jreAutoProvisioning.disabled is true

- its/src/test/java/com/sonar/it/scanner/msbuild/sonarqube/TelemetryTest.java
[SCAN4NET-945](https://sonarsource.atlassian.net/browse/SCAN4NET-945)
[SCAN4NET-945]: https://sonarsource.atlassian.net/browse/SCAN4NET-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-945 Better assertions for telemetry

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ArchiveDownloaderTests.cs
- Tests/SonarScanner.MSBuild.PreProcessor.Test/JreResolution/JreResolverTests.cs
- src/SonarScanner.MSBuild.PreProcessor/ArchiveDownloader.cs
- src/SonarScanner.MSBuild.PreProcessor/JreResolution/JreResolver.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.Designer.cs
- src/SonarScanner.MSBuild.PreProcessor/Resources.resx
[SCAN4NET-951](https://sonarsource.atlassian.net/browse/SCAN4NET-951)
Part of SCAN4NET-940
[SCAN4NET-951]: https://sonarsource.atlassian.net/browse/SCAN4NET-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-951 Move UnpackerFactory.Create into ArchiveDownloader

- Tests/SonarScanner.MSBuild.PreProcessor.Test/ScannerCliResolverTests.cs
- src/SonarScanner.MSBuild.Common/Telemetry/TelemetryKeys.cs
- src/SonarScanner.MSBuild.Common/Telemetry/TelemetryValues.cs
- src/SonarScanner.MSBuild.PreProcessor/ScannerCliResolver.cs
[SCAN4NET-957](https://sonarsource.atlassian.net/browse/SCAN4NET-957)
SCAN4NET-957 Add telemetry to ScannerCliResolver
[SCAN4NET-957]: https://sonarsource.atlassian.net/browse/SCAN4NET-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-957 Add telemetry to ScannerCliResolver

- src/SonarScanner.MSBuild.Common/AnalysisConfig/AnalysisConfig.cs
[SCAN4NET-960](https://sonarsource.atlassian.net/browse/SCAN4NET-960)
Part of SCAN4NET-941
[SCAN4NET-960]: https://sonarsource.atlassian.net/browse/SCAN4NET-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-960 Add SonarScannerCliPath

- Tests/Directory.Build.targets
- Tests/SonarScanner.MSBuild.Common.Test/SonarScanner.MSBuild.Common.Test.csproj
- Tests/SonarScanner.MSBuild.Common.Test/packages.lock.json
- Tests/SonarScanner.MSBuild.PostProcessor.Test/SonarScanner.MSBuild.PostProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PostProcessor.Test/packages.lock.json
- Tests/SonarScanner.MSBuild.PreProcessor.Test/SonarScanner.MSBuild.PreProcessor.Test.csproj
- Tests/SonarScanner.MSBuild.PreProcessor.Test/packages.lock.json
- Tests/SonarScanner.MSBuild.Shim.Test/SonarScanner.MSBuild.Shim.Test.csproj
- Tests/SonarScanner.MSBuild.Shim.Test/packages.lock.json
- Tests/SonarScanner.MSBuild.TFS.Test/SonarScanner.MSBuild.TFS.Test.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/SonarScanner.MSBuild.Tasks.IntegrationTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.IntegrationTest/packages.lock.json
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/SonarScanner.MSBuild.Tasks.UnitTest.csproj
- Tests/SonarScanner.MSBuild.Tasks.UnitTest/packages.lock.json
- Tests/SonarScanner.MSBuild.Test/SonarScanner.MSBuild.Test.csproj
- Tests/SonarScanner.MSBuild.Test/packages.lock.json
- Tests/TestUtilities/TestUtilities.csproj
- Tests/TestUtilities/packages.lock.json
[SCAN4NET-973](https://sonarsource.atlassian.net/browse/SCAN4NET-973)
Part of SCAN4NET-631
[SCAN4NET-973]: https://sonarsource.atlassian.net/browse/SCAN4NET-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-973 UTs: Extract dependencies into a single place

- src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.targets
[SCAN4NET-930](https://sonarsource.atlassian.net/browse/SCAN4NET-930)
Part of 
[SCAN4NET-930]: https://sonarsource.atlassian.net/browse/SCAN4NET-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCAN4NET-930 Update telemetry targets to be compatible with older MSBuild
